// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // ADMINC_12_SERVICIOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Admin_Adminc12ServicioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Admin_Adminc12Servicio>
    {
        public Admin_Adminc12ServicioConfiguration()
            : this("Admin")
        {
        }

        public Admin_Adminc12ServicioConfiguration(string schema)
        {
            ToTable("ADMINC_12_SERVICIOS", schema);
            HasKey(x => x.NIdServicio12);

            Property(x => x.NIdServicio12).HasColumnName(@"nIdServicio12").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SClave).HasColumnName(@"sClave").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SDescripcion).HasColumnName(@"sDescripcion").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(200);
            Property(x => x.NCostoProduccion).HasColumnName(@"nCostoProduccion").HasColumnType("decimal").IsOptional().HasPrecision(8,2);
            Property(x => x.BAplicaRestricciones).HasColumnName(@"bAplicaRestricciones").HasColumnType("bit").IsRequired();
            Property(x => x.BStatus).HasColumnName(@"bStatus").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
