// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // ADMINC_25_IVA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Admin_Adminc25Iva
    {
        [Required]
        [Display(Name = "N ID iva 25")]
        public int NIdIva25 { get; set; } // nIdIva25 (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "S descripcion")]
        public string SDescripcion { get; set; } // sDescripcion (length: 100)

        [Required]
        [Display(Name = "N valor")]
        public decimal NValor { get; set; } // nValor

        // Reverse navigation

        /// <summary>
        /// Child SIR_Sir123Cotizacione where [SIR_123_COTIZACIONES].[nIdIva25] point to this entity (FK_SIR_123_COTIZACIONES_ADMINC_25_IVA)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir123Cotizacione> SIR_Sir123Cotizacione { get; set; } // SIR_123_COTIZACIONES.FK_SIR_123_COTIZACIONES_ADMINC_25_IVA
        /// <summary>
        /// Child SIR_Sir314CotizacionMultiple where [SIR_314_COTIZACION_MULTIPLE].[nIdIva25] point to this entity (FK_SIR_314_COTIZACION_MULTIPLE_ADMINC_25_IVA)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir314CotizacionMultiple> SIR_Sir314CotizacionMultiple { get; set; } // SIR_314_COTIZACION_MULTIPLE.FK_SIR_314_COTIZACION_MULTIPLE_ADMINC_25_IVA

        public Admin_Adminc25Iva()
        {
            SIR_Sir123Cotizacione = new System.Collections.Generic.List<SIR_Sir123Cotizacione>();
            SIR_Sir314CotizacionMultiple = new System.Collections.Generic.List<SIR_Sir314CotizacionMultiple>();
        }
    }

}
// </auto-generated>
