// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // ADMINC_08_AGENTES_ADUANALES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Admin_Adminc08AgentesAduanale
    {
        [Required]
        [Display(Name = "N ID agente 08")]
        public int NIdAgente08 { get; set; } // nIdAgente08 (Primary key)

        [Required]
        [Display(Name = "N patente")]
        public int NPatente { get; set; } // nPatente

        [Required(AllowEmptyStrings = true)]
        [MaxLength(120)]
        [StringLength(120)]
        [Display(Name = "S razon social")]
        public string SRazonSocial { get; set; } // sRazonSocial (length: 120)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "S nombre")]
        public string SNombre { get; set; } // sNombre (length: 50)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "S apellido paterno")]
        public string SApellidoPaterno { get; set; } // sApellidoPaterno (length: 50)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "S apellido materno")]
        public string SApellidoMaterno { get; set; } // sApellidoMaterno (length: 50)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "S rfc")]
        public string SRfc { get; set; } // sRFC (length: 15)

        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "S curp")]
        public string SCurp { get; set; } // sCURP (length: 20)

        [Required]
        [Display(Name = "N tipo")]
        public byte NTipo { get; set; } // nTipo

        [Required]
        [Display(Name = "B status")]
        public bool BStatus { get; set; } // bStatus

        // Reverse navigation

        /// <summary>
        /// Child Admin_Adminc36AgentesAduanalesDir where [ADMINC_36_AGENTES_ADUANALES_DIR].[nIdAgente08] point to this entity (FK_ADMINC_36_AGENTES_ADUANALES_DIR_ADMINC_08_AGENTES_ADUANALES)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Admin_Adminc36AgentesAduanalesDir> Admin_Adminc36AgentesAduanalesDir { get; set; } // ADMINC_36_AGENTES_ADUANALES_DIR.FK_ADMINC_36_AGENTES_ADUANALES_DIR_ADMINC_08_AGENTES_ADUANALES
        /// <summary>
        /// Child Admin_Adminc39AgentesAduanalesMed where [ADMINC_39_AGENTES_ADUANALES_MED].[nIdAgente08] point to this entity (FK_ADMINC_39_AGENTES_ADUANALES_MED_ADMINC_08_AGENTES_ADUANALES)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Admin_Adminc39AgentesAduanalesMed> Admin_Adminc39AgentesAduanalesMed { get; set; } // ADMINC_39_AGENTES_ADUANALES_MED.FK_ADMINC_39_AGENTES_ADUANALES_MED_ADMINC_08_AGENTES_ADUANALES

        public Admin_Adminc08AgentesAduanale()
        {
            Admin_Adminc36AgentesAduanalesDir = new System.Collections.Generic.List<Admin_Adminc36AgentesAduanalesDir>();
            Admin_Adminc39AgentesAduanalesMed = new System.Collections.Generic.List<Admin_Adminc39AgentesAduanalesMed>();
        }
    }

}
// </auto-generated>
