// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // bco_cuentas
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class BcoCuenta
    {
        [Required]
        [Display(Name = "Id cta")]
        public int IdCta { get; set; } // id_cta (Primary key)

        [Required]
        [Display(Name = "Id usr")]
        public int IdUsr { get; set; } // id_usr

        [Required]
        [Display(Name = "Id bco")]
        public int IdBco { get; set; } // id_bco

        [Required]
        [Display(Name = "Id fmt 1")]
        public int IdFmt1 { get; set; } // id_fmt1

        [Required]
        [Display(Name = "Id fmt 2")]
        public int IdFmt2 { get; set; } // id_fmt2

        [Required]
        [Display(Name = "Id fmt 3")]
        public int IdFmt3 { get; set; } // id_fmt3

        [Required]
        [Display(Name = "Id mda")]
        public int IdMda { get; set; } // id_mda

        [Required]
        [Display(Name = "Id tip cta")]
        public int IdTipCta { get; set; } // id_tip_cta

        [Required(AllowEmptyStrings = true)]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Num")]
        public string Num { get; set; } // num (length: 30)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Clabe")]
        public string Clabe { get; set; } // clabe (length: 25)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Titular")]
        public string Titular { get; set; } // titular (length: 60)

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec alta")]
        public System.DateTime FecAlta { get; set; } // fec_alta

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec baja")]
        public System.DateTime FecBaja { get; set; } // fec_baja

        [Required]
        [Display(Name = "Cargos")]
        public double Cargos { get; set; } // cargos

        [Required]
        [Display(Name = "Abonos")]
        public double Abonos { get; set; } // abonos

        [Required]
        [Display(Name = "Saldo")]
        public double Saldo { get; set; } // saldo

        ///<summary>
        /// Fecha de la Ultima Conciliacion
        ///</summary>
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec concil")]
        public System.DateTime FecConcil { get; set; } // fec_concil

        [Required]
        [Display(Name = "No sig chk")]
        public int NoSigChk { get; set; } // no_sig_chk

        ///<summary>
        /// 0=cancelada 1=activa 2=cerrada
        ///</summary>
        [Required]
        [Display(Name = "Status")]
        public byte Status { get; set; } // status

        ///<summary>
        /// Saldo conciliado
        ///</summary>
        [Required]
        [Display(Name = "Saldo conc")]
        public double SaldoConc { get; set; } // saldo_conc

        ///<summary>
        /// id de la ultima conciliacion
        ///</summary>
        [Required]
        [Display(Name = "Id conc")]
        public int IdConc { get; set; } // id_conc

        [Required]
        [Display(Name = "Id cta ctb")]
        public int IdCtaCtb { get; set; } // id_cta_ctb

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Suc")]
        public string Suc { get; set; } // suc (length: 10)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(120)]
        [StringLength(120)]
        [Display(Name = "Dir")]
        public string Dir { get; set; } // dir (length: 120)

        [Required]
        [Display(Name = "Lim crd")]
        public double LimCrd { get; set; } // lim_crd

        [Required]
        [Display(Name = "Fondo fijo")]
        public double FondoFijo { get; set; } // fondo_fijo

        [Required]
        [Display(Name = "Id tip trn def")]
        public int IdTipTrnDef { get; set; } // id_TipTrn_def

        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Layout enc")]
        public string LayoutEnc { get; set; } // layout_enc (length: 1000)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Layout sep")]
        public string LayoutSep { get; set; } // layout_sep (length: 2)

        [Required]
        [Display(Name = "Layout inc enc")]
        public bool LayoutIncEnc { get; set; } // layout_inc_enc

        [Required]
        [Display(Name = "Id emp")]
        public int IdEmp { get; set; } // id_emp

        [Required]
        [Display(Name = "Tipo deuda")]
        public int TipoDeuda { get; set; } // tipo_deuda

        [Required]
        [Display(Name = "Layout ini fila")]
        public int LayoutIniFila { get; set; } // layout_ini_fila

        [Required]
        [Display(Name = "Id tip trn dep")]
        public int IdTipTrnDep { get; set; } // id_tip_trn_dep

        [Required]
        [Display(Name = "Id prov")]
        public int IdProv { get; set; } // id_prov

        [Required]
        [Display(Name = "Id clas")]
        public int IdClas { get; set; } // id_clas

        [Required]
        [Display(Name = "Bcosdo")]
        public double Bcosdo { get; set; } // bcosdo

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec bcosdo")]
        public System.DateTime FecBcosdo { get; set; } // fec_bcosdo

        [Required]
        [Display(Name = "C exp lay")]
        public byte CExpLay { get; set; } // c_exp_lay

        [Required]
        [Display(Name = "Id rel tar")]
        public int IdRelTar { get; set; } // id_rel_tar

        [Required]
        [Display(Name = "C term")]
        public byte CTerm { get; set; } // c_term

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Rfc")]
        public string Rfc { get; set; } // rfc (length: 20)

        [Required]
        [Display(Name = "C par rel")]
        public byte CParRel { get; set; } // c_par_rel

        [Required]
        [Display(Name = "Id cta aso")]
        public int IdCtaAso { get; set; } // id_cta_aso

        [Required]
        [Display(Name = "Id rel ddc")]
        public int IdRelDdc { get; set; } // id_rel_ddc

        [Required(AllowEmptyStrings = true)]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Num cliente")]
        public string NumCliente { get; set; } // num_cliente (length: 25)

        [Required]
        [Display(Name = "C pf")]
        public byte CPf { get; set; } // c_PF

        [Required]
        [Display(Name = "C flu")]
        public byte CFlu { get; set; } // c_Flu

        // Reverse navigation

        /// <summary>
        /// Child BcoAuxes where [bco_aux].[id_cta] point to this entity (FK_bco_aux_bco_cuentas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BcoAux> BcoAuxes { get; set; } // bco_aux.FK_bco_aux_bco_cuentas
        /// <summary>
        /// Child BcoConcs where [bco_conc].[id_cta] point to this entity (FK_bco_conc_bco_cuentas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BcoConc> BcoConcs { get; set; } // bco_conc.FK_bco_conc_bco_cuentas
        /// <summary>
        /// Child BcoDocs where [bco_doc].[id_cta] point to this entity (FK_bco_doc_bco_cuentas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BcoDoc> BcoDocs { get; set; } // bco_doc.FK_bco_doc_bco_cuentas
        /// <summary>
        /// Child BcoTransferencias where [bco_transferencias].[id_cta_abo] point to this entity (FK_bco_transferencias_bco_cuentas1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BcoTransferencia> BcoTransferencias_IdCtaAbo { get; set; } // bco_transferencias.FK_bco_transferencias_bco_cuentas1
        /// <summary>
        /// Child BcoTransferencias where [bco_transferencias].[id_cta_car] point to this entity (FK_bco_transferencias_bco_cuentas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BcoTransferencia> BcoTransferencias_IdCtaCar { get; set; } // bco_transferencias.FK_bco_transferencias_bco_cuentas
        /// <summary>
        /// Child SIR_Sir120SolicitudCheque where [SIR_120_SOLICITUD_CHEQUES].[nIdDeudor] point to this entity (FK_SIR_120_SOLICITUD_CHEQUES_bco_cuentas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir120SolicitudCheque> SIR_Sir120SolicitudCheque { get; set; } // SIR_120_SOLICITUD_CHEQUES.FK_SIR_120_SOLICITUD_CHEQUES_bco_cuentas
        /// <summary>
        /// Child SIR_Sir239CuentasBanco where [SIR_239_CUENTAS_BANCOS].[nIdCtaBanco] point to this entity (FK_SIR_239_CUENTAS_BANCOS_bco_cuentas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir239CuentasBanco> SIR_Sir239CuentasBanco { get; set; } // SIR_239_CUENTAS_BANCOS.FK_SIR_239_CUENTAS_BANCOS_bco_cuentas

        // Foreign keys

        /// <summary>
        /// Parent BcoBanco pointed by [bco_cuentas].([IdBco]) (FK_bco_cuentas_bco_bancos)
        /// </summary>
        public virtual BcoBanco BcoBanco { get; set; } // FK_bco_cuentas_bco_bancos

        /// <summary>
        /// Parent BcoTipCta pointed by [bco_cuentas].([IdTipCta]) (FK_bco_cuentas_bco_tip_cta)
        /// </summary>
        public virtual BcoTipCta BcoTipCta { get; set; } // FK_bco_cuentas_bco_tip_cta

        public BcoCuenta()
        {
            IdUsr = 0;
            IdBco = 0;
            IdFmt1 = 0;
            IdMda = 0;
            IdTipCta = 0;
            Num = "";
            Clabe = "";
            Titular = "";
            Cargos = 0;
            Abonos = 0;
            Saldo = 0;
            NoSigChk = 1;
            Status = 1;
            SaldoConc = 0;
            IdConc = 0;
            IdCtaCtb = 0;
            Suc = "";
            Dir = "";
            LimCrd = 0;
            FondoFijo = 0;
            IdTipTrnDef = 0;
            LayoutIncEnc = false;
            IdEmp = 0;
            TipoDeuda = 0;
            LayoutIniFila = 0;
            IdTipTrnDep = 0;
            IdProv = 0;
            IdClas = 0;
            Bcosdo = 0;
            CExpLay = 0;
            IdRelTar = 0;
            CTerm = 0;
            Rfc = "";
            CParRel = 0;
            IdCtaAso = 0;
            IdRelDdc = 0;
            NumCliente = "";
            CPf = 0;
            CFlu = 0;
            BcoAuxes = new System.Collections.Generic.List<BcoAux>();
            BcoConcs = new System.Collections.Generic.List<BcoConc>();
            BcoDocs = new System.Collections.Generic.List<BcoDoc>();
            BcoTransferencias_IdCtaAbo = new System.Collections.Generic.List<BcoTransferencia>();
            BcoTransferencias_IdCtaCar = new System.Collections.Generic.List<BcoTransferencia>();
            SIR_Sir120SolicitudCheque = new System.Collections.Generic.List<SIR_Sir120SolicitudCheque>();
            SIR_Sir239CuentasBanco = new System.Collections.Generic.List<SIR_Sir239CuentasBanco>();
        }
    }

}
// </auto-generated>
