// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // bco_iva_det_ret_acu
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class BcoIvaDetRetAcuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BcoIvaDetRetAcu>
    {
        public BcoIvaDetRetAcuConfiguration()
            : this("dbo")
        {
        }

        public BcoIvaDetRetAcuConfiguration(string schema)
        {
            ToTable("bco_iva_det_ret_acu", schema);
            HasKey(x => x.IdIvaDetRetAcu);

            Property(x => x.IdIvaDetRetAcu).HasColumnName(@"id_iva_det_ret_acu").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdRcnIva).HasColumnName(@"id_rcn_iva").HasColumnType("int").IsRequired();
            Property(x => x.PtgIva).HasColumnName(@"ptg_iva").HasColumnType("float").IsRequired();
            Property(x => x.IvaAcred).HasColumnName(@"iva_acred").HasColumnType("float").IsRequired();
            Property(x => x.FecReg).HasColumnName(@"fec_reg").HasColumnType("datetime").IsRequired();
        }
    }

}
// </auto-generated>
