// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // bco_tip_trn
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class BcoTipTrn
    {
        [Required]
        [Display(Name = "Id tip trn")]
        public int IdTipTrn { get; set; } // id_tip_trn (Primary key)

        [MaxLength(40)]
        [StringLength(40)]
        [Display(Name = "Des")]
        public string Des { get; set; } // des (length: 40)

        ///<summary>
        /// 1=cargo 2=abono
        ///</summary>
        [Required]
        [Display(Name = "Tipo")]
        public byte Tipo { get; set; } // tipo

        ///<summary>
        /// 1=cheque 0=otros  2=Efectivo aplica para los cobros en punto de venta
        ///</summary>
        [Required]
        [Display(Name = "C chq")]
        public byte CChq { get; set; } // c_chq

        [Required]
        [Display(Name = "Status")]
        public byte Status { get; set; } // status

        ///<summary>
        /// 0=No requiere Conciliacion 1=Si requiere conciliacion
        ///</summary>
        [Required]
        [Display(Name = "C concil")]
        public byte CConcil { get; set; } // c_concil

        [Required]
        [Display(Name = "C caj")]
        public byte CCaj { get; set; } // c_caj

        [Required]
        [Display(Name = "Id tip trn cmp")]
        public int IdTipTrnCmp { get; set; } // id_tip_trn_cmp

        [Required]
        [Display(Name = "C efe")]
        public byte CEfe { get; set; } // c_efe

        [Required]
        [Display(Name = "C gas")]
        public byte CGas { get; set; } // c_gas

        [Required]
        [Display(Name = "C lay")]
        public int CLay { get; set; } // c_lay

        [Required]
        [Display(Name = "C cob mul")]
        public byte CCobMul { get; set; } // c_cob_mul

        [Required]
        [Display(Name = "C tar")]
        public byte CTar { get; set; } // c_tar

        [Required]
        [Display(Name = "Id tip met pag")]
        public int IdTipMetPag { get; set; } // id_tip_met_pag

        [Required]
        [Display(Name = "Id met pag fac")]
        public int IdMetPagFac { get; set; } // id_met_pag_fac

        // Reverse navigation

        /// <summary>
        /// Child BcoAuxes where [bco_aux].[id_tip_trn] point to this entity (FK_bco_aux_bco_tip_trn)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BcoAux> BcoAuxes { get; set; } // bco_aux.FK_bco_aux_bco_tip_trn
        /// <summary>
        /// Child BcoDocs where [bco_doc].[id_tip_trn] point to this entity (FK_bco_doc_bco_tip_trn)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BcoDoc> BcoDocs { get; set; } // bco_doc.FK_bco_doc_bco_tip_trn

        public BcoTipTrn()
        {
            IdTipTrn = 0;
            Des = "";
            Tipo = 0;
            CChq = 0;
            Status = 0;
            CConcil = 1;
            CCaj = 0;
            IdTipTrnCmp = 0;
            CEfe = 0;
            CGas = 0;
            CLay = 0;
            CCobMul = 0;
            CTar = 0;
            IdTipMetPag = 0;
            IdMetPagFac = 0;
            BcoAuxes = new System.Collections.Generic.List<BcoAux>();
            BcoDocs = new System.Collections.Generic.List<BcoDoc>();
        }
    }

}
// </auto-generated>
