// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // The table 'Carga_Agencias_LF' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // Carga_Agencias_LF
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CargaAgenciasLf
    {
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Archivo")]
        public string Archivo { get; set; } // archivo (length: 255)

        [Display(Name = "Cliente")]
        public int? Cliente { get; set; } // cliente

        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Referencia")]
        public string Referencia { get; set; } // referencia (length: 255)

        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Ruta")]
        public string Ruta { get; set; } // ruta (length: 255)

        [Display(Name = "Tipomov")]
        public int? Tipomov { get; set; } // tipomov

        [Display(Name = "Numero")]
        public int? Numero { get; set; } // numero

        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Serie")]
        public string Serie { get; set; } // serie (length: 255)

        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Folio")]
        public string Folio { get; set; } // folio (length: 255)

        [Display(Name = "Carga")]
        public int? Carga { get; set; } // carga

        [Display(Name = "Escomplementaria")]
        public int? Escomplementaria { get; set; } // escomplementaria

        public CargaAgenciasLf()
        {
            Carga = 0;
            Escomplementaria = 0;
        }
    }

}
// </auto-generated>
