// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // cat_compe
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CatCompeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CatCompe>
    {
        public CatCompeConfiguration()
            : this("dbo")
        {
        }

        public CatCompeConfiguration(string schema)
        {
            ToTable("cat_compe", schema);
            HasKey(x => new { x.IdCompe, x.IdExterno, x.NumPermiso, x.FecReg, x.Status });

            Property(x => x.IdCompe).HasColumnName(@"id_compe").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdExterno).HasColumnName(@"id_externo").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NumPermiso).HasColumnName(@"num_permiso").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(30).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Nombre).HasColumnName(@"nombre").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(150);
            Property(x => x.NombreCorto).HasColumnName(@"nombre_corto").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(150);
            Property(x => x.Categoria).HasColumnName(@"categoria").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Marca).HasColumnName(@"marca").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Direccion).HasColumnName(@"direccion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.IdPais).HasColumnName(@"id_pais").HasColumnType("int").IsOptional();
            Property(x => x.IdEdo).HasColumnName(@"id_edo").HasColumnType("int").IsOptional();
            Property(x => x.Ciudad).HasColumnName(@"ciudad").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.PaisGeo).HasColumnName(@"pais_geo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.EdoGeo).HasColumnName(@"edo_geo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.CiudadGeo).HasColumnName(@"ciudad_geo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(150);
            Property(x => x.Comentario).HasColumnName(@"comentario").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.CodPostal).HasColumnName(@"cod_postal").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Telefono).HasColumnName(@"telefono").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.EMail).HasColumnName(@"e_mail").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Clave).HasColumnName(@"clave").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.FecReg).HasColumnName(@"Fec_reg").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("tinyint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.MiSuc).HasColumnName(@"mi_suc").HasColumnType("tinyint").IsOptional();
            Property(x => x.CveNegocio).HasColumnName(@"cve_negocio").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.Idmcp).HasColumnName(@"idmcp").HasColumnType("int").IsOptional();
            Property(x => x.IdIcono).HasColumnName(@"id_icono").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
