// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // cat_dispositivos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CatDispositivoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CatDispositivo>
    {
        public CatDispositivoConfiguration()
            : this("dbo")
        {
        }

        public CatDispositivoConfiguration(string schema)
        {
            ToTable("cat_dispositivos", schema);
            HasKey(x => x.IdDispositivo);

            Property(x => x.IdDispositivo).HasColumnName(@"id_dispositivo").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdCliTabAr).HasColumnName(@"id_cli_tab_ar").HasColumnType("int").IsRequired();
            Property(x => x.IdCmp).HasColumnName(@"id_cmp").HasColumnType("int").IsRequired();
            Property(x => x.Uid).HasColumnName(@"uid").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Des).HasColumnName(@"des").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
            Property(x => x.TipoUsuario).HasColumnName(@"tipo_usuario").HasColumnType("int").IsRequired();
            Property(x => x.IdUsuAsignado).HasColumnName(@"id_usu_asignado").HasColumnType("int").IsRequired();
            Property(x => x.StatusUsuAsignado).HasColumnName(@"status_usu_asignado").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("int").IsRequired();
            Property(x => x.IdUsr).HasColumnName(@"id_usr").HasColumnType("int").IsRequired();
            Property(x => x.FecReg).HasColumnName(@"fec_reg").HasColumnType("datetime").IsRequired();
            Property(x => x.Modo).HasColumnName(@"modo").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
