// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // cat_impto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CatImpto
    {
        [Required]
        [Display(Name = "Id impto")]
        public int IdImpto { get; set; } // id_impto (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(40)]
        [StringLength(40)]
        [Display(Name = "Des")]
        public string Des { get; set; } // des (length: 40)

        [Required]
        [Display(Name = "Id usr")]
        public int IdUsr { get; set; } // id_usr

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec rec")]
        public System.DateTime FecRec { get; set; } // fec_rec

        [Required]
        [Display(Name = "Status")]
        public byte Status { get; set; } // status

        ///<summary>
        /// 0-Todos 1-Clientes 2-Proveedores
        ///</summary>
        [Required]
        [Display(Name = "Tipo")]
        public byte Tipo { get; set; } // tipo

        [Required]
        [Display(Name = "Id impto cmp")]
        public byte IdImptoCmp { get; set; } // id_impto_cmp

        [Required]
        [Display(Name = "C pag imp")]
        public byte CPagImp { get; set; } // c_pag_imp

        [Required]
        [Display(Name = "C zon frn")]
        public byte CZonFrn { get; set; } // c_zon_frn

        [Required]
        [Display(Name = "C iva imp")]
        public byte CIvaImp { get; set; } // c_iva_imp

        [Required(AllowEmptyStrings = true)]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Id otr sis")]
        public string IdOtrSis { get; set; } // id_otr_sis (length: 25)

        // Reverse navigation

        /// <summary>
        /// Child CatProes where [cat_pro].[id_impto] point to this entity (FK_cat_pro_cat_impto)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CatPro> CatProes { get; set; } // cat_pro.FK_cat_pro_cat_impto

        public CatImpto()
        {
            IdImpto = 0;
            Des = "";
            IdUsr = 0;
            Status = 0;
            Tipo = 0;
            IdImptoCmp = 0;
            CPagImp = 0;
            CZonFrn = 0;
            CIvaImp = 0;
            IdOtrSis = "";
            CatProes = new System.Collections.Generic.List<CatPro>();
        }
    }

}
// </auto-generated>
