// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // cat_tra_veh
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CatTraVehConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CatTraVeh>
    {
        public CatTraVehConfiguration()
            : this("dbo")
        {
        }

        public CatTraVehConfiguration(string schema)
        {
            ToTable("cat_tra_veh", schema);
            HasKey(x => x.IdVehiculo);

            Property(x => x.IdVehiculo).HasColumnName(@"id_vehiculo").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Codigo).HasColumnName(@"codigo").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(25);
            Property(x => x.Descripcion).HasColumnName(@"descripcion").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
            Property(x => x.IdTipoVehiculo).HasColumnName(@"id_tipo_vehiculo").HasColumnType("int").IsRequired();
            Property(x => x.SistemaMetrico).HasColumnName(@"sistema_metrico").HasColumnType("int").IsRequired();
            Property(x => x.DimensionesAlto).HasColumnName(@"dimensiones_alto").HasColumnType("float").IsRequired();
            Property(x => x.DimensionesAncho).HasColumnName(@"dimensiones_ancho").HasColumnType("float").IsRequired();
            Property(x => x.DimensionesLargo).HasColumnName(@"dimensiones_largo").HasColumnType("float").IsRequired();
            Property(x => x.DimensionesPeso).HasColumnName(@"dimensiones_peso").HasColumnType("float").IsRequired();
            Property(x => x.CapacidadCarga).HasColumnName(@"capacidad_carga").HasColumnType("float").IsRequired();
            Property(x => x.CapacidadVolumen).HasColumnName(@"capacidad_volumen").HasColumnType("float").IsRequired();
            Property(x => x.CombustibleConCarga).HasColumnName(@"combustible_con_carga").HasColumnType("float").IsRequired();
            Property(x => x.CombustibleSinCarga).HasColumnName(@"combustible_sin_carga").HasColumnType("float").IsRequired();
            Property(x => x.CombustibleCapacidadTanque).HasColumnName(@"combustible_capacidad_tanque").HasColumnType("float").IsRequired();
            Property(x => x.CombustibleTiempoCarga).HasColumnName(@"combustible_tiempo_carga").HasColumnType("int").IsRequired();
            Property(x => x.IdUsr).HasColumnName(@"id_usr").HasColumnType("int").IsRequired();
            Property(x => x.FecReg).HasColumnName(@"fec_reg").HasColumnType("datetime").IsRequired();
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("int").IsRequired();
            Property(x => x.IdPro).HasColumnName(@"id_pro").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
