// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // cat_ubi_cfg
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CatUbiCfg
    {
        [Required]
        [Display(Name = "Id ubi cfg")]
        public int IdUbiCfg { get; set; } // id_ubi_cfg (Primary key via unique index IX_cat_ubi_cfg_id_ubi_cfg_id_alm)

        [Required]
        [Display(Name = "Id alm")]
        public int IdAlm { get; set; } // id_alm (Primary key via unique index IX_cat_ubi_cfg_id_ubi_cfg_id_alm)

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec reg")]
        public System.DateTime FecReg { get; set; } // fec_reg

        [Required]
        [Display(Name = "Id usr")]
        public int IdUsr { get; set; } // id_usr

        [Required(AllowEmptyStrings = true)]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Nom")]
        public string Nom { get; set; } // nom (length: 60)

        [Required]
        [Display(Name = "C act")]
        public byte CAct { get; set; } // c_act

        [Required(AllowEmptyStrings = true)]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Caracter")]
        public string Caracter { get; set; } // caracter (length: 1)

        [Required]
        [Display(Name = "Peso")]
        public double Peso { get; set; } // peso

        [Required]
        [Display(Name = "Area")]
        public double Area { get; set; } // area

        [Required]
        [Display(Name = "Vol")]
        public double Vol { get; set; } // vol

        public CatUbiCfg()
        {
            IdUbiCfg = 0;
            IdAlm = 0;
            IdUsr = 0;
            Nom = "";
            CAct = 0;
            Caracter = "";
            Peso = 0;
            Area = 0;
            Vol = 0;
        }
    }

}
// </auto-generated>
