// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // cfg_version
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CfgVersion
    {

        ///<summary>
        /// 1.0.29
        ///</summary>
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Versi n")]
        public string Versión { get; set; } // Versión (length: 10)

        [Required]
        [Display(Name = "Mcp")]
        public byte Mcp { get; set; } // mcp (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Post")]
        public string Post { get; set; } // post (Primary key) (length: 2)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Erv version")]
        public string ErvVersion { get; set; } // erv_version (Primary key) (length: 10)

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec reg")]
        public System.DateTime FecReg { get; set; } // fec_reg (Primary key)

        [Required]
        [Display(Name = "Id ver")]
        public long IdVer { get; set; } // id_ver (Primary key)

        [Display(Name = "Id sis")]
        public long? IdSis { get; set; } // id_sis

        [Display(Name = "Hst")]
        public byte[] Hst { get; set; } // hst

        [Display(Name = "Ctrt lic")]
        public byte[] CtrtLic { get; set; } // ctrt_lic

        [Display(Name = "Ctrt imp")]
        public byte[] CtrtImp { get; set; } // ctrt_imp

        [Display(Name = "Ctrt mtto")]
        public byte[] CtrtMtto { get; set; } // ctrt_mtto

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Version pdv")]
        public string VersionPdv { get; set; } // version_pdv (Primary key) (length: 10)

        public CfgVersion()
        {
            Mcp = 0;
            Post = "";
            ErvVersion = "";
            IdSis = 0;
            VersionPdv = "0.0.0";
        }
    }

}
// </auto-generated>
