// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // The table 'cpt_atio' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // cpt_atio
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CptAtio
    {
        [Display(Name = "Id")]
        public int? Id { get; set; } // id

        [Display(Name = "Num cpt")]
        public int? NumCpt { get; set; } // num_cpt

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Des")]
        public string Des { get; set; } // des (length: 100)

        [Display(Name = "Tip")]
        public int? Tip { get; set; } // tip

        [Display(Name = "Id 1 g")]
        public int? Id1G { get; set; } // id_1G
    }

}
// </auto-generated>
