// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // sis_permisos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class crm_SisPermisoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<crm_SisPermiso>
    {
        public crm_SisPermisoConfiguration()
            : this("crm")
        {
        }

        public crm_SisPermisoConfiguration(string schema)
        {
            ToTable("sis_permisos", schema);
            HasKey(x => x.IdPerm);

            Property(x => x.IdPerm).HasColumnName(@"id_perm").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdRelEmpCto).HasColumnName(@"id_rel_emp_cto").HasColumnType("int").IsRequired();
            Property(x => x.IdPuesto).HasColumnName(@"id_puesto").HasColumnType("int").IsRequired();
            Property(x => x.IdPermAcc).HasColumnName(@"id_perm_acc").HasColumnType("int").IsRequired();
            Property(x => x.IdRec).HasColumnName(@"id_rec").HasColumnType("int").IsRequired();
            Property(x => x.Cond).HasColumnName(@"cond").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
        }
    }

}
// </auto-generated>
