// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // aux_cat_clas_gral_ins
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class crm_AuxCatClasGralIn
    {
        [Required]
        [Display(Name = "Id clas gral")]
        public int IdClasGral { get; set; } // id_clas_gral (Primary key)

        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Clave")]
        public string Clave { get; set; } // clave (length: 10)

        [MaxLength(40)]
        [StringLength(40)]
        [Display(Name = "Des")]
        public string Des { get; set; } // des (length: 40)

        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Cuenta")]
        public string Cuenta { get; set; } // cuenta (length: 20)

        [Display(Name = "Status")]
        public byte? Status { get; set; } // status

        [Required]
        [Display(Name = "Sistema")]
        public byte Sistema { get; set; } // sistema (Primary key)

        [Display(Name = "Tipoobj")]
        public int? Tipoobj { get; set; } // tipoobj

        [Required]
        [Display(Name = "C mul")]
        public byte CMul { get; set; } // c_mul (Primary key)

        [Required]
        [Display(Name = "C ctb")]
        public byte CCtb { get; set; } // c_ctb (Primary key)

        [Required]
        [Display(Name = "B repetido")]
        public byte BRepetido { get; set; } // b_repetido (Primary key)

        public crm_AuxCatClasGralIn()
        {
            Sistema = 0;
            CMul = 0;
            CCtb = 0;
            BRepetido = 0;
        }
    }

}
// </auto-generated>
