// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // eve_even
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class crm_EveEvenConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<crm_EveEven>
    {
        public crm_EveEvenConfiguration()
            : this("crm")
        {
        }

        public crm_EveEvenConfiguration(string schema)
        {
            ToTable("eve_even", schema);
            HasKey(x => x.IdEveEven);

            Property(x => x.IdEveEven).HasColumnName(@"id_eve_even").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdTipEve).HasColumnName(@"id_tip_eve").HasColumnType("int").IsRequired();
            Property(x => x.IdEve).HasColumnName(@"id_eve").HasColumnType("int").IsRequired();
            Property(x => x.IdPred).HasColumnName(@"id_pred").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
