// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // sis_rel_obj_arch
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class crm_SisRelObjArch
    {
        [Required]
        [Display(Name = "Id rel obj arch")]
        public int IdRelObjArch { get; set; } // id_rel_obj_arch (Primary key)

        [Required]
        [Display(Name = "Id obj")]
        public int IdObj { get; set; } // id_obj

        [Required]
        [Display(Name = "Id tip obj")]
        public int IdTipObj { get; set; } // id_tip_obj

        [Required]
        [Display(Name = "Id arch")]
        public int IdArch { get; set; } // id_arch

        [Required]
        [Display(Name = "Status")]
        public int Status { get; set; } // status

        [Required]
        [Display(Name = "Id tip doc")]
        public int IdTipDoc { get; set; } // id_tip_doc

        [Required]
        [Display(Name = "Id tbl")]
        public int IdTbl { get; set; } // id_tbl

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Serie")]
        public string Serie { get; set; } // serie (length: 20)

        [Required]
        [Display(Name = "Id prov")]
        public long IdProv { get; set; } // id_prov

        [Required]
        [Display(Name = "Id cli fa da")]
        public long IdCliFaDa { get; set; } // id_cli_fa_da

        [MaxLength(40)]
        [StringLength(40)]
        [Display(Name = "No fact")]
        public string NoFact { get; set; } // no_fact (length: 40)

        [Required]
        [Display(Name = "Env a")]
        public byte EnvA { get; set; } // env_a

        [Required]
        [Display(Name = "Id rel cot")]
        public int IdRelCot { get; set; } // id_rel_cot

        [Required]
        [Display(Name = "Is upd from 1 g")]
        public bool IsUpdFrom1G { get; set; } // is_upd_from_1g

        [Required]
        [Display(Name = "Id part")]
        public int IdPart { get; set; } // id_part

        [Required]
        [Display(Name = "Id obj det")]
        public int IdObjDet { get; set; } // id_obj_det

        // Reverse navigation

        /// <summary>
        /// Child TblInfoRelObjArches where [tbl_info_rel_obj_arch].[id_rel_obj_arch] point to this entity (FK_tbl_info_rel_obj_arch_id_rel_obj_arch)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TblInfoRelObjArch> TblInfoRelObjArches { get; set; } // tbl_info_rel_obj_arch.FK_tbl_info_rel_obj_arch_id_rel_obj_arch

        public crm_SisRelObjArch()
        {
            IdObj = 0;
            IdTipObj = 0;
            IdArch = 0;
            IdTipDoc = 0;
            IdTbl = 0;
            Serie = "";
            IdProv = 0;
            IdCliFaDa = 0;
            NoFact = "";
            EnvA = 0;
            IdRelCot = 0;
            IsUpdFrom1G = false;
            IdPart = 0;
            IdObjDet = 0;
            TblInfoRelObjArches = new System.Collections.Generic.List<TblInfoRelObjArch>();
        }
    }

}
// </auto-generated>
