// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // FramentedTableList_jg
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class FramentedTableListJg
    {
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Table name")]
        public string TableName { get; set; } // TableName (length: 128)

        [Display(Name = "Avg fragmentation in percent")]
        public double? AvgFragmentationInPercent { get; set; } // avg_fragmentation_in_percent

        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Index name")]
        public string IndexName { get; set; } // IndexName (length: 128)

        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Schema name")]
        public string SchemaName { get; set; } // SchemaName (length: 128)

        [Required]
        [Display(Name = "Is processed")]
        public int IsProcessed { get; set; } // IsProcessed (Primary key)

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec process")]
        public System.DateTime FecProcess { get; set; } // Fec_process (Primary key)

        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Pc")]
        public string Pc { get; set; } // pc (length: 128)
    }

}
// </auto-generated>
