// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // imp_fac_det
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ImpFacDetConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ImpFacDet>
    {
        public ImpFacDetConfiguration()
            : this("dbo")
        {
        }

        public ImpFacDetConfiguration(string schema)
        {
            ToTable("imp_fac_det", schema);
            HasKey(x => x.ImpIdFacDet);

            Property(x => x.ImpIdFacDet).HasColumnName(@"imp_id_fac_det").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ImpIdFacEnc).HasColumnName(@"imp_id_fac_enc").HasColumnType("int").IsRequired();
            Property(x => x.ImpIdPro).HasColumnName(@"imp_id_pro").HasColumnType("int").IsRequired();
            Property(x => x.ImpDescripcion).HasColumnName(@"imp_descripcion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ImpCant).HasColumnName(@"imp_cant").HasColumnType("float").IsRequired();
            Property(x => x.ImpIdUdm).HasColumnName(@"imp_id_udm").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ImpUdm).HasColumnName(@"imp_udm").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ImpIdOtrSisPro).HasColumnName(@"imp_id_otr_sis_pro").HasColumnType("int").IsRequired();
            Property(x => x.ImpCveSat).HasColumnName(@"imp_cve_sat").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.ImpTotal).HasColumnName(@"imp_total").HasColumnType("float").IsRequired();
            Property(x => x.ImpSub).HasColumnName(@"imp_sub").HasColumnType("float").IsRequired();
            Property(x => x.ImpImptos).HasColumnName(@"imp_imptos").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioOrig).HasColumnName(@"imp_precio_orig").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioPubSimptos).HasColumnName(@"imp_precio_pub_simptos").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioSimptos).HasColumnName(@"imp_precio_simptos").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioCimptos).HasColumnName(@"imp_precio_cimptos").HasColumnType("float").IsRequired();
            Property(x => x.ImpIdProLis).HasColumnName(@"imp_id_pro_lis").HasColumnType("int").IsRequired();
            Property(x => x.ImpIdLisPre).HasColumnName(@"imp_id_lis_pre").HasColumnType("int").IsRequired();
            Property(x => x.ImpIdSisLisPre).HasColumnName(@"imp_id_sis_lis_pre").HasColumnType("int").IsRequired();
            Property(x => x.ImpImporteCimptos).HasColumnName(@"imp_importe_cimptos").HasColumnType("float").IsRequired();
            Property(x => x.ImpImporteSimptos).HasColumnName(@"imp_importe_simptos").HasColumnType("float").IsRequired();
            Property(x => x.ImpMontosImptos).HasColumnName(@"imp_montos_imptos").HasColumnType("float").IsRequired();
            Property(x => x.ImpIdImpto).HasColumnName(@"imp_id_impto").HasColumnType("int").IsRequired();
            Property(x => x.ImpCosto).HasColumnName(@"imp_costo").HasColumnType("float").IsRequired();
            Property(x => x.ImpCostoTotal).HasColumnName(@"imp_costo_total").HasColumnType("float").IsRequired();
            Property(x => x.ImpMontoDescto).HasColumnName(@"imp_monto_descto").HasColumnType("float").IsRequired();
            Property(x => x.ImpIdAlmac).HasColumnName(@"imp_id_almac").HasColumnType("int").IsRequired();
            Property(x => x.ImpIdSuc).HasColumnName(@"imp_id_suc").HasColumnType("int").IsRequired();
            Property(x => x.ImpIdMda).HasColumnName(@"imp_id_mda").HasColumnType("int").IsRequired();
            Property(x => x.ImpTc).HasColumnName(@"imp_tc").HasColumnType("float").IsRequired();
            Property(x => x.ImpOper).HasColumnName(@"imp_oper").HasColumnType("tinyint").IsRequired();
            Property(x => x.ImpTotalBse).HasColumnName(@"imp_total_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpImptosBse).HasColumnName(@"imp_imptos_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpSubBse).HasColumnName(@"imp_sub_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioOrigBse).HasColumnName(@"imp_precio_orig_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioPubBse).HasColumnName(@"imp_precio_pub_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioPubSimptosBse).HasColumnName(@"imp_precio_pub_simptos_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioCimptosBse).HasColumnName(@"imp_precio_cimptos_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpPrecioSimptosBse).HasColumnName(@"imp_precio_simptos_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpImporteCimptosBse).HasColumnName(@"imp_importe_cimptos_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpImporteSimptosBse).HasColumnName(@"imp_importe_simptos_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpMontoImptosBse).HasColumnName(@"imp_monto_imptos_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpMontoDesctoBse).HasColumnName(@"imp_monto_descto_bse").HasColumnType("float").IsRequired();
            Property(x => x.ImpDctoPtg).HasColumnName(@"imp_dcto_ptg").HasColumnType("float").IsRequired();
            Property(x => x.ImpDctoMto).HasColumnName(@"imp_dcto_mto").HasColumnType("float").IsRequired();
            Property(x => x.ImpTipCom).HasColumnName(@"imp_tip_com").HasColumnType("tinyint").IsRequired();
            Property(x => x.ImpPtgCom).HasColumnName(@"imp_ptg_com").HasColumnType("float").IsRequired();
            Property(x => x.ImpMtoCom).HasColumnName(@"imp_mto_com").HasColumnType("float").IsRequired();
            Property(x => x.ImpTipHon).HasColumnName(@"imp_tip_hon").HasColumnType("int").IsRequired();
            Property(x => x.ImpPtgHon).HasColumnName(@"imp_ptg_hon").HasColumnType("float").IsRequired();
            Property(x => x.ImpIdCodSrv).HasColumnName(@"imp_id_cod_srv").HasColumnType("int").IsRequired();
            Property(x => x.ImpCodSrv).HasColumnName(@"imp_cod_srv").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ImpIdCenCto).HasColumnName(@"imp_id_cen_cto").HasColumnType("int").IsRequired();
            Property(x => x.ImpCenCto).HasColumnName(@"imp_cen_cto").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ImpIdRef).HasColumnName(@"imp_id_ref").HasColumnType("int").IsRequired();
            Property(x => x.ImpRef).HasColumnName(@"imp_ref").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ImpIdRefExt).HasColumnName(@"imp_id_ref_ext").HasColumnType("nvarchar").IsRequired().HasMaxLength(64);
            Property(x => x.ImpRefExt).HasColumnName(@"imp_ref_ext").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(64);
            Property(x => x.ImpCmt).HasColumnName(@"imp_cmt").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ImpStatusDetImp).HasColumnName(@"imp_status_det_imp").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
