// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // pro_rpt_enc
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ProRptEncConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProRptEnc>
    {
        public ProRptEncConfiguration()
            : this("dbo")
        {
        }

        public ProRptEncConfiguration(string schema)
        {
            ToTable("pro_rpt_enc", schema);
            HasKey(x => x.IdRptPro);

            Property(x => x.IdRptPro).HasColumnName(@"id_rpt_pro").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdUsr).HasColumnName(@"id_usr").HasColumnType("int").IsRequired();
            Property(x => x.IdNota).HasColumnName(@"id_nota").HasColumnType("int").IsRequired();
            Property(x => x.IdOrden).HasColumnName(@"id_orden").HasColumnType("int").IsRequired();
            Property(x => x.IdAlmac).HasColumnName(@"id_almac").HasColumnType("int").IsRequired();
            Property(x => x.IdPro).HasColumnName(@"id_pro").HasColumnType("int").IsRequired();
            Property(x => x.IdTipDoc).HasColumnName(@"id_tip_doc").HasColumnType("int").IsRequired();
            Property(x => x.NumDoc).HasColumnName(@"num_doc").HasColumnType("int").IsRequired();
            Property(x => x.NumOrd).HasColumnName(@"num_ord").HasColumnType("int").IsRequired();
            Property(x => x.Referencia).HasColumnName(@"referencia").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(25);
            Property(x => x.Fecha).HasColumnName(@"fecha").HasColumnType("datetime").IsRequired();
            Property(x => x.Ordenada).HasColumnName(@"ordenada").HasColumnType("float").IsRequired();
            Property(x => x.Pendiente).HasColumnName(@"pendiente").HasColumnType("float").IsRequired();
            Property(x => x.CostoOrig).HasColumnName(@"costo_orig").HasColumnType("float").IsRequired();
            Property(x => x.PrecioOrig).HasColumnName(@"precio_orig").HasColumnType("float").IsRequired();
            Property(x => x.Reportada).HasColumnName(@"reportada").HasColumnType("float").IsRequired();
            Property(x => x.CostoAct).HasColumnName(@"costo_act").HasColumnType("float").IsRequired();
            Property(x => x.CCerrar).HasColumnName(@"c_cerrar").HasColumnType("tinyint").IsRequired();
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("tinyint").IsRequired();
            Property(x => x.ConsRpt).HasColumnName(@"cons_rpt").HasColumnType("int").IsRequired();
            Property(x => x.CostoPromAct).HasColumnName(@"costo_prom_act").HasColumnType("float").IsRequired();
            Property(x => x.IdComSerLot).HasColumnName(@"id_com_ser_lot").HasColumnType("int").IsRequired();
            Property(x => x.IdKardex).HasColumnName(@"id_kardex").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.CatDocto).WithMany(b => b.ProRptEncs).HasForeignKey(c => c.IdTipDoc).WillCascadeOnDelete(false); // FK_pro_rpt_enc_cat_doctos
            HasRequired(a => a.CatPro).WithMany(b => b.ProRptEncs).HasForeignKey(c => c.IdPro).WillCascadeOnDelete(false); // FK_pro_rpt_enc_cat_pro
            HasRequired(a => a.CatUsr).WithMany(b => b.ProRptEncs).HasForeignKey(c => c.IdUsr).WillCascadeOnDelete(false); // FK_pro_rpt_enc_cat_usr
        }
    }

}
// </auto-generated>
