// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // reg_nom_cfdi_enc
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class RegNomCfdiEnc
    {
        [Required]
        [Display(Name = "Id reg nom cfdi")]
        public int IdRegNomCfdi { get; set; } // id_reg_nom_cfdi (Primary key)

        [Required]
        [Display(Name = "Id reg nom")]
        public int IdRegNom { get; set; } // id_reg_nom

        [Required]
        [Display(Name = "Id emp")]
        public int IdEmp { get; set; } // id_emp

        [Required]
        [Display(Name = "Numero")]
        public int Numero { get; set; } // numero

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha")]
        public System.DateTime Fecha { get; set; } // fecha

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Serie")]
        public string Serie { get; set; } // serie (length: 10)

        [Required]
        [Display(Name = "Monto")]
        public double Monto { get; set; } // monto

        [Required]
        [Display(Name = "Status")]
        public int Status { get; set; } // status

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Registro patronal")]
        public string RegistroPatronal { get; set; } // RegistroPatronal (length: 20)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Num empleado")]
        public string NumEmpleado { get; set; } // num_empleado (length: 15)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Curp")]
        public string Curp { get; set; } // curp (length: 20)

        [Required]
        [Display(Name = "Tip regimen")]
        public int TipRegimen { get; set; } // tip_regimen

        [Required(AllowEmptyStrings = true)]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Nss")]
        public string Nss { get; set; } // nss (length: 15)

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fec pago")]
        public System.DateTime FecPago { get; set; } // fec_pago

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fec ini pago")]
        public System.DateTime FecIniPago { get; set; } // fec_ini_pago

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fec fin pago")]
        public System.DateTime FecFinPago { get; set; } // fec_fin_pago

        [Required]
        [Display(Name = "Num dias pag")]
        public double NumDiasPag { get; set; } // num_dias_pag

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Departamento")]
        public string Departamento { get; set; } // departamento (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Clabe")]
        public string Clabe { get; set; } // clabe (length: 20)

        [Required]
        [Display(Name = "Banco")]
        public int Banco { get; set; } // banco

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fec ini rel lab")]
        public System.DateTime FecIniRelLab { get; set; } // fec_ini_rel_lab

        [Required]
        [Display(Name = "Antiguedad")]
        public int Antiguedad { get; set; } // antiguedad

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Puesto")]
        public string Puesto { get; set; } // puesto (length: 50)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Tipo contrato")]
        public string TipoContrato { get; set; } // tipo_contrato (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Tipo jornada")]
        public string TipoJornada { get; set; } // tipo_jornada (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Periodicidad pago")]
        public string PeriodicidadPago { get; set; } // periodicidad_pago (length: 100)

        [Required]
        [Display(Name = "Sal base cot apor")]
        public double SalBaseCotApor { get; set; } // sal_base_cot_apor

        [Required]
        [Display(Name = "Riesgo puesto")]
        public int RiesgoPuesto { get; set; } // riesgo_puesto

        [Required]
        [Display(Name = "Sal diario integrado")]
        public double SalDiarioIntegrado { get; set; } // sal_diario_integrado

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Concepto")]
        public string Concepto { get; set; } // concepto

        [Required]
        [Display(Name = "Sindicalizado")]
        public int Sindicalizado { get; set; } // sindicalizado

        [Required]
        [Display(Name = "Ju tot exh")]
        public double JuTotExh { get; set; } // ju_tot_exh

        [Required]
        [Display(Name = "Ju tot parc")]
        public double JuTotParc { get; set; } // ju_tot_parc

        [Required]
        [Display(Name = "Ju mto dia")]
        public double JuMtoDia { get; set; } // ju_mto_dia

        [Required]
        [Display(Name = "Ju ing acu")]
        public double JuIngAcu { get; set; } // ju_ing_acu

        [Required]
        [Display(Name = "Ju ing no acu")]
        public double JuIngNoAcu { get; set; } // ju_ing_no_acu

        [Required]
        [Display(Name = "Se tot pag")]
        public double SeTotPag { get; set; } // se_tot_pag

        [Required]
        [Display(Name = "Se num anios")]
        public double SeNumAnios { get; set; } // se_num_anios

        [Required]
        [Display(Name = "Se ult sueldo")]
        public double SeUltSueldo { get; set; } // se_ult_sueldo

        [Required]
        [Display(Name = "Se ing acu")]
        public double SeIngAcu { get; set; } // se_ing_acu

        [Required]
        [Display(Name = "Se ing no acu")]
        public double SeIngNoAcu { get; set; } // se_ing_no_acu

        [Required]
        [Display(Name = "Subs cau")]
        public double SubsCau { get; set; } // subs_cau

        [Required]
        [Display(Name = "Com sdo fav")]
        public double ComSdoFav { get; set; } // com_sdo_fav

        [Required]
        [Display(Name = "Com anio")]
        public int ComAnio { get; set; } // com_anio

        [Required]
        [Display(Name = "Com rem salfav")]
        public double ComRemSalfav { get; set; } // com_rem_salfav

        [Required(AllowEmptyStrings = true)]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Tipo nomina")]
        public string TipoNomina { get; set; } // tipo_nomina (length: 15)

        [Required]
        [Display(Name = "Tipo recibo")]
        public int TipoRecibo { get; set; } // tipo_recibo

        [Required]
        [Display(Name = "Totalotrosp")]
        public int Totalotrosp { get; set; } // totalotrosp

        [Required]
        [Display(Name = "Totalsueldos")]
        public int Totalsueldos { get; set; } // totalsueldos

        [Required]
        [Display(Name = "Totalsepindem")]
        public int Totalsepindem { get; set; } // totalsepindem

        [Required]
        [Display(Name = "Totaljubpenret")]
        public int Totaljubpenret { get; set; } // totaljubpenret

        [Required]
        [Display(Name = "Total otrasded")]
        public int TotalOtrasded { get; set; } // total_otrasded

        [Required]
        [Display(Name = "Total isr")]
        public int TotalIsr { get; set; } // total_isr

        [Required(AllowEmptyStrings = true)]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Tip sat")]
        public string TipSat { get; set; } // tip_sat (length: 3)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Display(Name = "Reg bit")]
        public string RegBit { get; set; } // reg_bit (length: 4000)

        public RegNomCfdiEnc()
        {
            IdRegNom = 0;
            IdEmp = 0;
            Numero = 0;
            Serie = "";
            Monto = 0;
            Status = 0;
            RegistroPatronal = "";
            NumEmpleado = "";
            Curp = "";
            TipRegimen = 0;
            Nss = "";
            NumDiasPag = 0;
            Departamento = "";
            Clabe = "";
            Banco = 0;
            Antiguedad = 0;
            Puesto = "";
            TipoContrato = "";
            TipoJornada = "";
            PeriodicidadPago = "";
            SalBaseCotApor = 0;
            RiesgoPuesto = 0;
            SalDiarioIntegrado = 0;
            Concepto = "";
            Sindicalizado = 0;
            TipoNomina = "";
            TipoRecibo = 0;
            Totalotrosp = 0;
            Totalsueldos = 0;
            Totalsepindem = 0;
            Totaljubpenret = 0;
            TotalOtrasded = 0;
            TotalIsr = 0;
            TipSat = "000";
            RegBit = "";
        }
    }

}
// </auto-generated>
