// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // rh_emp_per
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class RhEmpPerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RhEmpPer>
    {
        public RhEmpPerConfiguration()
            : this("dbo")
        {
        }

        public RhEmpPerConfiguration(string schema)
        {
            ToTable("rh_emp_per", schema);
            HasKey(x => x.IdPer);

            Property(x => x.IdPer).HasColumnName(@"id_per").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NoEmp).HasColumnName(@"no_emp").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
