// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_353_FRACCIONES_AMERICANAS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir353FraccionesAmericana
    {
        [Required]
        [Display(Name = "N ID fraccion ame 353")]
        public int NIdFraccionAme353 { get; set; } // nIdFraccionAme353 (Primary key)

        [Required]
        [Display(Name = "N ID parte 99")]
        public int NIdParte99 { get; set; } // nIdParte99

        [Display(Name = "N ID codigo exportacion 334")]
        public int? NIdCodigoExportacion334 { get; set; } // nIdCodigoExportacion334

        [Display(Name = "N ID primera um 333")]
        public int? NIdPrimeraUm333 { get; set; } // nIdPrimeraUM333

        [Display(Name = "N ID segunda um 33")]
        public int? NIdSegundaUm33 { get; set; } // nIdSegundaUM33

        [Display(Name = "N ID tipo licencia 335")]
        public int? NIdTipoLicencia335 { get; set; } // nIdTipoLicencia335

        [MaxLength(12)]
        [StringLength(12)]
        [Display(Name = "S numero licencia")]
        public string SNumeroLicencia { get; set; } // sNumeroLicencia (length: 12)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "S fraccion ame")]
        public string SFraccionAme { get; set; } // sFraccionAme (length: 10)

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "S descripcion")]
        public string SDescripcion { get; set; } // sDescripcion

        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "S eccn")]
        public string SEccn { get; set; } // sECCN (length: 5)

        [Required]
        [Display(Name = "N origen")]
        public byte NOrigen { get; set; } // nOrigen

        [Display(Name = "N ID ddtcn um exencion 332")]
        public int? NIdDdtcNumExencion332 { get; set; } // nIdDDTCNumExencion332

        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "S ddtcn um registro")]
        public string SDdtcNumRegistro { get; set; } // sDDTCNumRegistro (length: 6)

        [Required]
        [Display(Name = "N ddtce quipo militar")]
        public byte NDdtcEquipoMilitar { get; set; } // nDDTCEquipoMilitar

        [Required]
        [Display(Name = "N ddtcc ertificacion")]
        public byte NDdtcCertificacion { get; set; } // nDDTCCertificacion

        [Display(Name = "N ID ddtcc ategoria usml 331")]
        public int? NIdDdtcCategoriaUsml331 { get; set; } // nIdDDTCCategoriaUSML331

        [Display(Name = "N ID ddtcu nidad medida 330")]
        public int? NIdDdtcUnidadMedida330 { get; set; } // nIdDDTCUnidadMedida330

        [Required]
        [Display(Name = "N tipo fraccion")]
        public byte NTipoFraccion { get; set; } // nTipoFraccion

        // Foreign keys

        /// <summary>
        /// Parent SIR_Sir330SedDdtcUnitsMeasure pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdDdtcUnidadMedida330]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_330_SED_DDTC_UNITS_MEASURE)
        /// </summary>
        public virtual SIR_Sir330SedDdtcUnitsMeasure SIR_Sir330SedDdtcUnitsMeasure { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_330_SED_DDTC_UNITS_MEASURE

        /// <summary>
        /// Parent SIR_Sir331SedDdtcCategoRy pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdDdtcCategoriaUsml331]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_331_SED_DDTC_CATEGORIES)
        /// </summary>
        public virtual SIR_Sir331SedDdtcCategoRy SIR_Sir331SedDdtcCategoRy { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_331_SED_DDTC_CATEGORIES

        /// <summary>
        /// Parent SIR_Sir332SedDdtcExemption pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdDdtcNumExencion332]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_332_SED_DDTC_EXEMPTIONS)
        /// </summary>
        public virtual SIR_Sir332SedDdtcExemption SIR_Sir332SedDdtcExemption { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_332_SED_DDTC_EXEMPTIONS

        /// <summary>
        /// Parent SIR_Sir333SedUnitsMeasure pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdPrimeraUm333]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_333_SED_UNITS_MEASURE_sPrimeraUM333)
        /// </summary>
        public virtual SIR_Sir333SedUnitsMeasure SIR_Sir333SedUnitsMeasure_NIdPrimeraUm333 { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_333_SED_UNITS_MEASURE_sPrimeraUM333

        /// <summary>
        /// Parent SIR_Sir333SedUnitsMeasure pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdSegundaUm33]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_333_SED_UNITS_MEASURE_sSegundaUM33)
        /// </summary>
        public virtual SIR_Sir333SedUnitsMeasure SIR_Sir333SedUnitsMeasure_NIdSegundaUm33 { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_333_SED_UNITS_MEASURE_sSegundaUM33

        /// <summary>
        /// Parent SIR_Sir334SedExportInformation pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdCodigoExportacion334]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_334_SED_EXPORT_INFORMATION)
        /// </summary>
        public virtual SIR_Sir334SedExportInformation SIR_Sir334SedExportInformation { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_334_SED_EXPORT_INFORMATION

        /// <summary>
        /// Parent SIR_Sir335SedLicense pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdTipoLicencia335]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_335_SED_LICENSES)
        /// </summary>
        public virtual SIR_Sir335SedLicense SIR_Sir335SedLicense { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_335_SED_LICENSES

        /// <summary>
        /// Parent SIR_Sir99Parte pointed by [SIR_353_FRACCIONES_AMERICANAS].([NIdParte99]) (FK_SIR_353_FRACCIONES_AMERICANAS_SIR_99_PARTES)
        /// </summary>
        public virtual SIR_Sir99Parte SIR_Sir99Parte { get; set; } // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_99_PARTES
    }

}
// </auto-generated>
