// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_180_PED_FORMAS_PAGO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir180PedFormasPagoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir180PedFormasPago>
    {
        public SIR_Sir180PedFormasPagoConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir180PedFormasPagoConfiguration(string schema)
        {
            ToTable("SIR_180_PED_FORMAS_PAGO", schema);
            HasKey(x => x.NIdPedForm180);

            Property(x => x.NIdPedForm180).HasColumnName(@"nIdPedForm180").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SInstitucionEmisora).HasColumnName(@"sInstitucionEmisora").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(300);
            Property(x => x.SNumeroDocumento).HasColumnName(@"sNumeroDocumento").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(40);
            Property(x => x.DFecha).HasColumnName(@"dFecha").HasColumnType("smalldatetime").IsOptional();
            Property(x => x.NImporteTotal).HasColumnName(@"nImporteTotal").HasColumnType("decimal").IsOptional().HasPrecision(14,2);
            Property(x => x.NSaldoDisponible).HasColumnName(@"nSaldoDisponible").HasColumnType("decimal").IsOptional().HasPrecision(14,2);
            Property(x => x.NImportePagar).HasColumnName(@"nImportePagar").HasColumnType("decimal").IsOptional().HasPrecision(14,2);
            Property(x => x.DFechaEdicion).HasColumnName(@"dFechaEdicion").HasColumnType("datetime").IsRequired();
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsRequired();
            Property(x => x.NIdImpPed185).HasColumnName(@"nIdImpPed185").HasColumnType("int").IsRequired();
            Property(x => x.SHNomImpuesto).HasColumnName(@"sHNomImpuesto").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.NIdFormaPago32).HasColumnName(@"nIdFormaPago32").HasColumnType("int").IsOptional();
            Property(x => x.NHClave).HasColumnName(@"nHClave").HasColumnType("tinyint").IsOptional();
            Property(x => x.SHDescripcion).HasColumnName(@"sHDescripcion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(55);
            Property(x => x.NIdPedimento149).HasColumnName(@"nIdPedimento149").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.SIR_Sir149Pedimento).WithMany(b => b.SIR_Sir180PedFormasPago).HasForeignKey(c => c.NIdPedimento149).WillCascadeOnDelete(false); // FK_SIR_180_PED_FORMAS_PAGO_SIR_149_PEDIMENTO
            HasOptional(a => a.SIR_Sir32FormasPago).WithMany(b => b.SIR_Sir180PedFormasPago).HasForeignKey(c => c.NIdFormaPago32).WillCascadeOnDelete(false); // FK_SIR_180_PED_FORMAS_PAGO_SIR_32_FORMAS_PAGO
            HasRequired(a => a.CatUsr).WithMany(b => b.SIR_Sir180PedFormasPago).HasForeignKey(c => c.NIdUsuarioEd).WillCascadeOnDelete(false); // FK_SIR_180_PED_FORMAS_PAGO_cat_usr
        }
    }

}
// </auto-generated>
