// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_124_ANTICIPOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir124AnticiposConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir124Anticipos>
    {
        public SIR_Sir124AnticiposConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir124AnticiposConfiguration(string schema)
        {
            ToTable("SIR_124_ANTICIPOS", schema);
            HasKey(x => x.NIdAnticipo124);

            Property(x => x.NIdAnticipo124).HasColumnName(@"nIdAnticipo124").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NFolio).HasColumnName(@"nFolio").HasColumnType("int").IsRequired();
            Property(x => x.NIdCotizacion123).HasColumnName(@"nIdCotizacion123").HasColumnType("int").IsOptional();
            Property(x => x.NIdReferencia60).HasColumnName(@"nIdReferencia60").HasColumnType("int").IsRequired();
            Property(x => x.NSolicitadoPor).HasColumnName(@"nSolicitadoPor").HasColumnType("int").IsOptional();
            Property(x => x.DFechaSolicitud).HasColumnName(@"dFechaSolicitud").HasColumnType("smalldatetime").IsRequired();
            Property(x => x.NIdMoneda).HasColumnName(@"nIdMoneda").HasColumnType("int").IsOptional();
            Property(x => x.NImporte).HasColumnName(@"nImporte").HasColumnType("decimal").IsRequired().HasPrecision(12,3);
            Property(x => x.NStatus).HasColumnName(@"nStatus").HasColumnType("tinyint").IsRequired();
            Property(x => x.DFechaAutorizacion).HasColumnName(@"dFechaAutorizacion").HasColumnType("smalldatetime").IsOptional();
            Property(x => x.DFechaEdicion).HasColumnName(@"dFechaEdicion").HasColumnType("datetime").IsRequired();
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsRequired();
            Property(x => x.NIdSucPatAdu71).HasColumnName(@"nIdSucPatAdu71").HasColumnType("int").IsOptional();
            Property(x => x.NIdCompMul314).HasColumnName(@"nIdCompMul314").HasColumnType("int").IsOptional();
            Property(x => x.SPedido).HasColumnName(@"sPedido").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SModelo).HasColumnName(@"sModelo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SSerie).HasColumnName(@"sSerie").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.NImpuestos).HasColumnName(@"nImpuestos").HasColumnType("decimal").IsOptional().HasPrecision(12,3);
            Property(x => x.NGastos).HasColumnName(@"nGastos").HasColumnType("decimal").IsOptional().HasPrecision(12,3);
            Property(x => x.NIngresos).HasColumnName(@"nIngresos").HasColumnType("decimal").IsOptional().HasPrecision(12,3);
            Property(x => x.NTotal).HasColumnName(@"nTotal").HasColumnType("decimal").IsRequired().HasPrecision(12,3);
            Property(x => x.NComplementarios).HasColumnName(@"nComplementarios").HasColumnType("decimal").IsOptional().HasPrecision(12,3);
            Property(x => x.NSolicitadoPor01).HasColumnName(@"nSolicitadoPor01").HasColumnType("int").IsOptional();
            Property(x => x.NIdMoneda03).HasColumnName(@"nIdMoneda03").HasColumnType("int").IsOptional();
            Property(x => x.SIdForaneo).HasColumnName(@"sIdForaneo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);

            // Foreign keys
            HasOptional(a => a.Admin_Admina01Usuario).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NSolicitadoPor01).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_ADMINA_01_USUARIOS
            HasOptional(a => a.Admin_Adminc03Moneda).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NIdMoneda03).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_ADMINC_03_MONEDAS
            HasOptional(a => a.MonMoneda).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NIdMoneda).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_mon_monedas
            HasOptional(a => a.SIR_Sir123Cotizacione).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NIdCotizacion123).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_SIR_123_COTIZACIONES
            HasOptional(a => a.SIR_Sir314CotizacionMultiple).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NIdCompMul314).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_SIR_314_COTIZACION_MULTIPLE
            HasOptional(a => a.SIR_Sir71SucursalPatenteAduana).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NIdSucPatAdu71).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_SIR_71_SUCURSAL_PATENTE_ADUANA
            HasRequired(a => a.CatUsr).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NIdUsuarioEd).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_cat_usr_ed
            HasRequired(a => a.SIR_Sir60Referencia).WithMany(b => b.SIR_Sir124Anticipos).HasForeignKey(c => c.NIdReferencia60).WillCascadeOnDelete(false); // FK_SIR_124_ANTICIPOS_SIR_60_REFERENCIAS
        }
    }

}
// </auto-generated>
