// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_13_HISTORIAL_PARIDAD
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir13HistorialParidad
    {
        [Required]
        [Display(Name = "N ID histo paridad 13")]
        public int NIdHistoParidad13 { get; set; } // nIdHistoParidad13 (Primary key)

        [Required]
        [Display(Name = "N ID pais 01")]
        public int NIdPais01 { get; set; } // nIdPais01

        [Required]
        [Display(Name = "D fecha factor")]
        public System.DateTime DFechaFactor { get; set; } // dFechaFactor

        [Display(Name = "N valor factor")]
        public decimal? NValorFactor { get; set; } // nValorFactor

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "D fecha edicion")]
        public System.DateTime DFechaEdicion { get; set; } // dFechaEdicion

        [Required]
        [Display(Name = "N ID usuario ed")]
        public int NIdUsuarioEd { get; set; } // nIdUsuarioEd

        // Reverse navigation

        /// <summary>
        /// Child SIR_Sir52Factura where [SIR_52_FACTURAS].[nIdHistoParidad13] point to this entity (FK_SIR_52_FACTURAS_SIR_13_HISTORIAL_PARIDAD)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir52Factura> SIR_Sir52Factura { get; set; } // SIR_52_FACTURAS.FK_SIR_52_FACTURAS_SIR_13_HISTORIAL_PARIDAD
        /// <summary>
        /// Child SIR_Sir576FacturasAvisoArribo where [SIR_576_FACTURAS_AVISO_ARRIBO].[nIdHistoParidad13] point to this entity (FK_SIR_576_FACTURAS_AVISO_ARRIBO_SIR_13_HISTORIAL_PARIDAD)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir576FacturasAvisoArribo> SIR_Sir576FacturasAvisoArribo { get; set; } // SIR_576_FACTURAS_AVISO_ARRIBO.FK_SIR_576_FACTURAS_AVISO_ARRIBO_SIR_13_HISTORIAL_PARIDAD

        // Foreign keys

        /// <summary>
        /// Parent CatUsr pointed by [SIR_13_HISTORIAL_PARIDAD].([NIdUsuarioEd]) (FK_SIR_13_HISTORIAL_PARIDAD_cat_usr_ed)
        /// </summary>
        public virtual CatUsr CatUsr { get; set; } // FK_SIR_13_HISTORIAL_PARIDAD_cat_usr_ed

        /// <summary>
        /// Parent SIR_Sir01Pais pointed by [SIR_13_HISTORIAL_PARIDAD].([NIdPais01]) (FK_SIR_13_HISTORIAL_PARIDAD_SIR_01_PAISES)
        /// </summary>
        public virtual SIR_Sir01Pais SIR_Sir01Pais { get; set; } // FK_SIR_13_HISTORIAL_PARIDAD_SIR_01_PAISES

        public SIR_Sir13HistorialParidad()
        {
            DFechaEdicion = System.DateTime.Now;
            NIdUsuarioEd = 0;
            SIR_Sir52Factura = new System.Collections.Generic.List<SIR_Sir52Factura>();
            SIR_Sir576FacturasAvisoArribo = new System.Collections.Generic.List<SIR_Sir576FacturasAvisoArribo>();
        }
    }

}
// </auto-generated>
