// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_685_ FRACCIONES_DESDOBLAMIENTO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir685FraccionesDesdoblamiento
    {
        [Required]
        [Display(Name = "N idf racc desd 685")]
        public int NIdFraccDesd685 { get; set; } // nIDFraccDesd685 (Primary key)

        [Required]
        [Display(Name = "N ID fracc 167")]
        public int NIdFracc167 { get; set; } // nIdFracc167

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "S sub division")]
        public string SSubDivision { get; set; } // sSubDivision (length: 2)

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "S criterio desdoblamiento")]
        public string SCriterioDesdoblamiento { get; set; } // sCriterioDesdoblamiento

        [Display(Name = "N idu suario edicion")]
        public int? NIdUsuarioEdicion { get; set; } // nIDUsuarioEdicion

        [Display(Name = "S modificaciones")]
        public string SModificaciones { get; set; } // sModificaciones

        // Reverse navigation

        /// <summary>
        /// Child SIR_Sir99Parte where [SIR_99_PARTES].[nIDFraccDesd685] point to this entity (FK_SIR_99_PARTES_SIR_685_ FRACCIONES_DESDOBLAMIENTO)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir99Parte> SIR_Sir99Parte { get; set; } // SIR_99_PARTES.FK_SIR_99_PARTES_SIR_685_ FRACCIONES_DESDOBLAMIENTO

        // Foreign keys

        /// <summary>
        /// Parent SIR_Sir167FraccionesArancelaria pointed by [SIR_685_ FRACCIONES_DESDOBLAMIENTO].([NIdFracc167]) (SIR_685_ FRACCIONES_DESDOBLAMIENTO_SIR_167_FRACCIONES_ARANCELARIAS)
        /// </summary>
        public virtual SIR_Sir167FraccionesArancelaria SIR_Sir167FraccionesArancelaria { get; set; } // SIR_685_ FRACCIONES_DESDOBLAMIENTO_SIR_167_FRACCIONES_ARANCELARIAS

        public SIR_Sir685FraccionesDesdoblamiento()
        {
            SIR_Sir99Parte = new System.Collections.Generic.List<SIR_Sir99Parte>();
        }
    }

}
// </auto-generated>
