// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_60_REFERENCIAS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir60Referencia
    {
        [Required]
        [Display(Name = "N ID referencia 60")]
        public int NIdReferencia60 { get; set; } // nIdReferencia60 (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(64)]
        [StringLength(64)]
        [Display(Name = "S referencia")]
        public string SReferencia { get; set; } // sReferencia (length: 64)

        [Required]
        [Display(Name = "N ID expediente 59")]
        public int NIdExpediente59 { get; set; } // nIdExpediente59

        [Required]
        [Display(Name = "D fecha apertura")]
        public System.DateTime DFechaApertura { get; set; } // dFechaApertura

        [Display(Name = "N ID cliente")]
        public int? NIdCliente { get; set; } // nIdCliente

        [Required]
        [Display(Name = "N tipo operacion")]
        public byte NTipoOperacion { get; set; } // nTipoOperacion

        [Display(Name = "N ID reg trans 41")]
        public int? NIdRegTrans41 { get; set; } // nIdRegTrans41

        [Display(Name = "N ID puerto origen")]
        public int? NIdPuertoOrigen { get; set; } // nIdPuertoOrigen

        [Display(Name = "N peso bruto")]
        public decimal? NPesoBruto { get; set; } // nPesoBruto

        [Required]
        [Display(Name = "N ID tipo trafico 25")]
        public int NIdTipoTrafico25 { get; set; } // nIdTipoTrafico25

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "S comentario ref")]
        public string SComentarioRef { get; set; } // sComentarioRef (length: 50)

        [Required]
        [Display(Name = "N ID suc pat adu 71")]
        public int NIdSucPatAdu71 { get; set; } // nIdSucPatAdu71

        [Display(Name = "N ID ejecutivo")]
        public int? NIdEjecutivo { get; set; } // nIdEjecutivo

        [Display(Name = "N ID usuario")]
        public int? NIdUsuario { get; set; } // nIdUsuario

        [Display(Name = "N ID tipo ref")]
        public int? NIdTipoRef { get; set; } // nIdTipoRef

        [Required]
        [Display(Name = "D fecha operacion")]
        public System.DateTime DFechaOperacion { get; set; } // dFechaOperacion

        [Required(AllowEmptyStrings = true)]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "S mercancia desc")]
        public string SMercanciaDesc { get; set; } // sMercanciaDesc (length: 200)

        [Required]
        [Display(Name = "N sistema")]
        public byte NSistema { get; set; } // nSistema

        [Display(Name = "N ID adu sec 06")]
        public int? NIdAduSec06 { get; set; } // nIdAduSec06

        [Display(Name = "N ID imex")]
        public int? NIdImex { get; set; } // nIdImex

        [Display(Name = "N ID clave docto 28")]
        public int? NIdClaveDocto28 { get; set; } // nIdClaveDocto28

        [Required]
        [Display(Name = "B excluir cta gastos")]
        public bool BExcluirCtaGastos { get; set; } // bExcluirCtaGastos

        [Display(Name = "N ID consignataria")]
        public int? NIdConsignataria { get; set; } // nIdConsignataria

        [Display(Name = "D fecha cierre admin")]
        public System.DateTime? DFechaCierreAdmin { get; set; } // dFechaCierreAdmin

        [Display(Name = "D fecha cierre oper")]
        public System.DateTime? DFechaCierreOper { get; set; } // dFechaCierreOper

        [Display(Name = "N ID mtra sel ale 67")]
        public int? NIdMtraSelAle67 { get; set; } // nIdMtraSelAle67

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "D fecha edicion")]
        public System.DateTime DFechaEdicion { get; set; } // dFechaEdicion

        [Required]
        [Display(Name = "N ID usuario ed")]
        public int NIdUsuarioEd { get; set; } // nIdUsuarioEd

        [MaxLength(7)]
        [StringLength(7)]
        [Display(Name = "S num pedimento")]
        public string SNumPedimento { get; set; } // sNumPedimento (length: 7)

        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "S consignado a")]
        public string SConsignadoA { get; set; } // sConsignadoA (length: 80)

        [Display(Name = "N ID prog desp 134")]
        public int? NIdProgDesp134 { get; set; } // nIdProgDesp134

        [Required]
        [Display(Name = "N tipo carga")]
        public byte NTipoCarga { get; set; } // nTipoCarga

        [Required]
        [Display(Name = "N ID tipo merc 80")]
        public int NIdTipoMerc80 { get; set; } // nIdTipoMerc80

        [Required]
        [Display(Name = "N ID status 73")]
        public int NIdStatus73 { get; set; } // nIdStatus73

        [Display(Name = "N ID pedimento 149")]
        public int? NIdPedimento149 { get; set; } // nIdPedimento149

        [Display(Name = "N color")]
        public int? NColor { get; set; } // nColor

        [Display(Name = "N ID recti 28")]
        public int? NIdRecti28 { get; set; } // nIdRecti28

        [Display(Name = "N ID ref original 60")]
        public int? NIdRefOriginal60 { get; set; } // nIdRefOriginal60

        [Display(Name = "N ID ref hist 193")]
        public int? NIdRefHist193 { get; set; } // nIdRefHist193

        [Required]
        [Display(Name = "N ID cliente fact")]
        public int NIdClienteFact { get; set; } // nIdClienteFact

        [Display(Name = "N ID pr des bod 204")]
        public int? NIdPrDesBod204 { get; set; } // nIdPrDesBod204

        [Display(Name = "N valor fact par global")]
        public decimal? NValorFactParGlobal { get; set; } // nValorFactParGlobal

        [Display(Name = "N ID pais fac par 01")]
        public int? NIdPaisFacPar01 { get; set; } // nIdPaisFacPar01

        [Required]
        [Display(Name = "B es consolidado")]
        public bool BEsConsolidado { get; set; } // bEsConsolidado

        [Required]
        [Display(Name = "N sis origen")]
        public byte NSisOrigen { get; set; } // nSisOrigen

        [Required]
        [Display(Name = "N status vig")]
        public byte NStatusVig { get; set; } // nStatusVig

        [Display(Name = "S marcas numeros")]
        public string SMarcasNumeros { get; set; } // sMarcasNumeros

        [Display(Name = "S observaciones")]
        public string SObservaciones { get; set; } // sObservaciones

        [Display(Name = "D cierre cga")]
        public System.DateTime? DCierreCga { get; set; } // dCierreCGA

        [Display(Name = "N ID ori des 86")]
        public int? NIdOriDes86 { get; set; } // nIdOriDes86

        [Display(Name = "N ID recti 290")]
        public int? NIdRecti290 { get; set; } // nIdRecti290

        [Display(Name = "N ID extraccion 293")]
        public int? NIdExtraccion293 { get; set; } // nIdExtraccion293

        [Display(Name = "N ID linea naviera")]
        public int? NIdLineaNaviera { get; set; } // nIdLineaNaviera

        [Display(Name = "D presentacion")]
        public System.DateTime? DPresentacion { get; set; } // dPresentacion

        [Display(Name = "D cierre")]
        public System.DateTime? DCierre { get; set; } // dCierre

        [Display(Name = "D documentacion")]
        public System.DateTime? DDocumentacion { get; set; } // dDocumentacion

        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "S booking")]
        public string SBooking { get; set; } // sBooking (length: 30)

        [MaxLength(64)]
        [StringLength(64)]
        [Display(Name = "S ref corresponsal")]
        public string SRefCorresponsal { get; set; } // sRefCorresponsal (length: 64)

        [MaxLength(7)]
        [StringLength(7)]
        [Display(Name = "S ped corresponsal")]
        public string SPedCorresponsal { get; set; } // sPedCorresponsal (length: 7)

        [Display(Name = "N ID clias 304")]
        public int? NIdClias304 { get; set; } // nIdClias304

        [Display(Name = "D pago corresponsal")]
        public System.DateTime? DPagoCorresponsal { get; set; } // dPagoCorresponsal

        [Display(Name = "N ID puerto origen 04")]
        public int? NIdPuertoOrigen04 { get; set; } // nIdPuertoOrigen04

        [Display(Name = "N ID puerto destino 04")]
        public int? NIdPuertoDestino04 { get; set; } // nIdPuertoDestino04

        [Display(Name = "D ultimo contenedor")]
        public System.DateTime? DUltimoContenedor { get; set; } // dUltimoContenedor

        [Display(Name = "N financiamiento")]
        public decimal? NFinanciamiento { get; set; } // nFinanciamiento

        [Required]
        [Display(Name = "B captura manual")]
        public bool BCapturaManual { get; set; } // bCapturaManual

        [Display(Name = "N ID imex 07")]
        public int? NIdImex07 { get; set; } // nIdImex07

        [Display(Name = "N ID clie 07")]
        public int? NIdClie07 { get; set; } // nIdClie07

        [Display(Name = "N ID ejecutivo 02")]
        public int? NIdEjecutivo02 { get; set; } // nIdEjecutivo02

        [Display(Name = "N ID tipo ref 32")]
        public int? NIdTipoRef32 { get; set; } // nIdTipoRef32

        [Display(Name = "N ID clie fact 07")]
        public int? NIdClieFact07 { get; set; } // nIdClieFact07

        [Display(Name = "N ID naviera 42")]
        public int? NIdNaviera42 { get; set; } // nIdNaviera42

        [Display(Name = "N ID usu 01")]
        public int? NIdUsu01 { get; set; } // nIdUsu01

        [Display(Name = "D status")]
        public System.DateTime? DStatus { get; set; } // dStatus

        [Display(Name = "D constancia")]
        public System.DateTime? DConstancia { get; set; } // dConstancia

        [Display(Name = "D doctos ok")]
        public System.DateTime? DDoctosOk { get; set; } // dDoctosOK

        [Display(Name = "D entrega pre bl")]
        public System.DateTime? DEntregaPreBl { get; set; } // dEntregaPreBL

        [Display(Name = "D ped despachado")]
        public System.DateTime? DPedDespachado { get; set; } // dPedDespachado

        [Display(Name = "D carta terminal")]
        public System.DateTime? DCartaTerminal { get; set; } // dCartaTerminal

        [Display(Name = "D mcia trasladada")]
        public System.DateTime? DMciaTrasladada { get; set; } // dMciaTrasladada

        [Display(Name = "B sobredimension")]
        public bool? BSobredimension { get; set; } // bSobredimension

        [Display(Name = "N planas utilizadas")]
        public int? NPlanasUtilizadas { get; set; } // nPlanasUtilizadas

        [Required]
        [Display(Name = "B merc peligrosa")]
        public bool BMercPeligrosa { get; set; } // bMercPeligrosa

        [Display(Name = "N ID transportista")]
        public int? NIdTransportista { get; set; } // nIdTransportista

        [Display(Name = "N ID transportista 42")]
        public int? NIdTransportista42 { get; set; } // nIdTransportista42

        [Display(Name = "B flete prepagado")]
        public bool? BFletePrepagado { get; set; } // bFletePrepagado

        [Display(Name = "B otros inc pre pagado")]
        public bool? BOtrosIncPrePagado { get; set; } // bOtrosIncPrePagado

        [Display(Name = "N ID referencia 60 ext")]
        public int? NIdReferencia60Ext { get; set; } // nIdReferencia60Ext

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "S porcentaje honorarios")]
        public string SPorcentajeHonorarios { get; set; } // sPorcentajeHonorarios (length: 100)

        [Display(Name = "N clave tarifa honorarios")]
        public int? NClaveTarifaHonorarios { get; set; } // nClaveTarifaHonorarios

        [Display(Name = "N base honorarios")]
        public decimal? NBaseHonorarios { get; set; } // nBaseHonorarios

        [MaxLength(3000)]
        [StringLength(3000)]
        [Display(Name = "S motivo eliminacion")]
        public string SMotivoEliminacion { get; set; } // sMotivoEliminacion (length: 3000)

        [Display(Name = "B es rectificacion externa")]
        public bool? BEsRectificacionExterna { get; set; } // bEsRectificacionExterna

        [Display(Name = "B status ads")]
        public bool? BStatusAds { get; set; } // bStatusADS

        [DataType(DataType.DateTime)]
        [Display(Name = "D entrega")]
        public System.DateTime? DEntrega { get; set; } // dEntrega

        [Display(Name = "D fecha estimada despacho")]
        public System.DateTime? DFechaEstimadaDespacho { get; set; } // dFechaEstimadaDespacho

        [Display(Name = "D fecha despacho")]
        public System.DateTime? DFechaDespacho { get; set; } // dFechaDespacho

        [Display(Name = "B status rel confronta")]
        public bool? BStatusRelConfronta { get; set; } // bStatusRelConfronta

        [Display(Name = "D fs tatus rel confronta")]
        public System.DateTime? DFStatusRelConfronta { get; set; } // dFStatusRelConfronta

        [DataType(DataType.DateTime)]
        [Display(Name = "D fecha vo bo")]
        public System.DateTime? DFechaVoBo { get; set; } // dFechaVoBo

        [DataType(DataType.DateTime)]
        [Display(Name = "D entrega destino final")]
        public System.DateTime? DEntregaDestinoFinal { get; set; } // dEntregaDestinoFinal

        [Display(Name = "B master")]
        public bool? BMaster { get; set; } // bMaster

        [Display(Name = "N ID referencia master")]
        public int? NIdReferenciaMaster { get; set; } // nIdReferenciaMaster

        [Display(Name = "B consolidada")]
        public bool? BConsolidada { get; set; } // bConsolidada

        [Display(Name = "B crea referencia")]
        public bool? BCreaReferencia { get; set; } // bCreaReferencia

        [Display(Name = "D fecha hora recoleccion")]
        public System.DateTime? DFechaHoraRecoleccion { get; set; } // dFechaHoraRecoleccion

        [Display(Name = "N ID usuario recoleccion")]
        public int? NIdUsuarioRecoleccion { get; set; } // nIdUsuarioRecoleccion

        [Display(Name = "D fecha nota")]
        public System.DateTime? DFechaNota { get; set; } // dFechaNota

        [Display(Name = "N ID usuario nota")]
        public int? NIdUsuarioNota { get; set; } // nIdUsuarioNota

        [Display(Name = "D fecha clasificacion")]
        public System.DateTime? DFechaClasificacion { get; set; } // dFechaClasificacion

        [Display(Name = "N ID usuario clasificacion")]
        public int? NIdUsuarioClasificacion { get; set; } // nIdUsuarioClasificacion

        [Display(Name = "D fecha proforma")]
        public System.DateTime? DFechaProforma { get; set; } // dFechaProforma

        [Display(Name = "N ID usuario proforma")]
        public int? NIdUsuarioProforma { get; set; } // nIdUsuarioProforma

        [Display(Name = "D entrega at ransportista")]
        public System.DateTime? DEntregaATransportista { get; set; } // dEntregaATransportista

        [Display(Name = "N ID usuario at ransportista")]
        public int? NIdUsuarioATransportista { get; set; } // nIdUsuarioATransportista

        [Display(Name = "D fecha prealerta")]
        public System.DateTime? DFechaPrealerta { get; set; } // dFechaPrealerta

        [Display(Name = "N ID usuario prealerta")]
        public int? NIdUsuarioPrealerta { get; set; } // nIdUsuarioPrealerta

        [Display(Name = "D fecha solicitud clasificacion")]
        public System.DateTime? DFechaSolicitudClasificacion { get; set; } // dFechaSolicitudClasificacion

        [Display(Name = "N ID usuario solicitud clasificacion 01")]
        public int? NIdUsuarioSolicitudClasificacion01 { get; set; } // nIdUsuarioSolicitudClasificacion01

        [Display(Name = "N ID usuario recoleccion 01")]
        public int? NIdUsuarioRecoleccion01 { get; set; } // nIdUsuarioRecoleccion01

        [Display(Name = "N ID usuario prealerta 01")]
        public int? NIdUsuarioPrealerta01 { get; set; } // nIdUsuarioPrealerta01

        [Display(Name = "N ID usuario clasificacion 01")]
        public int? NIdUsuarioClasificacion01 { get; set; } // nIdUsuarioClasificacion01

        [Display(Name = "N ID usuario proforma 01")]
        public int? NIdUsuarioProforma01 { get; set; } // nIdUsuarioProforma01

        [Display(Name = "D envio contabilidad")]
        public System.DateTime? DEnvioContabilidad { get; set; } // dEnvioContabilidad

        [Display(Name = "D entrega carta traslado")]
        public System.DateTime? DEntregaCartaTraslado { get; set; } // dEntregaCartaTraslado

        [MaxLength(3000)]
        [StringLength(3000)]
        [Display(Name = "S motivo cierre operativo")]
        public string SMotivoCierreOperativo { get; set; } // sMotivoCierreOperativo (length: 3000)

        [Display(Name = "B cierre operativo")]
        public bool? BCierreOperativo { get; set; } // bCierreOperativo

        [Display(Name = "S num operacion")]
        public string SNumOperacion { get; set; } // sNumOperacion

        [Display(Name = "N ID usuario nota 01")]
        public int? NIdUsuarioNota01 { get; set; } // nIdUsuarioNota01

        [Display(Name = "N ID usuario at ransportista 01")]
        public int? NIdUsuarioATransportista01 { get; set; } // nIdUsuarioATransportista01

        [Display(Name = "N ID usuario solicitud clasificacion")]
        public int? NIdUsuarioSolicitudClasificacion { get; set; } // nIdUsuarioSolicitudClasificacion

        [Display(Name = "N ID ref comp 307")]
        public int? NIdRefComp307 { get; set; } // nIdRefComp307

        [Display(Name = "D fecha embarque")]
        public System.DateTime? DFechaEmbarque { get; set; } // dFechaEmbarque

        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "S observacion monitor ejecutivo")]
        public string SObservacionMonitorEjecutivo { get; set; } // sObservacionMonitorEjecutivo (length: 500)

        [Display(Name = "B visualizar en monitor ejecutivo")]
        public bool? BVisualizarEnMonitorEjecutivo { get; set; } // bVisualizarEnMonitorEjecutivo

        [Display(Name = "N ID solicitud sed 673")]
        public int? NIdSolicitudSed673 { get; set; } // nIdSolicitudSED673

        [Display(Name = "S freight bill")]
        public string SFreightBill { get; set; } // sFreightBill

        [Display(Name = "S observaciones de incumplido")]
        public string SObservacionesDeIncumplido { get; set; } // sObservacionesDeIncumplido

        [Display(Name = "D fecha entrega guia")]
        public System.DateTime? DFechaEntregaGuia { get; set; } // dFechaEntregaGuia

        [Display(Name = "D fecha corte solicitado")]
        public System.DateTime? DFechaCorteSolicitado { get; set; } // dFechaCorteSolicitado

        [Display(Name = "D fecha entrega mcia aduana")]
        public System.DateTime? DFechaEntregaMciaAduana { get; set; } // dFechaEntregaMciaAduana

        [Display(Name = "D fecha entrega doctos corte")]
        public System.DateTime? DFechaEntregaDoctosCorte { get; set; } // dFechaEntregaDoctosCorte

        [Display(Name = "S observaciones portada")]
        public string SObservacionesPortada { get; set; } // sObservacionesPortada

        [Display(Name = "N cove cc")]
        public decimal? NCoveCc { get; set; } // nCoveCC

        [Display(Name = "N validacion cc")]
        public decimal? NValidacionCc { get; set; } // nValidacionCC

        [Display(Name = "N complem sin val cove")]
        public decimal? NComplemSinValCove { get; set; } // nComplemSinValCove

        [Display(Name = "D fecha etae xpo")]
        public System.DateTime? DFechaEtaExpo { get; set; } // dFechaETAExpo

        [Display(Name = "N ID ref copia org 60")]
        public int? NIdRefCopiaOrg60 { get; set; } // nIdRefCopiaOrg60

        [Display(Name = "D fecha estimada pago")]
        public System.DateTime? DFechaEstimadaPago { get; set; } // dFechaEstimadaPago

        [Display(Name = "B desconsolidacion")]
        public bool? BDesconsolidacion { get; set; } // bDesconsolidacion

        [Display(Name = "B con demora")]
        public bool? BConDemora { get; set; } // bConDemora

        [Display(Name = "B previo en despacho")]
        public bool? BPrevioEnDespacho { get; set; } // bPrevioEnDespacho

        [Display(Name = "N dias obj calidad despacho")]
        public int? NDiasObjCalidadDespacho { get; set; } // nDiasObjCalidadDespacho

        [Display(Name = "N dias comodin despacho")]
        public int? NDiasComodinDespacho { get; set; } // nDiasComodinDespacho

        [Display(Name = "B obj calidad cumplido despacho")]
        public bool? BObjCalidadCumplidoDespacho { get; set; } // bObjCalidadCumplidoDespacho

        [Display(Name = "N dias obj calidad cga")]
        public int? NDiasObjCalidadCga { get; set; } // nDiasObjCalidadCGA

        [Display(Name = "N dias comodin cga")]
        public int? NDiasComodinCga { get; set; } // nDiasComodinCGA

        [Display(Name = "B obj calidad cumplido cga")]
        public bool? BObjCalidadCumplidoCga { get; set; } // bObjCalidadCumplidoCGA

        [Display(Name = "N ID estatus ref 804")]
        public int? NIdEstatusRef804 { get; set; } // nIdEstatusRef804

        [Display(Name = "B notifi enviada dom")]
        public bool? BNotifiEnviadaDom { get; set; } // bNotifiEnviadaDom

        [Display(Name = "N ID tarifa mercancia 112")]
        public int? NIdTarifaMercancia112 { get; set; } // nIdTarifaMercancia112

        [Display(Name = "B de carga m 3")]
        public bool? BDeCargaM3 { get; set; } // bDeCargaM3

        [Display(Name = "B requiere previo")]
        public bool? BRequierePrevio { get; set; } // bRequierePrevio

        [Display(Name = "B es historico")]
        public bool? BEsHistorico { get; set; } // bEsHistorico

        [Display(Name = "B procesando expediente")]
        public bool? BProcesandoExpediente { get; set; } // bProcesandoExpediente

        [DataType(DataType.DateTime)]
        [Display(Name = "D fecha procesa")]
        public System.DateTime? DFechaProcesa { get; set; } // dFechaProcesa

        [Display(Name = "N saldo")]
        public decimal? NSaldo { get; set; } // nSaldo

        [Display(Name = "N anticipo")]
        public decimal? NAnticipo { get; set; } // nAnticipo

        [Display(Name = "N iva")]
        public decimal? NIva { get; set; } // nIva

        [Display(Name = "N complementarios")]
        public decimal? NComplementarios { get; set; } // nComplementarios

        [Display(Name = "N honorarios")]
        public decimal? NHonorarios { get; set; } // nHonorarios

        [Display(Name = "N pagoshechos")]
        public decimal? NPagoshechos { get; set; } // nPagoshechos

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) SIR_Sir60Referencia pointed by [SIR_463_REEMBOLSO_REFERENCIA].[nIdReferencia60] (FK_SIR_463_REEMBOLSO_REFERENCIA_SIR_463_REEMBOLSO_REFERENCIA)
        /// </summary>
        public virtual SIR_Sir463ReembolsoReferencia SIR_Sir463ReembolsoReferencia { get; set; } // SIR_463_REEMBOLSO_REFERENCIA.FK_SIR_463_REEMBOLSO_REFERENCIA_SIR_463_REEMBOLSO_REFERENCIA
        /// <summary>
        /// Child Admin_Admino09DetallesPagoCliente where [ADMINO_09_DETALLES_PAGO_CLIENTE].[nIdReferencia60] point to this entity (FK_ADMINO_09_DETALLES_PAGO_CLIENTE_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Admin_Admino09DetallesPagoCliente> Admin_Admino09DetallesPagoCliente { get; set; } // ADMINO_09_DETALLES_PAGO_CLIENTE.FK_ADMINO_09_DETALLES_PAGO_CLIENTE_SIR_60_REFERENCIAS
        /// <summary>
        /// Child Admin_Admino16DetallesCuentasGasto where [ADMINO_16_DETALLES_CUENTAS_GASTOS].[nIdReferencia60] point to this entity (FK_ADMINO_16_DETALLES_CUENTAS_GASTOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Admin_Admino16DetallesCuentasGasto> Admin_Admino16DetallesCuentasGasto { get; set; } // ADMINO_16_DETALLES_CUENTAS_GASTOS.FK_ADMINO_16_DETALLES_CUENTAS_GASTOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child Admin_Admino23DetallesLiquidacione where [ADMINO_23_DETALLES_LIQUIDACIONES].[nIdReferencia60] point to this entity (FK_ADMINO_23_DETALLES_LIQUIDACIONES_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Admin_Admino23DetallesLiquidacione> Admin_Admino23DetallesLiquidacione { get; set; } // ADMINO_23_DETALLES_LIQUIDACIONES.FK_ADMINO_23_DETALLES_LIQUIDACIONES_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir100FacPartAgrupada where [SIR_100_FAC_PART_AGRUPADAS].[nIdReferencia60] point to this entity (FK_SIR_100_FAC_PART_AGRUPADAS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir100FacPartAgrupada> SIR_Sir100FacPartAgrupada { get; set; } // SIR_100_FAC_PART_AGRUPADAS.FK_SIR_100_FAC_PART_AGRUPADAS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir110DocumentosNoconforme where [SIR_110_DOCUMENTOS_NOCONFORMES].[nIdReferencia60] point to this entity (FK_SIR_110_DOCUMENTOS_NOCONFORMES_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir110DocumentosNoconforme> SIR_Sir110DocumentosNoconforme { get; set; } // SIR_110_DOCUMENTOS_NOCONFORMES.FK_SIR_110_DOCUMENTOS_NOCONFORMES_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir122SolCheqConcepto where [SIR_122_SOL_CHEQ_CONCEPTOS].[nIdReferencia60] point to this entity (FK_SIR_122_SOL_CHEQ_CONCEPTOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir122SolCheqConcepto> SIR_Sir122SolCheqConcepto { get; set; } // SIR_122_SOL_CHEQ_CONCEPTOS.FK_SIR_122_SOL_CHEQ_CONCEPTOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir123Cotizacione where [SIR_123_COTIZACIONES].[nIdReferencia60] point to this entity (FK_SIR_123_COTIZACIONES_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir123Cotizacione> SIR_Sir123Cotizacione { get; set; } // SIR_123_COTIZACIONES.FK_SIR_123_COTIZACIONES_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir124Anticipos where [SIR_124_ANTICIPOS].[nIdReferencia60] point to this entity (FK_SIR_124_ANTICIPOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir124Anticipos> SIR_Sir124Anticipos { get; set; } // SIR_124_ANTICIPOS.FK_SIR_124_ANTICIPOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir128PedidosCliente (Many-to-Many) mapped by table [SIR_345_REFERENCIAS_PEDIDOS]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir128PedidosCliente> SIR_Sir128PedidosCliente { get; set; } // Many to many mapping
        /// <summary>
        /// Child SIR_Sir135CargaSueltaDetalle where [SIR_135_CARGA_SUELTA_DETALLE].[nIdReferencia60] point to this entity (FK_SIR_135_CARGA_SUELTA_DETALLE_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir135CargaSueltaDetalle> SIR_Sir135CargaSueltaDetalle { get; set; } // SIR_135_CARGA_SUELTA_DETALLE.FK_SIR_135_CARGA_SUELTA_DETALLE_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir136TarifaMuellCalculo where [SIR_136_TARIFA_MUELL_CALCULO].[nIdReferencia60] point to this entity (FK_SIR_136_TARIFA_MUELL_CALCULO_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir136TarifaMuellCalculo> SIR_Sir136TarifaMuellCalculo { get; set; } // SIR_136_TARIFA_MUELL_CALCULO.FK_SIR_136_TARIFA_MUELL_CALCULO_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir148OrdenesReferencia where [SIR_148_ORDENES_REFERENCIAS].[nIdReferencia60] point to this entity (FK_SIR_148_ORDENES_REFERENCIAS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir148OrdenesReferencia> SIR_Sir148OrdenesReferencia { get; set; } // SIR_148_ORDENES_REFERENCIAS.FK_SIR_148_ORDENES_REFERENCIAS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir14Tinterterminale where [SIR_14_TINTERTERMINALES].[nIdReferencia60] point to this entity (FK_SIR_14_TINTERTERMINALES_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir14Tinterterminale> SIR_Sir14Tinterterminale { get; set; } // SIR_14_TINTERTERMINALES.FK_SIR_14_TINTERTERMINALES_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir161ProgPreviosRef where [SIR_161_PROG_PREVIOS_REF].[nIdReferencia60] point to this entity (FK_SIR_161_PROG_PREVIOS_REF_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir161ProgPreviosRef> SIR_Sir161ProgPreviosRef { get; set; } // SIR_161_PROG_PREVIOS_REF.FK_SIR_161_PROG_PREVIOS_REF_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir169SolicitudTransporte where [SIR_169_SOLICITUD_TRANSPORTE].[nIdReferencia60] point to this entity (FK_SIR_169_SOLICITUD_TRANSPORTE_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir169SolicitudTransporte> SIR_Sir169SolicitudTransporte { get; set; } // SIR_169_SOLICITUD_TRANSPORTE.FK_SIR_169_SOLICITUD_TRANSPORTE_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir186OrdenesRemisione (Many-to-Many) mapped by table [SIR_187_REFERENCIAS_REMISIONES]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir186OrdenesRemisione> SIR_Sir186OrdenesRemisione { get; set; } // Many to many mapping
        /// <summary>
        /// Child SIR_Sir192ActividadesReferencia where [SIR_192_ACTIVIDADES_REFERENCIAS].[nIdReferencia60] point to this entity (FK_SIR_192_ACTIVIDADES_REFERENCIAS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir192ActividadesReferencia> SIR_Sir192ActividadesReferencia { get; set; } // SIR_192_ACTIVIDADES_REFERENCIAS.FK_SIR_192_ACTIVIDADES_REFERENCIAS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir197Furgone where [SIR_197_FURGONES].[nIdReferencia60] point to this entity (FK_SIR_197_FURGONES_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir197Furgone> SIR_Sir197Furgone { get; set; } // SIR_197_FURGONES.FK_SIR_197_FURGONES_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir199BodegaServicio where [SIR_199_BODEGA_SERVICIOS].[nIdReferencia60] point to this entity (FK_SIR_199_BODEGA_SERVICIOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir199BodegaServicio> SIR_Sir199BodegaServicio { get; set; } // SIR_199_BODEGA_SERVICIOS.FK_SIR_199_BODEGA_SERVICIOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir206Remesa where [SIR_206_REMESAS].[nIdReferencia60] point to this entity (FK_SIR_206_REMESAS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir206Remesa> SIR_Sir206Remesa { get; set; } // SIR_206_REMESAS.FK_SIR_206_REMESAS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir228RegistrosSagarpa where [SIR_228_REGISTROS_SAGARPA].[nIdReferencia60] point to this entity (FK_SIR_228_REGISTROS_SAGARPA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir228RegistrosSagarpa> SIR_Sir228RegistrosSagarpa { get; set; } // SIR_228_REGISTROS_SAGARPA.FK_SIR_228_REGISTROS_SAGARPA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir251ManifestacionesValor where [SIR_251_MANIFESTACIONES_VALOR].[nIdReferencia60] point to this entity (FK_SIR_251_MANIFESTACIONES_VALOR_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir251ManifestacionesValor> SIR_Sir251ManifestacionesValor { get; set; } // SIR_251_MANIFESTACIONES_VALOR.FK_SIR_251_MANIFESTACIONES_VALOR_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir273Profepa where [SIR_273_PROFEPA].[nIdReferencia60] point to this entity (FK_SIR_273_PROFEPA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir273Profepa> SIR_Sir273Profepa { get; set; } // SIR_273_PROFEPA.FK_SIR_273_PROFEPA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir291SellosRecibido where [SIR_291_SELLOS_RECIBIDOS].[nIdReferencia60] point to this entity (FK_SIR_291_SELLOS_RECIBIDOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir291SellosRecibido> SIR_Sir291SellosRecibido { get; set; } // SIR_291_SELLOS_RECIBIDOS.FK_SIR_291_SELLOS_RECIBIDOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir293ExtraccionPedimento where [SIR_293_EXTRACCION_PEDIMENTOS].[nIdRefOrigen] point to this entity (FK_SIR_293_EXTRACCION_PEDIMENTOS_SIR_60_REFERENCIAS_ORIGEN)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir293ExtraccionPedimento> SIR_Sir293ExtraccionPedimento_NIdRefOrigen { get; set; } // SIR_293_EXTRACCION_PEDIMENTOS.FK_SIR_293_EXTRACCION_PEDIMENTOS_SIR_60_REFERENCIAS_ORIGEN
        /// <summary>
        /// Child SIR_Sir299ArchivosFactura where [SIR_299_ARCHIVOS_FACTURAS].[nIdReferencia60] point to this entity (FK_SIR_299_ARCHIVOS_FACTURAS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir299ArchivosFactura> SIR_Sir299ArchivosFactura { get; set; } // SIR_299_ARCHIVOS_FACTURAS.FK_SIR_299_ARCHIVOS_FACTURAS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir346SedDocument where [SIR_346_SED_DOCUMENTS].[nIdReferencia60] point to this entity (FK_SIR_346_SED_DOCUMENTS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir346SedDocument> SIR_Sir346SedDocument { get; set; } // SIR_346_SED_DOCUMENTS.FK_SIR_346_SED_DOCUMENTS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir34ReferenciasCatPro where [SIR_34_REFERENCIAS_CAT_PRO].[nIdReferencia60] point to this entity (FK_SIR_34_REFERENCIAS_CAT_PRO_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir34ReferenciasCatPro> SIR_Sir34ReferenciasCatPro { get; set; } // SIR_34_REFERENCIAS_CAT_PRO.FK_SIR_34_REFERENCIAS_CAT_PRO_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir367CaracReferencia where [SIR_367_CARAC_REFERENCIA].[nIdReferencia60] point to this entity (FK_367_CARAC_REFERENCIA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir367CaracReferencia> SIR_Sir367CaracReferencia { get; set; } // SIR_367_CARAC_REFERENCIA.FK_367_CARAC_REFERENCIA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir403EtapasReferencia where [SIR_403_ETAPAS_REFERENCIA].[nIdReferencia60] point to this entity (FK_SIR_403_ETAPAS_REFERENCIA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir403EtapasReferencia> SIR_Sir403EtapasReferencia { get; set; } // SIR_403_ETAPAS_REFERENCIA.FK_SIR_403_ETAPAS_REFERENCIA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir409ConfigVucem where [SIR_409_CONFIG_VUCEM].[nIdReferencia60] point to this entity (FK_SIR_409_CONFIG_VUCEM_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir409ConfigVucem> SIR_Sir409ConfigVucem { get; set; } // SIR_409_CONFIG_VUCEM.FK_SIR_409_CONFIG_VUCEM_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir40ValCamposActividade where [SIR_40_VAL_CAMPOS_ACTIVIDADES].[nIdReferencia60] point to this entity (FK_SIR_40_VAL_CAMPOS_ACTIVIDADES_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir40ValCamposActividade> SIR_Sir40ValCamposActividade { get; set; } // SIR_40_VAL_CAMPOS_ACTIVIDADES.FK_SIR_40_VAL_CAMPOS_ACTIVIDADES_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir478NotificacionesBandeja where [SIR_478_NOTIFICACIONES_BANDEJA].[nIdReferencia60] point to this entity (FK_SIR_478_NOTIFICACIONES_BANDEJA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir478NotificacionesBandeja> SIR_Sir478NotificacionesBandeja { get; set; } // SIR_478_NOTIFICACIONES_BANDEJA.FK_SIR_478_NOTIFICACIONES_BANDEJA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir492DatosTarifa where [SIR_492_DATOS_TARIFA].[nIdReferencia60] point to this entity (FK_SIR_492_DATOS_TARIFA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir492DatosTarifa> SIR_Sir492DatosTarifa { get; set; } // SIR_492_DATOS_TARIFA.FK_SIR_492_DATOS_TARIFA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir52Factura (Many-to-Many) mapped by table [SIR_188_FACTURAS_REFERENCIAS]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir52Factura> SIR_Sir52Factura { get; set; } // Many to many mapping
        /// <summary>
        /// Child SIR_Sir560PedimentoEdespacho where [SIR_560_PEDIMENTO_EDESPACHO].[nIdReferencia60] point to this entity (FK_SIR_560_PEDIMENTO_EDESPACHO_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir560PedimentoEdespacho> SIR_Sir560PedimentoEdespacho { get; set; } // SIR_560_PEDIMENTO_EDESPACHO.FK_SIR_560_PEDIMENTO_EDESPACHO_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir571CalculoAlmacenaje where [SIR_571_CALCULO_ALMACENAJE].[nIdReferencia60] point to this entity (FK_SIR_571_CALCULO_ALMACENAJE_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir571CalculoAlmacenaje> SIR_Sir571CalculoAlmacenaje { get; set; } // SIR_571_CALCULO_ALMACENAJE.FK_SIR_571_CALCULO_ALMACENAJE_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir584BlIncidencia where [SIR_584_BL_INCIDENCIAS].[nIdReferencia60] point to this entity (FK_SIR_584_BL_INCIDENCIAS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir584BlIncidencia> SIR_Sir584BlIncidencia { get; set; } // SIR_584_BL_INCIDENCIAS.FK_SIR_584_BL_INCIDENCIAS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir590ReferenciasSubdivision where [SIR_590_REFERENCIAS_SUBDIVISION].[nIdRefOriginal60] point to this entity (FK_SIR_590_REFERENCIAS_SUBDIVISION_SIR_60_REFERENCIAS_ORIGINAL)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir590ReferenciasSubdivision> SIR_Sir590ReferenciasSubdivision_NIdRefOriginal60 { get; set; } // SIR_590_REFERENCIAS_SUBDIVISION.FK_SIR_590_REFERENCIAS_SUBDIVISION_SIR_60_REFERENCIAS_ORIGINAL
        /// <summary>
        /// Child SIR_Sir590ReferenciasSubdivision where [SIR_590_REFERENCIAS_SUBDIVISION].[nIdRefSubdivision60] point to this entity (FK_SIR_590_REFERENCIAS_SUBDIVISION_SIR_60_REFERENCIAS_SUBDIVISION)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir590ReferenciasSubdivision> SIR_Sir590ReferenciasSubdivision_NIdRefSubdivision60 { get; set; } // SIR_590_REFERENCIAS_SUBDIVISION.FK_SIR_590_REFERENCIAS_SUBDIVISION_SIR_60_REFERENCIAS_SUBDIVISION
        /// <summary>
        /// Child SIR_Sir60Referencia where [SIR_60_REFERENCIAS].[nIdReferenciaMaster] point to this entity (FK_SIR_60_REFERENCIAS_SIR_60_REFERENCIAS_nIdReferenciaMaster)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir60Referencia> SIR_Sir60Referencia2 { get; set; } // SIR_60_REFERENCIAS.FK_SIR_60_REFERENCIAS_SIR_60_REFERENCIAS_nIdReferenciaMaster
        /// <summary>
        /// Child SIR_Sir626RevisionDocumental where [SIR_626_REVISION_DOCUMENTAL].[nIdReferencia60] point to this entity (FK_SIR_626_REVISION_DOCUMENTAL_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir626RevisionDocumental> SIR_Sir626RevisionDocumental { get; set; } // SIR_626_REVISION_DOCUMENTAL.FK_SIR_626_REVISION_DOCUMENTAL_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir635MonitorClasificacion where [SIR_635_MONITOR_CLASIFICACION].[nIdReferencia60] point to this entity (FK_SIR_635_MONITOR_CLASIFICACION_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir635MonitorClasificacion> SIR_Sir635MonitorClasificacion { get; set; } // SIR_635_MONITOR_CLASIFICACION.FK_SIR_635_MONITOR_CLASIFICACION_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir63Documento where [SIR_63_DOCUMENTOS].[nIdReferencia60] point to this entity (FK_SIR_63_DOCUMENTOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir63Documento> SIR_Sir63Documento { get; set; } // SIR_63_DOCUMENTOS.FK_SIR_63_DOCUMENTOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir646OrdenesDeTrabajo where [SIR_646_ORDENES_DE_TRABAJO].[nIdReferencia60] point to this entity (FK_SIR_646_ORDENES_DE_TRABAJO_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir646OrdenesDeTrabajo> SIR_Sir646OrdenesDeTrabajo { get; set; } // SIR_646_ORDENES_DE_TRABAJO.FK_SIR_646_ORDENES_DE_TRABAJO_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir681EtapasMonitorEjecutivoReferencia where [SIR_681_ETAPAS_MONITOR_EJECUTIVO_REFERENCIA].[nIdReferencia60] point to this entity (FK_SIR_681_ETAPAS_MONITOR_EJECUTIVO_REFERENCIA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir681EtapasMonitorEjecutivoReferencia> SIR_Sir681EtapasMonitorEjecutivoReferencia { get; set; } // SIR_681_ETAPAS_MONITOR_EJECUTIVO_REFERENCIA.FK_SIR_681_ETAPAS_MONITOR_EJECUTIVO_REFERENCIA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir695HistSubdivision where [SIR_695_HIST_SUBDIVISION].[nIdReferenciaOrig60] point to this entity (FK_SIR_695_HIST_SUBDIVISION_SIR_60_REFERENCIAS_ORIG)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir695HistSubdivision> SIR_Sir695HistSubdivision_NIdReferenciaOrig60 { get; set; } // SIR_695_HIST_SUBDIVISION.FK_SIR_695_HIST_SUBDIVISION_SIR_60_REFERENCIAS_ORIG
        /// <summary>
        /// Child SIR_Sir695HistSubdivision where [SIR_695_HIST_SUBDIVISION].[nIdReferenciaSub60] point to this entity (FK_SIR_695_HIST_SUBDIVISION_SIR_60_REFERENCIAS_SUB)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir695HistSubdivision> SIR_Sir695HistSubdivision_NIdReferenciaSub60 { get; set; } // SIR_695_HIST_SUBDIVISION.FK_SIR_695_HIST_SUBDIVISION_SIR_60_REFERENCIAS_SUB
        /// <summary>
        /// Child SIR_Sir699GastoscompRef where [SIR_699_GASTOSCOMP_REF].[nIdReferencia60] point to this entity (FK_SIR_699_GASTOSCOMP_REF_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir699GastoscompRef> SIR_Sir699GastoscompRef { get; set; } // SIR_699_GASTOSCOMP_REF.FK_SIR_699_GASTOSCOMP_REF_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir701RevisionDocumento where [SIR_701_REVISION_DOCUMENTOS].[nIdReferencia60] point to this entity (FK_SIR_701_REVISION_DOCUMENTOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir701RevisionDocumento> SIR_Sir701RevisionDocumento { get; set; } // SIR_701_REVISION_DOCUMENTOS.FK_SIR_701_REVISION_DOCUMENTOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir709AvisosEletronico where [SIR_709_AVISOS_ELETRONICOS].[nIdReferencia60] point to this entity (FK_SIR_709_AVISOS_ELETRONICOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir709AvisosEletronico> SIR_Sir709AvisosEletronico { get; set; } // SIR_709_AVISOS_ELETRONICOS.FK_SIR_709_AVISOS_ELETRONICOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir726BitacoraReferenciaCuentaAmericanaAx where [SIR_726_BITACORA_REFERENCIA_CUENTA_AMERICANA_AX].[nIdReferencia60] point to this entity (FK_SIR_726_BITACORA_CUENTA_AMERICANA_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir726BitacoraReferenciaCuentaAmericanaAx> SIR_Sir726BitacoraReferenciaCuentaAmericanaAx { get; set; } // SIR_726_BITACORA_REFERENCIA_CUENTA_AMERICANA_AX.FK_SIR_726_BITACORA_CUENTA_AMERICANA_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir734BitacoraNotificacionPagoPedimento where [SIR_734_BITACORA_NOTIFICACION_PAGO_PEDIMENTO].[nIdReferencia] point to this entity (FK_SIR_734_BITACORA_NOTIFICACION_PAGO_PEDIMENTO_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir734BitacoraNotificacionPagoPedimento> SIR_Sir734BitacoraNotificacionPagoPedimento { get; set; } // SIR_734_BITACORA_NOTIFICACION_PAGO_PEDIMENTO.FK_SIR_734_BITACORA_NOTIFICACION_PAGO_PEDIMENTO_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir753ServiciosNoconforme where [SIR_753_SERVICIOS_NOCONFORME].[nIdReferencia60] point to this entity (FK_SIR_753_SERVICIOS_NOCONFORME_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir753ServiciosNoconforme> SIR_Sir753ServiciosNoconforme { get; set; } // SIR_753_SERVICIOS_NOCONFORME.FK_SIR_753_SERVICIOS_NOCONFORME_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir76Contenedore where [SIR_76_CONTENEDORES].[nIdReferencia60] point to this entity (FK_SIR_76_CONTENEDORES_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir76Contenedore> SIR_Sir76Contenedore { get; set; } // SIR_76_CONTENEDORES.FK_SIR_76_CONTENEDORES_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir781ConsultaExpedienteCove where [SIR_781_CONSULTA_EXPEDIENTE_COVE].[nIdReferencia60] point to this entity (FK_SIR_781_CONSULTA_EXPEDIENTE_COVE_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir781ConsultaExpedienteCove> SIR_Sir781ConsultaExpedienteCove { get; set; } // SIR_781_CONSULTA_EXPEDIENTE_COVE.FK_SIR_781_CONSULTA_EXPEDIENTE_COVE_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir78ReferenciasObserv where [SIR_78_REFERENCIAS_OBSERV].[nIdReferencia60] point to this entity (FK_SIR_78_REFERENCIAS_OBSERV_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir78ReferenciasObserv> SIR_Sir78ReferenciasObserv { get; set; } // SIR_78_REFERENCIAS_OBSERV.FK_SIR_78_REFERENCIAS_OBSERV_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir797NotificacionSirApp where [SIR_797_NOTIFICACION_SIR_APP].[nIdReferencia60] point to this entity (FK_SIR_797_NOTIFICACION_SIR_APP_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir797NotificacionSirApp> SIR_Sir797NotificacionSirApp { get; set; } // SIR_797_NOTIFICACION_SIR_APP.FK_SIR_797_NOTIFICACION_SIR_APP_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir79ReferenciasBl where [SIR_79_REFERENCIAS_BLS].[nIdReferencia60] point to this entity (FK_SIR_79_REFERENCIAS_BLS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir79ReferenciasBl> SIR_Sir79ReferenciasBl { get; set; } // SIR_79_REFERENCIAS_BLS.FK_SIR_79_REFERENCIAS_BLS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir87SolicitudServicio where [SIR_87_SOLICITUD_SERVICIOS].[nIdReferencia60] point to this entity (FK_SIR_87_SOLICITUD_SERVICIOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir87SolicitudServicio> SIR_Sir87SolicitudServicio { get; set; } // SIR_87_SOLICITUD_SERVICIOS.FK_SIR_87_SOLICITUD_SERVICIOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir92ObservRefOperativa where [SIR_92_OBSERV_REF_OPERATIVAS].[nIdReferencia60] point to this entity (FK_SIR_92_OBSERV_REF_OPERATIVAS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir92ObservRefOperativa> SIR_Sir92ObservRefOperativa { get; set; } // SIR_92_OBSERV_REF_OPERATIVAS.FK_SIR_92_OBSERV_REF_OPERATIVAS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIR_Sir94PreBl where [SIR_94_PRE_BLS].[nIdReferencia60] point to this entity (FK_SIR_94_PRE_BLS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir94PreBl> SIR_Sir94PreBl { get; set; } // SIR_94_PRE_BLS.FK_SIR_94_PRE_BLS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIRAdmin_Sira48DetalleProgServicio where [SIRA_48_DETALLE_PROG_SERVICIOS].[nIdReferencia60] point to this entity (FK_SIRA_48_DETALLE_PROG_SERVICIOS_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIRAdmin_Sira48DetalleProgServicio> SIRAdmin_Sira48DetalleProgServicio { get; set; } // SIRA_48_DETALLE_PROG_SERVICIOS.FK_SIRA_48_DETALLE_PROG_SERVICIOS_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIRAdmin_Sira49LiberacionContenedor where [SIRA_49_LIBERACION_CONTENEDOR].[nIdReferencia60] point to this entity (FK_SIRA_49_LIBERACION_CONTENEDOR_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIRAdmin_Sira49LiberacionContenedor> SIRAdmin_Sira49LiberacionContenedor { get; set; } // SIRA_49_LIBERACION_CONTENEDOR.FK_SIRA_49_LIBERACION_CONTENEDOR_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SIRAdmin_Sira50Booking where [SIRA_50_BOOKING].[nIdReferencia60] point to this entity (FK_SIRA_50_BOOKING_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIRAdmin_Sira50Booking> SIRAdmin_Sira50Booking { get; set; } // SIRA_50_BOOKING.FK_SIRA_50_BOOKING_SIR_60_REFERENCIAS
        /// <summary>
        /// Child SisRefRelDocs where [sis_ref_rel_doc].[id_ref] point to this entity (FK_sis_ref_rel_doc_SIR_60_REFERENCIAS)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SisRefRelDoc> SisRefRelDocs { get; set; } // sis_ref_rel_doc.FK_sis_ref_rel_doc_SIR_60_REFERENCIAS

        // Foreign keys

        /// <summary>
        /// Parent Admin_Admina01Usuario pointed by [SIR_60_REFERENCIAS].([NIdUsu01]) (FK_SIR_60_REFERENCIAS_ADMINA_01_USUARIOS)
        /// </summary>
        public virtual Admin_Admina01Usuario Admin_Admina01Usuario_NIdUsu01 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINA_01_USUARIOS

        /// <summary>
        /// Parent Admin_Admina01Usuario pointed by [SIR_60_REFERENCIAS].([NIdUsuarioATransportista01]) (FK_SIR_60_REFERENCIAS_ADMINA_01_USUARIOS_nIdUsuarioATransportista01)
        /// </summary>
        public virtual Admin_Admina01Usuario Admin_Admina01Usuario_NIdUsuarioATransportista01 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINA_01_USUARIOS_nIdUsuarioATransportista01

        /// <summary>
        /// Parent Admin_Admina01Usuario pointed by [SIR_60_REFERENCIAS].([NIdUsuarioNota01]) (FK_SIR_60_REFERENCIAS_ADMINA_01_USUARIOS_nIdUsuarioNota01)
        /// </summary>
        public virtual Admin_Admina01Usuario Admin_Admina01Usuario_NIdUsuarioNota01 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINA_01_USUARIOS_nIdUsuarioNota01

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_60_REFERENCIAS].([NIdEjecutivo02]) (FK_SIR_60_REFERENCIAS_ADMINA_02_PERSONAL)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal { get; set; } // FK_SIR_60_REFERENCIAS_ADMINA_02_PERSONAL

        /// <summary>
        /// Parent Admin_Adminc07Cliente pointed by [SIR_60_REFERENCIAS].([NIdClie07]) (FK_SIR_60_REFERENCIAS_ADMINC_07_CLIENTES_nIdClie07)
        /// </summary>
        public virtual Admin_Adminc07Cliente Admin_Adminc07Cliente_NIdClie07 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINC_07_CLIENTES_nIdClie07

        /// <summary>
        /// Parent Admin_Adminc07Cliente pointed by [SIR_60_REFERENCIAS].([NIdClieFact07]) (FK_SIR_60_REFERENCIAS_ADMINC_07_CLIENTES_nIdClieFact07)
        /// </summary>
        public virtual Admin_Adminc07Cliente Admin_Adminc07Cliente_NIdClieFact07 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINC_07_CLIENTES_nIdClieFact07

        /// <summary>
        /// Parent Admin_Adminc07Cliente pointed by [SIR_60_REFERENCIAS].([NIdImex07]) (FK_SIR_60_REFERENCIAS_ADMINC_07_CLIENTES_nIdImex07)
        /// </summary>
        public virtual Admin_Adminc07Cliente Admin_Adminc07Cliente_NIdImex07 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINC_07_CLIENTES_nIdImex07

        /// <summary>
        /// Parent Admin_Adminc32TiposReferencia pointed by [SIR_60_REFERENCIAS].([NIdTipoRef32]) (FK_SIR_60_REFERENCIAS_ADMINC_32_TIPOS_REFERENCIAS)
        /// </summary>
        public virtual Admin_Adminc32TiposReferencia Admin_Adminc32TiposReferencia { get; set; } // FK_SIR_60_REFERENCIAS_ADMINC_32_TIPOS_REFERENCIAS

        /// <summary>
        /// Parent Admin_Adminc42Proveedore pointed by [SIR_60_REFERENCIAS].([NIdNaviera42]) (FK_SIR_60_REFERENCIAS_ADMINC_42_PROVEEDORES)
        /// </summary>
        public virtual Admin_Adminc42Proveedore Admin_Adminc42Proveedore_NIdNaviera42 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINC_42_PROVEEDORES

        /// <summary>
        /// Parent Admin_Adminc42Proveedore pointed by [SIR_60_REFERENCIAS].([NIdTransportista42]) (FK_SIR_60_REFERENCIAS_ADMINC_42_PROVEEDORES_Transportista)
        /// </summary>
        public virtual Admin_Adminc42Proveedore Admin_Adminc42Proveedore_NIdTransportista42 { get; set; } // FK_SIR_60_REFERENCIAS_ADMINC_42_PROVEEDORES_Transportista

        /// <summary>
        /// Parent CatCliente pointed by [SIR_60_REFERENCIAS].([NIdCliente]) (FK_SIR_60_REFERENCIAS_cat_clientes)
        /// </summary>
        public virtual CatCliente CatCliente_NIdCliente { get; set; } // FK_SIR_60_REFERENCIAS_cat_clientes

        /// <summary>
        /// Parent CatCliente pointed by [SIR_60_REFERENCIAS].([NIdClienteFact]) (FK_SIR_60_REFERENCIAS_cat_clientes_fact)
        /// </summary>
        public virtual CatCliente CatCliente_NIdClienteFact { get; set; } // FK_SIR_60_REFERENCIAS_cat_clientes_fact

        /// <summary>
        /// Parent CatCliente pointed by [SIR_60_REFERENCIAS].([NIdImex]) (FK_SIR_60_REFERENCIAS_cat_clientes1)
        /// </summary>
        public virtual CatCliente CatCliente_NIdImex { get; set; } // FK_SIR_60_REFERENCIAS_cat_clientes1

        /// <summary>
        /// Parent CatEmp pointed by [SIR_60_REFERENCIAS].([NIdEjecutivo]) (FK_SIR_60_REFERENCIAS_cat_emp)
        /// </summary>
        public virtual CatEmp CatEmp { get; set; } // FK_SIR_60_REFERENCIAS_cat_emp

        /// <summary>
        /// Parent CatProv pointed by [SIR_60_REFERENCIAS].([NIdConsignataria]) (FK_SIR_60_REFERENCIAS_cat_prov)
        /// </summary>
        public virtual CatProv CatProv_NIdConsignataria { get; set; } // FK_SIR_60_REFERENCIAS_cat_prov

        /// <summary>
        /// Parent CatProv pointed by [SIR_60_REFERENCIAS].([NIdLineaNaviera]) (FK_SIR_60_REFERENCIAS_cat_prov_naviera)
        /// </summary>
        public virtual CatProv CatProv_NIdLineaNaviera { get; set; } // FK_SIR_60_REFERENCIAS_cat_prov_naviera

        /// <summary>
        /// Parent CatProv pointed by [SIR_60_REFERENCIAS].([NIdTransportista]) (FK_SIR_60_REFERENCIAS_cat_prov_Transportista)
        /// </summary>
        public virtual CatProv CatProv_NIdTransportista { get; set; } // FK_SIR_60_REFERENCIAS_cat_prov_Transportista

        /// <summary>
        /// Parent CatUsr pointed by [SIR_60_REFERENCIAS].([NIdUsuario]) (FK_SIR_60_REFERENCIAS_cat_usr)
        /// </summary>
        public virtual CatUsr CatUsr { get; set; } // FK_SIR_60_REFERENCIAS_cat_usr

        /// <summary>
        /// Parent SIR_Sir01Pais pointed by [SIR_60_REFERENCIAS].([NIdPaisFacPar01]) (FK_SIR_60_REFERENCIAS_SIR_01_PAISES)
        /// </summary>
        public virtual SIR_Sir01Pais SIR_Sir01Pais { get; set; } // FK_SIR_60_REFERENCIAS_SIR_01_PAISES

        /// <summary>
        /// Parent SIR_Sir04Puerto pointed by [SIR_60_REFERENCIAS].([NIdPuertoDestino04]) (FK_SIR_60_REFERENCIAS_SIR_04_PUERTOS_DESTINO)
        /// </summary>
        public virtual SIR_Sir04Puerto SIR_Sir04Puerto_NIdPuertoDestino04 { get; set; } // FK_SIR_60_REFERENCIAS_SIR_04_PUERTOS_DESTINO

        /// <summary>
        /// Parent SIR_Sir04Puerto pointed by [SIR_60_REFERENCIAS].([NIdPuertoOrigen]) (FK_SIR_60_REFERENCIAS_SIR_04_PUERTOS)
        /// </summary>
        public virtual SIR_Sir04Puerto SIR_Sir04Puerto_NIdPuertoOrigen { get; set; } // FK_SIR_60_REFERENCIAS_SIR_04_PUERTOS

        /// <summary>
        /// Parent SIR_Sir04Puerto pointed by [SIR_60_REFERENCIAS].([NIdPuertoOrigen04]) (FK_SIR_60_REFERENCIAS_SIR_04_PUERTOS_ORIGEN)
        /// </summary>
        public virtual SIR_Sir04Puerto SIR_Sir04Puerto_NIdPuertoOrigen04 { get; set; } // FK_SIR_60_REFERENCIAS_SIR_04_PUERTOS_ORIGEN

        /// <summary>
        /// Parent SIR_Sir06AduanaSec pointed by [SIR_60_REFERENCIAS].([NIdAduSec06]) (FK_SIR_60_REFERENCIAS_SIR_06_ADUANA_SEC)
        /// </summary>
        public virtual SIR_Sir06AduanaSec SIR_Sir06AduanaSec { get; set; } // FK_SIR_60_REFERENCIAS_SIR_06_ADUANA_SEC

        /// <summary>
        /// Parent SIR_Sir134ProgramacionDespacho pointed by [SIR_60_REFERENCIAS].([NIdProgDesp134]) (FK_SIR_60_REFERENCIAS_SIR_134_PROGRAMACION_DESPACHOS)
        /// </summary>
        public virtual SIR_Sir134ProgramacionDespacho SIR_Sir134ProgramacionDespacho { get; set; } // FK_SIR_60_REFERENCIAS_SIR_134_PROGRAMACION_DESPACHOS

        /// <summary>
        /// Parent SIR_Sir149Pedimento pointed by [SIR_60_REFERENCIAS].([NIdPedimento149]) (FK_SIR_60_REFERENCIAS_SIR_149_PEDIMENTO)
        /// </summary>
        public virtual SIR_Sir149Pedimento SIR_Sir149Pedimento { get; set; } // FK_SIR_60_REFERENCIAS_SIR_149_PEDIMENTO

        /// <summary>
        /// Parent SIR_Sir193ReferenciasHistorico pointed by [SIR_60_REFERENCIAS].([NIdRefHist193]) (FK_SIR_60_REFERENCIAS_SIR_193_REFERENCIAS_HISTORICO)
        /// </summary>
        public virtual SIR_Sir193ReferenciasHistorico SIR_Sir193ReferenciasHistorico { get; set; } // FK_SIR_60_REFERENCIAS_SIR_193_REFERENCIAS_HISTORICO

        /// <summary>
        /// Parent SIR_Sir204ProgDespachosBodega pointed by [SIR_60_REFERENCIAS].([NIdPrDesBod204]) (FK_SIR_60_REFERENCIAS_SIR_204_PROG_DESPACHOS_BODEGA)
        /// </summary>
        public virtual SIR_Sir204ProgDespachosBodega SIR_Sir204ProgDespachosBodega { get; set; } // FK_SIR_60_REFERENCIAS_SIR_204_PROG_DESPACHOS_BODEGA

        /// <summary>
        /// Parent SIR_Sir25TiposTrafico pointed by [SIR_60_REFERENCIAS].([NIdTipoTrafico25]) (FK_SIR_60_REFERENCIAS_SIR_25_TIPOS_TRAFICO)
        /// </summary>
        public virtual SIR_Sir25TiposTrafico SIR_Sir25TiposTrafico { get; set; } // FK_SIR_60_REFERENCIAS_SIR_25_TIPOS_TRAFICO

        /// <summary>
        /// Parent SIR_Sir28ClavesDocto pointed by [SIR_60_REFERENCIAS].([NIdClaveDocto28]) (FK_SIR_60_REFERENCIAS_SIR_28_CLAVES_DOCTOS)
        /// </summary>
        public virtual SIR_Sir28ClavesDocto SIR_Sir28ClavesDocto_NIdClaveDocto28 { get; set; } // FK_SIR_60_REFERENCIAS_SIR_28_CLAVES_DOCTOS

        /// <summary>
        /// Parent SIR_Sir28ClavesDocto pointed by [SIR_60_REFERENCIAS].([NIdRecti28]) (FK_SIR_60_REFERENCIAS_SIR_28_CLAVES_DOCTOS_RECTI)
        /// </summary>
        public virtual SIR_Sir28ClavesDocto SIR_Sir28ClavesDocto_NIdRecti28 { get; set; } // FK_SIR_60_REFERENCIAS_SIR_28_CLAVES_DOCTOS_RECTI

        /// <summary>
        /// Parent SIR_Sir290RectificPedimento pointed by [SIR_60_REFERENCIAS].([NIdRecti290]) (FK_SIR_60_REFERENCIAS_SIR_290_RECTIFIC_PEDIMENTO)
        /// </summary>
        public virtual SIR_Sir290RectificPedimento SIR_Sir290RectificPedimento { get; set; } // FK_SIR_60_REFERENCIAS_SIR_290_RECTIFIC_PEDIMENTO

        /// <summary>
        /// Parent SIR_Sir293ExtraccionPedimento pointed by [SIR_60_REFERENCIAS].([NIdExtraccion293]) (FK_SIR_60_REFERENCIAS_SIR_293_EXTRACCION_PEDIMENTOS)
        /// </summary>
        public virtual SIR_Sir293ExtraccionPedimento SIR_Sir293ExtraccionPedimento_NIdExtraccion293 { get; set; } // FK_SIR_60_REFERENCIAS_SIR_293_EXTRACCION_PEDIMENTOS

        /// <summary>
        /// Parent SIR_Sir304Corresponsalia pointed by [SIR_60_REFERENCIAS].([NIdClias304]) (FK_SIR_60_REFERENCIAS_SIR_304_CORRESPONSALIAS)
        /// </summary>
        public virtual SIR_Sir304Corresponsalia SIR_Sir304Corresponsalia { get; set; } // FK_SIR_60_REFERENCIAS_SIR_304_CORRESPONSALIAS

        /// <summary>
        /// Parent SIR_Sir307RefComplementaria pointed by [SIR_60_REFERENCIAS].([NIdRefComp307]) (FK_SIR_60_REFERENCIAS_SIR_307_REF_COMPLEMENTARIAS_nIdRefComp307)
        /// </summary>
        public virtual SIR_Sir307RefComplementaria SIR_Sir307RefComplementaria { get; set; } // FK_SIR_60_REFERENCIAS_SIR_307_REF_COMPLEMENTARIAS_nIdRefComp307

        /// <summary>
        /// Parent SIR_Sir41RegTransporte pointed by [SIR_60_REFERENCIAS].([NIdRegTrans41]) (FK_SIR_60_REFERENCIAS_SIR_41_REG_TRANSPORTES)
        /// </summary>
        public virtual SIR_Sir41RegTransporte SIR_Sir41RegTransporte { get; set; } // FK_SIR_60_REFERENCIAS_SIR_41_REG_TRANSPORTES

        /// <summary>
        /// Parent SIR_Sir59Expediente pointed by [SIR_60_REFERENCIAS].([NIdExpediente59]) (FK_SIR_60_REFERENCIAS_SIR_59_EXPEDIENTES)
        /// </summary>
        public virtual SIR_Sir59Expediente SIR_Sir59Expediente { get; set; } // FK_SIR_60_REFERENCIAS_SIR_59_EXPEDIENTES

        /// <summary>
        /// Parent SIR_Sir60Referencia pointed by [SIR_60_REFERENCIAS].([NIdReferenciaMaster]) (FK_SIR_60_REFERENCIAS_SIR_60_REFERENCIAS_nIdReferenciaMaster)
        /// </summary>
        public virtual SIR_Sir60Referencia SIR_Sir60Referencia1 { get; set; } // FK_SIR_60_REFERENCIAS_SIR_60_REFERENCIAS_nIdReferenciaMaster

        /// <summary>
        /// Parent SIR_Sir673SolicitudSed pointed by [SIR_60_REFERENCIAS].([NIdSolicitudSed673]) (FK_SIR_60_REFERENCIAS_SIR_673_SOLICITUD_SED)
        /// </summary>
        public virtual SIR_Sir673SolicitudSed SIR_Sir673SolicitudSed { get; set; } // FK_SIR_60_REFERENCIAS_SIR_673_SOLICITUD_SED

        /// <summary>
        /// Parent SIR_Sir67MtraSelecAleatoria pointed by [SIR_60_REFERENCIAS].([NIdMtraSelAle67]) (FK_SIR_60_REFERENCIAS_SIR_67_MTRA_SELEC_ALEATORIA)
        /// </summary>
        public virtual SIR_Sir67MtraSelecAleatoria SIR_Sir67MtraSelecAleatoria { get; set; } // FK_SIR_60_REFERENCIAS_SIR_67_MTRA_SELEC_ALEATORIA

        /// <summary>
        /// Parent SIR_Sir71SucursalPatenteAduana pointed by [SIR_60_REFERENCIAS].([NIdSucPatAdu71]) (FK_SIR_60_REFERENCIAS_SIR_71_SUCURSAL_PATENTE_ADUANA)
        /// </summary>
        public virtual SIR_Sir71SucursalPatenteAduana SIR_Sir71SucursalPatenteAduana { get; set; } // FK_SIR_60_REFERENCIAS_SIR_71_SUCURSAL_PATENTE_ADUANA

        /// <summary>
        /// Parent SIR_Sir73StatusReferencia pointed by [SIR_60_REFERENCIAS].([NIdStatus73]) (FK_SIR_60_REFERENCIAS_SIR_73_STATUS_REFERENCIAS)
        /// </summary>
        public virtual SIR_Sir73StatusReferencia SIR_Sir73StatusReferencia { get; set; } // FK_SIR_60_REFERENCIAS_SIR_73_STATUS_REFERENCIAS

        /// <summary>
        /// Parent SIR_Sir804EstatusReferencia pointed by [SIR_60_REFERENCIAS].([NIdEstatusRef804]) (FK_SIR_60_REFERENCIAS_ESTATUS_MERCANCIA)
        /// </summary>
        public virtual SIR_Sir804EstatusReferencia SIR_Sir804EstatusReferencia { get; set; } // FK_SIR_60_REFERENCIAS_ESTATUS_MERCANCIA

        /// <summary>
        /// Parent SIR_Sir80TiposMercancia pointed by [SIR_60_REFERENCIAS].([NIdTipoMerc80]) (FK_SIR_60_REFERENCIAS_SIR_80_TIPOS_MERCANCIA)
        /// </summary>
        public virtual SIR_Sir80TiposMercancia SIR_Sir80TiposMercancia { get; set; } // FK_SIR_60_REFERENCIAS_SIR_80_TIPOS_MERCANCIA

        /// <summary>
        /// Parent SIR_Sir86OrigenesDestino pointed by [SIR_60_REFERENCIAS].([NIdOriDes86]) (FK_SIR_60_REFERENCIAS_SIR_86_ORIGENES_DESTINOS)
        /// </summary>
        public virtual SIR_Sir86OrigenesDestino SIR_Sir86OrigenesDestino { get; set; } // FK_SIR_60_REFERENCIAS_SIR_86_ORIGENES_DESTINOS

        /// <summary>
        /// Parent SisTipRef pointed by [SIR_60_REFERENCIAS].([NIdTipoRef]) (FK_SIR_60_REFERENCIAS_sis_tip_ref)
        /// </summary>
        public virtual SisTipRef SisTipRef { get; set; } // FK_SIR_60_REFERENCIAS_sis_tip_ref

        public SIR_Sir60Referencia()
        {
            BExcluirCtaGastos = false;
            DFechaEdicion = System.DateTime.Now;
            NIdUsuarioEd = 0;
            NTipoCarga = 1;
            NIdTipoMerc80 = 1;
            NIdStatus73 = 0;
            NIdClienteFact = 0;
            BEsConsolidado = false;
            NSisOrigen = 1;
            NStatusVig = 1;
            BCapturaManual = false;
            BMercPeligrosa = false;
            BEsRectificacionExterna = false;
            BStatusRelConfronta = false;
            BNotifiEnviadaDom = false;
            Admin_Admino09DetallesPagoCliente = new System.Collections.Generic.List<Admin_Admino09DetallesPagoCliente>();
            Admin_Admino16DetallesCuentasGasto = new System.Collections.Generic.List<Admin_Admino16DetallesCuentasGasto>();
            Admin_Admino23DetallesLiquidacione = new System.Collections.Generic.List<Admin_Admino23DetallesLiquidacione>();
            SIR_Sir100FacPartAgrupada = new System.Collections.Generic.List<SIR_Sir100FacPartAgrupada>();
            SIR_Sir110DocumentosNoconforme = new System.Collections.Generic.List<SIR_Sir110DocumentosNoconforme>();
            SIR_Sir122SolCheqConcepto = new System.Collections.Generic.List<SIR_Sir122SolCheqConcepto>();
            SIR_Sir123Cotizacione = new System.Collections.Generic.List<SIR_Sir123Cotizacione>();
            SIR_Sir124Anticipos = new System.Collections.Generic.List<SIR_Sir124Anticipos>();
            SIR_Sir135CargaSueltaDetalle = new System.Collections.Generic.List<SIR_Sir135CargaSueltaDetalle>();
            SIR_Sir136TarifaMuellCalculo = new System.Collections.Generic.List<SIR_Sir136TarifaMuellCalculo>();
            SIR_Sir14Tinterterminale = new System.Collections.Generic.List<SIR_Sir14Tinterterminale>();
            SIR_Sir148OrdenesReferencia = new System.Collections.Generic.List<SIR_Sir148OrdenesReferencia>();
            SIR_Sir161ProgPreviosRef = new System.Collections.Generic.List<SIR_Sir161ProgPreviosRef>();
            SIR_Sir169SolicitudTransporte = new System.Collections.Generic.List<SIR_Sir169SolicitudTransporte>();
            SIR_Sir192ActividadesReferencia = new System.Collections.Generic.List<SIR_Sir192ActividadesReferencia>();
            SIR_Sir197Furgone = new System.Collections.Generic.List<SIR_Sir197Furgone>();
            SIR_Sir199BodegaServicio = new System.Collections.Generic.List<SIR_Sir199BodegaServicio>();
            SIR_Sir206Remesa = new System.Collections.Generic.List<SIR_Sir206Remesa>();
            SIR_Sir228RegistrosSagarpa = new System.Collections.Generic.List<SIR_Sir228RegistrosSagarpa>();
            SIR_Sir251ManifestacionesValor = new System.Collections.Generic.List<SIR_Sir251ManifestacionesValor>();
            SIR_Sir273Profepa = new System.Collections.Generic.List<SIR_Sir273Profepa>();
            SIR_Sir291SellosRecibido = new System.Collections.Generic.List<SIR_Sir291SellosRecibido>();
            SIR_Sir293ExtraccionPedimento_NIdRefOrigen = new System.Collections.Generic.List<SIR_Sir293ExtraccionPedimento>();
            SIR_Sir299ArchivosFactura = new System.Collections.Generic.List<SIR_Sir299ArchivosFactura>();
            SIR_Sir34ReferenciasCatPro = new System.Collections.Generic.List<SIR_Sir34ReferenciasCatPro>();
            SIR_Sir346SedDocument = new System.Collections.Generic.List<SIR_Sir346SedDocument>();
            SIR_Sir367CaracReferencia = new System.Collections.Generic.List<SIR_Sir367CaracReferencia>();
            SIR_Sir40ValCamposActividade = new System.Collections.Generic.List<SIR_Sir40ValCamposActividade>();
            SIR_Sir403EtapasReferencia = new System.Collections.Generic.List<SIR_Sir403EtapasReferencia>();
            SIR_Sir409ConfigVucem = new System.Collections.Generic.List<SIR_Sir409ConfigVucem>();
            SIR_Sir478NotificacionesBandeja = new System.Collections.Generic.List<SIR_Sir478NotificacionesBandeja>();
            SIR_Sir492DatosTarifa = new System.Collections.Generic.List<SIR_Sir492DatosTarifa>();
            SIR_Sir560PedimentoEdespacho = new System.Collections.Generic.List<SIR_Sir560PedimentoEdespacho>();
            SIR_Sir571CalculoAlmacenaje = new System.Collections.Generic.List<SIR_Sir571CalculoAlmacenaje>();
            SIR_Sir584BlIncidencia = new System.Collections.Generic.List<SIR_Sir584BlIncidencia>();
            SIR_Sir590ReferenciasSubdivision_NIdRefOriginal60 = new System.Collections.Generic.List<SIR_Sir590ReferenciasSubdivision>();
            SIR_Sir590ReferenciasSubdivision_NIdRefSubdivision60 = new System.Collections.Generic.List<SIR_Sir590ReferenciasSubdivision>();
            SIR_Sir60Referencia2 = new System.Collections.Generic.List<SIR_Sir60Referencia>();
            SIR_Sir626RevisionDocumental = new System.Collections.Generic.List<SIR_Sir626RevisionDocumental>();
            SIR_Sir63Documento = new System.Collections.Generic.List<SIR_Sir63Documento>();
            SIR_Sir635MonitorClasificacion = new System.Collections.Generic.List<SIR_Sir635MonitorClasificacion>();
            SIR_Sir646OrdenesDeTrabajo = new System.Collections.Generic.List<SIR_Sir646OrdenesDeTrabajo>();
            SIR_Sir681EtapasMonitorEjecutivoReferencia = new System.Collections.Generic.List<SIR_Sir681EtapasMonitorEjecutivoReferencia>();
            SIR_Sir695HistSubdivision_NIdReferenciaOrig60 = new System.Collections.Generic.List<SIR_Sir695HistSubdivision>();
            SIR_Sir695HistSubdivision_NIdReferenciaSub60 = new System.Collections.Generic.List<SIR_Sir695HistSubdivision>();
            SIR_Sir699GastoscompRef = new System.Collections.Generic.List<SIR_Sir699GastoscompRef>();
            SIR_Sir701RevisionDocumento = new System.Collections.Generic.List<SIR_Sir701RevisionDocumento>();
            SIR_Sir709AvisosEletronico = new System.Collections.Generic.List<SIR_Sir709AvisosEletronico>();
            SIR_Sir726BitacoraReferenciaCuentaAmericanaAx = new System.Collections.Generic.List<SIR_Sir726BitacoraReferenciaCuentaAmericanaAx>();
            SIR_Sir734BitacoraNotificacionPagoPedimento = new System.Collections.Generic.List<SIR_Sir734BitacoraNotificacionPagoPedimento>();
            SIR_Sir753ServiciosNoconforme = new System.Collections.Generic.List<SIR_Sir753ServiciosNoconforme>();
            SIR_Sir76Contenedore = new System.Collections.Generic.List<SIR_Sir76Contenedore>();
            SIR_Sir78ReferenciasObserv = new System.Collections.Generic.List<SIR_Sir78ReferenciasObserv>();
            SIR_Sir781ConsultaExpedienteCove = new System.Collections.Generic.List<SIR_Sir781ConsultaExpedienteCove>();
            SIR_Sir79ReferenciasBl = new System.Collections.Generic.List<SIR_Sir79ReferenciasBl>();
            SIR_Sir797NotificacionSirApp = new System.Collections.Generic.List<SIR_Sir797NotificacionSirApp>();
            SIR_Sir87SolicitudServicio = new System.Collections.Generic.List<SIR_Sir87SolicitudServicio>();
            SIR_Sir92ObservRefOperativa = new System.Collections.Generic.List<SIR_Sir92ObservRefOperativa>();
            SIR_Sir94PreBl = new System.Collections.Generic.List<SIR_Sir94PreBl>();
            SIRAdmin_Sira48DetalleProgServicio = new System.Collections.Generic.List<SIRAdmin_Sira48DetalleProgServicio>();
            SIRAdmin_Sira49LiberacionContenedor = new System.Collections.Generic.List<SIRAdmin_Sira49LiberacionContenedor>();
            SIRAdmin_Sira50Booking = new System.Collections.Generic.List<SIRAdmin_Sira50Booking>();
            SisRefRelDocs = new System.Collections.Generic.List<SisRefRelDoc>();
            SIR_Sir186OrdenesRemisione = new System.Collections.Generic.List<SIR_Sir186OrdenesRemisione>();
            SIR_Sir52Factura = new System.Collections.Generic.List<SIR_Sir52Factura>();
            SIR_Sir128PedidosCliente = new System.Collections.Generic.List<SIR_Sir128PedidosCliente>();
        }
    }

}
// </auto-generated>
