// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_647_DATOS_SERVICIOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir647DatosServicio
    {
        [Required]
        [Display(Name = "N ID datos servicio 647")]
        public int NIdDatosServicio647 { get; set; } // nIdDatosServicio647 (Primary key)

        [Required]
        [Display(Name = "N ID orden de trabajo servicio 656")]
        public int NIdOrdenDeTrabajoServicio656 { get; set; } // nIdOrdenDeTrabajoServicio656

        [Required]
        [Display(Name = "N ID caract servicio 643")]
        public int NIdCaractServicio643 { get; set; } // nIdCaractServicio643

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "S valor")]
        public string SValor { get; set; } // sValor (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent SIR_Sir643CaracteristicasServicio pointed by [SIR_647_DATOS_SERVICIOS].([NIdCaractServicio643]) ([FK_SIR_647_DATOS_SERVICIOS_SIR_643_CARACTERISTICAS_SERVICIOS)
        /// </summary>
        public virtual SIR_Sir643CaracteristicasServicio SIR_Sir643CaracteristicasServicio { get; set; } // [FK_SIR_647_DATOS_SERVICIOS_SIR_643_CARACTERISTICAS_SERVICIOS

        /// <summary>
        /// Parent SIR_Sir656OrdenTrabajoServicio pointed by [SIR_647_DATOS_SERVICIOS].([NIdOrdenDeTrabajoServicio656]) ([FK_SIR_647_DATOS_SERVICIOS_SIR_656_ORDEN_TRABAJO_SERVICIO)
        /// </summary>
        public virtual SIR_Sir656OrdenTrabajoServicio SIR_Sir656OrdenTrabajoServicio { get; set; } // [FK_SIR_647_DATOS_SERVICIOS_SIR_656_ORDEN_TRABAJO_SERVICIO
    }

}
// </auto-generated>
