// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_58_OBSERV_CONTENEDORES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir58ObservContenedoreConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir58ObservContenedore>
    {
        public SIR_Sir58ObservContenedoreConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir58ObservContenedoreConfiguration(string schema)
        {
            ToTable("SIR_58_OBSERV_CONTENEDORES", schema);
            HasKey(x => x.NIdContObserv58);

            Property(x => x.NIdContObserv58).HasColumnName(@"nIdContObserv58").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NSecuencia).HasColumnName(@"nSecuencia").HasColumnType("tinyint").IsRequired();
            Property(x => x.NIdContenedor76).HasColumnName(@"nIdContenedor76").HasColumnType("int").IsRequired();
            Property(x => x.NIdUsuario).HasColumnName(@"nIdUsuario").HasColumnType("int").IsOptional();
            Property(x => x.SObservacion).HasColumnName(@"sObservacion").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.DFecha).HasColumnName(@"dFecha").HasColumnType("smalldatetime").IsRequired();
            Property(x => x.DFechaEdicion).HasColumnName(@"dFechaEdicion").HasColumnType("datetime").IsRequired();
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsRequired();
            Property(x => x.NIdUsu01).HasColumnName(@"nIdUsu01").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Admin_Admina01Usuario).WithMany(b => b.SIR_Sir58ObservContenedore).HasForeignKey(c => c.NIdUsu01).WillCascadeOnDelete(false); // FK_SIR_58_OBSERV_CONTENEDORES_ADMINA_01_USUARIOS
            HasOptional(a => a.CatUsr_NIdUsuario).WithMany(b => b.SIR_Sir58ObservContenedore_NIdUsuario).HasForeignKey(c => c.NIdUsuario).WillCascadeOnDelete(false); // FK_SIR_58_OBSERV_CONTENEDORES_cat_usr
            HasRequired(a => a.CatUsr_NIdUsuarioEd).WithMany(b => b.SIR_Sir58ObservContenedore_NIdUsuarioEd).HasForeignKey(c => c.NIdUsuarioEd).WillCascadeOnDelete(false); // FK_SIR_58_OBSERV_CONTENEDORES_cat_usr_ed
            HasRequired(a => a.SIR_Sir76Contenedore).WithMany(b => b.SIR_Sir58ObservContenedore).HasForeignKey(c => c.NIdContenedor76); // FK_SIR_58_CONTENEDORES_OBSERV_SIR_76_CONTENEDORES
        }
    }

}
// </auto-generated>
