// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_218_RESPUESTA_VALIDACION
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir218RespuestaValidacionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir218RespuestaValidacion>
    {
        public SIR_Sir218RespuestaValidacionConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir218RespuestaValidacionConfiguration(string schema)
        {
            ToTable("SIR_218_RESPUESTA_VALIDACION", schema);
            HasKey(x => x.NIdArchRes218);

            Property(x => x.NIdArchRes218).HasColumnName(@"nIdArchRes218").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NIdArchM3216).HasColumnName(@"nIdArchM3216").HasColumnType("int").IsRequired();
            Property(x => x.SDescripcion).HasColumnName(@"sDescripcion").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(12);
            Property(x => x.SDirectorio).HasColumnName(@"sDirectorio").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
            Property(x => x.DFechaEdicion).HasColumnName(@"dFechaEdicion").HasColumnType("datetime").IsRequired();
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.CatUsr).WithMany(b => b.SIR_Sir218RespuestaValidacion).HasForeignKey(c => c.NIdUsuarioEd).WillCascadeOnDelete(false); // FK_SIR_218_RESPUESTA_VALIDACION_cat_usr_ed
            HasRequired(a => a.SIR_Sir216ArchivosPedimento).WithMany(b => b.SIR_Sir218RespuestaValidacion).HasForeignKey(c => c.NIdArchM3216).WillCascadeOnDelete(false); // FK_SIR_218_RESPUESTA_VALIDACION_SIR_216_ARCHIVOSM3
        }
    }

}
// </auto-generated>
