// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_372_CAAT_NAVIERAS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir372CaatNavieraConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir372CaatNaviera>
    {
        public SIR_Sir372CaatNavieraConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir372CaatNavieraConfiguration(string schema)
        {
            ToTable("SIR_372_CAAT_NAVIERAS", schema);
            HasKey(x => x.NIdCaatNavieras372);

            Property(x => x.NIdCaatNavieras372).HasColumnName(@"nIdCaatNavieras372").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SCaat).HasColumnName(@"sCAAT").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(4);
            Property(x => x.SRazonSocial).HasColumnName(@"sRazonSocial").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
        }
    }

}
// </auto-generated>
