// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_302_EJECUTIVOS_CLIENTES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir302EjecutivosCliente
    {
        [Required]
        [Display(Name = "N ID empleado")]
        public int NIdEmpleado { get; set; } // nIdEmpleado (Primary key via unique index UK_SIR_302_EJECUTIVOS_CLIENTES)

        [Display(Name = "N ID cliente")]
        public int? NIdCliente { get; set; } // nIdCliente

        [Display(Name = "N ID clie 07")]
        public int? NIdClie07 { get; set; } // nIdClie07

        [Display(Name = "N ID pers 02")]
        public int? NIdPers02 { get; set; } // nIdPers02

        // Foreign keys

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_302_EJECUTIVOS_CLIENTES].([NIdPers02]) (FK_SIR_302_EJECUTIVOS_CLIENTES_ADMINA_02_PERSONAL)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal { get; set; } // FK_SIR_302_EJECUTIVOS_CLIENTES_ADMINA_02_PERSONAL

        /// <summary>
        /// Parent Admin_Adminc07Cliente pointed by [SIR_302_EJECUTIVOS_CLIENTES].([NIdClie07]) (FK_SIR_302_EJECUTIVOS_CLIENTES_ADMINC_07_CLIENTES)
        /// </summary>
        public virtual Admin_Adminc07Cliente Admin_Adminc07Cliente { get; set; } // FK_SIR_302_EJECUTIVOS_CLIENTES_ADMINC_07_CLIENTES

        /// <summary>
        /// Parent CatCliente pointed by [SIR_302_EJECUTIVOS_CLIENTES].([NIdCliente]) (FK_SIR_302_EJECUTIVOS_CLIENTES_cat_clientes)
        /// </summary>
        public virtual CatCliente CatCliente { get; set; } // FK_SIR_302_EJECUTIVOS_CLIENTES_cat_clientes

        /// <summary>
        /// Parent CatEmp pointed by [SIR_302_EJECUTIVOS_CLIENTES].([NIdEmpleado]) (FK_SIR_302_EJECUTIVOS_CLIENTES_cat_emp)
        /// </summary>
        public virtual CatEmp CatEmp { get; set; } // FK_SIR_302_EJECUTIVOS_CLIENTES_cat_emp
    }

}
// </auto-generated>
