// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // The table 'SIR_728_PARTE_PERMISO_ADUANA' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // SIR_728_PARTE_PERMISO_ADUANA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir728PartePermisoAduana
    {
        [Display(Name = "N ID parte 99")]
        public int? NIdParte99 { get; set; } // nIdParte99

        [Display(Name = "N ID adu sec 06")]
        public int? NIdAduSec06 { get; set; } // nIdAduSec06

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "S registro")]
        public string SRegistro { get; set; } // sRegistro (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent SIR_Sir06AduanaSec pointed by [SIR_728_PARTE_PERMISO_ADUANA].([NIdAduSec06]) (FK_SIR_728_PARTE_PERMISO_ADUANA_SIR_06_ADUANA_SEC)
        /// </summary>
        public virtual SIR_Sir06AduanaSec SIR_Sir06AduanaSec { get; set; } // FK_SIR_728_PARTE_PERMISO_ADUANA_SIR_06_ADUANA_SEC

        /// <summary>
        /// Parent SIR_Sir99Parte pointed by [SIR_728_PARTE_PERMISO_ADUANA].([NIdParte99]) (FK_SIR_728_PARTE_PERMISO_ADUANA_SIR_99_PARTES)
        /// </summary>
        public virtual SIR_Sir99Parte SIR_Sir99Parte { get; set; } // FK_SIR_728_PARTE_PERMISO_ADUANA_SIR_99_PARTES
    }

}
// </auto-generated>
