// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_380_CONFIDENCIAL_SISTEMA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir380ConfidencialSistemaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir380ConfidencialSistema>
    {
        public SIR_Sir380ConfidencialSistemaConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir380ConfidencialSistemaConfiguration(string schema)
        {
            ToTable("SIR_380_CONFIDENCIAL_SISTEMA", schema);
            HasKey(x => x.NIdConfidencialSistema380);

            Property(x => x.NIdConfidencialSistema380).HasColumnName(@"nIdConfidencialSistema380").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NTipoBloqueo).HasColumnName(@"nTipoBloqueo").HasColumnType("tinyint").IsRequired();
            Property(x => x.DFecha).HasColumnName(@"dFecha").HasColumnType("datetime").IsRequired();
            Property(x => x.SMensaje).HasColumnName(@"sMensaje").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.NAviso).HasColumnName(@"nAviso").HasColumnType("int").IsOptional();
            Property(x => x.SPatente).HasColumnName(@"sPatente").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(4);
            Property(x => x.SAduana).HasColumnName(@"sAduana").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(2);
        }
    }

}
// </auto-generated>
