// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_55_FACTURAS_INCREMENTABLES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir55FacturasIncrementableConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir55FacturasIncrementable>
    {
        public SIR_Sir55FacturasIncrementableConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir55FacturasIncrementableConfiguration(string schema)
        {
            ToTable("SIR_55_FACTURAS_INCREMENTABLES", schema);
            HasKey(x => x.NIdFacturaInc55);

            Property(x => x.NIdFacturaInc55).HasColumnName(@"nIdFacturaInc55").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NIdFactura52).HasColumnName(@"nIdFactura52").HasColumnType("int").IsRequired();
            Property(x => x.NIdTipoIncrementable54).HasColumnName(@"nIdTipoIncrementable54").HasColumnType("int").IsRequired();
            Property(x => x.NIdMoneda03).HasColumnName(@"nIdMoneda03").HasColumnType("int").IsOptional();
            Property(x => x.NMonto).HasColumnName(@"nMonto").HasColumnType("decimal").IsRequired().HasPrecision(12,3);
            Property(x => x.DFechaEdicion).HasColumnName(@"dFechaEdicion").HasColumnType("datetime").IsRequired();
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsRequired();

            // Foreign keys
            HasOptional(a => a.SIR_Sir03Moneda).WithMany(b => b.SIR_Sir55FacturasIncrementable).HasForeignKey(c => c.NIdMoneda03).WillCascadeOnDelete(false); // FK_SIR_55_FACTURAS_INCREMENTABLES_SIR_03_MONEDAS
            HasRequired(a => a.CatUsr).WithMany(b => b.SIR_Sir55FacturasIncrementable).HasForeignKey(c => c.NIdUsuarioEd).WillCascadeOnDelete(false); // FK_SIR_55_FACTURAS_INCREMENTABLES_cat_usr_ed
            HasRequired(a => a.SIR_Sir52Factura).WithMany(b => b.SIR_Sir55FacturasIncrementable).HasForeignKey(c => c.NIdFactura52); // FK_SIR_55_FACTURAS_INCREMENTABLES_SIR_52_FACTURAS
            HasRequired(a => a.SIR_Sir54TipoIncrementable).WithMany(b => b.SIR_Sir55FacturasIncrementable).HasForeignKey(c => c.NIdTipoIncrementable54).WillCascadeOnDelete(false); // FK_SIR_55_FACTURAS_INCREMENTABLES_SIR_54_TIPO_INCREMENTABLES
        }
    }

}
// </auto-generated>
