// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_71_SUCURSAL_PATENTE_ADUANA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir71SucursalPatenteAduanaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir71SucursalPatenteAduana>
    {
        public SIR_Sir71SucursalPatenteAduanaConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir71SucursalPatenteAduanaConfiguration(string schema)
        {
            ToTable("SIR_71_SUCURSAL_PATENTE_ADUANA", schema);
            HasKey(x => x.NIdSucPatAdu71);

            Property(x => x.NIdSucPatAdu71).HasColumnName(@"nIdSucPatAdu71").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NIdSucursal).HasColumnName(@"nIdSucursal").HasColumnType("int").IsOptional();
            Property(x => x.NIdPatente70).HasColumnName(@"nIdPatente70").HasColumnType("int").IsRequired();
            Property(x => x.NIdAduSec06).HasColumnName(@"nIdAduSec06").HasColumnType("int").IsRequired();
            Property(x => x.NGrupoAduana).HasColumnName(@"nGrupoAduana").HasColumnType("tinyint").IsRequired();
            Property(x => x.DFechaEdicion).HasColumnName(@"dFechaEdicion").HasColumnType("datetime").IsRequired();
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsRequired();
            Property(x => x.BUtilizaFox).HasColumnName(@"bUtilizaFox").HasColumnType("bit").IsRequired();
            Property(x => x.NIdSuc12).HasColumnName(@"nIdSuc12").HasColumnType("int").IsOptional();
            Property(x => x.NIdSucPatAdu71Ext).HasColumnName(@"nIdSucPatAdu71Ext").HasColumnType("int").IsOptional();
            Property(x => x.SAcronimo).HasColumnName(@"sAcronimo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.BSucursalMasterBodega).HasColumnName(@"bSucursalMasterBodega").HasColumnType("bit").IsOptional();
            HasMany(t => t.SIRWEB_Sw06UsuarioWebaccess).WithMany(t => t.SIR_Sir71SucursalPatenteAduana).Map(m =>
            {
                m.ToTable("SW_07_USUARIO_WEBACCESS_SUCPATADU", "SIRWEB");
                m.MapLeftKey("nIdSucPatAdu71");
                m.MapRightKey("nIdUsuarioWA06");
            });
        }
    }

}
// </auto-generated>
