// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_353_FRACCIONES_AMERICANAS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir353FraccionesAmericanaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir353FraccionesAmericana>
    {
        public SIR_Sir353FraccionesAmericanaConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir353FraccionesAmericanaConfiguration(string schema)
        {
            ToTable("SIR_353_FRACCIONES_AMERICANAS", schema);
            HasKey(x => x.NIdFraccionAme353);

            Property(x => x.NIdFraccionAme353).HasColumnName(@"nIdFraccionAme353").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NIdParte99).HasColumnName(@"nIdParte99").HasColumnType("int").IsRequired();
            Property(x => x.NIdCodigoExportacion334).HasColumnName(@"nIdCodigoExportacion334").HasColumnType("int").IsOptional();
            Property(x => x.NIdPrimeraUm333).HasColumnName(@"nIdPrimeraUM333").HasColumnType("int").IsOptional();
            Property(x => x.NIdSegundaUm33).HasColumnName(@"nIdSegundaUM33").HasColumnType("int").IsOptional();
            Property(x => x.NIdTipoLicencia335).HasColumnName(@"nIdTipoLicencia335").HasColumnType("int").IsOptional();
            Property(x => x.SNumeroLicencia).HasColumnName(@"sNumeroLicencia").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(12);
            Property(x => x.SFraccionAme).HasColumnName(@"sFraccionAme").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            Property(x => x.SDescripcion).HasColumnName(@"sDescripcion").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.SEccn).HasColumnName(@"sECCN").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(5);
            Property(x => x.NOrigen).HasColumnName(@"nOrigen").HasColumnType("tinyint").IsRequired();
            Property(x => x.NIdDdtcNumExencion332).HasColumnName(@"nIdDDTCNumExencion332").HasColumnType("int").IsOptional();
            Property(x => x.SDdtcNumRegistro).HasColumnName(@"sDDTCNumRegistro").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(6);
            Property(x => x.NDdtcEquipoMilitar).HasColumnName(@"nDDTCEquipoMilitar").HasColumnType("tinyint").IsRequired();
            Property(x => x.NDdtcCertificacion).HasColumnName(@"nDDTCCertificacion").HasColumnType("tinyint").IsRequired();
            Property(x => x.NIdDdtcCategoriaUsml331).HasColumnName(@"nIdDDTCCategoriaUSML331").HasColumnType("int").IsOptional();
            Property(x => x.NIdDdtcUnidadMedida330).HasColumnName(@"nIdDDTCUnidadMedida330").HasColumnType("int").IsOptional();
            Property(x => x.NTipoFraccion).HasColumnName(@"nTipoFraccion").HasColumnType("tinyint").IsRequired();

            // Foreign keys
            HasOptional(a => a.SIR_Sir330SedDdtcUnitsMeasure).WithMany(b => b.SIR_Sir353FraccionesAmericana).HasForeignKey(c => c.NIdDdtcUnidadMedida330).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_330_SED_DDTC_UNITS_MEASURE
            HasOptional(a => a.SIR_Sir331SedDdtcCategoRy).WithMany(b => b.SIR_Sir353FraccionesAmericana).HasForeignKey(c => c.NIdDdtcCategoriaUsml331).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_331_SED_DDTC_CATEGORIES
            HasOptional(a => a.SIR_Sir332SedDdtcExemption).WithMany(b => b.SIR_Sir353FraccionesAmericana).HasForeignKey(c => c.NIdDdtcNumExencion332).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_332_SED_DDTC_EXEMPTIONS
            HasOptional(a => a.SIR_Sir333SedUnitsMeasure_NIdPrimeraUm333).WithMany(b => b.SIR_Sir353FraccionesAmericana_NIdPrimeraUm333).HasForeignKey(c => c.NIdPrimeraUm333).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_333_SED_UNITS_MEASURE_sPrimeraUM333
            HasOptional(a => a.SIR_Sir333SedUnitsMeasure_NIdSegundaUm33).WithMany(b => b.SIR_Sir353FraccionesAmericana_NIdSegundaUm33).HasForeignKey(c => c.NIdSegundaUm33).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_333_SED_UNITS_MEASURE_sSegundaUM33
            HasOptional(a => a.SIR_Sir334SedExportInformation).WithMany(b => b.SIR_Sir353FraccionesAmericana).HasForeignKey(c => c.NIdCodigoExportacion334).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_334_SED_EXPORT_INFORMATION
            HasOptional(a => a.SIR_Sir335SedLicense).WithMany(b => b.SIR_Sir353FraccionesAmericana).HasForeignKey(c => c.NIdTipoLicencia335).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_335_SED_LICENSES
            HasRequired(a => a.SIR_Sir99Parte).WithMany(b => b.SIR_Sir353FraccionesAmericana).HasForeignKey(c => c.NIdParte99).WillCascadeOnDelete(false); // FK_SIR_353_FRACCIONES_AMERICANAS_SIR_99_PARTES
        }
    }

}
// </auto-generated>
