// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_427_PARTES_IMPUESTOS_HISTORICO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir427PartesImpuestosHistorico
    {
        [Required]
        [Display(Name = "N ID historico parte 413")]
        public int NIdHistoricoParte413 { get; set; } // nIdHistoricoParte413 (Primary key)

        [Required]
        [Display(Name = "N ID tipos imp 30")]
        public int NIdTiposImp30 { get; set; } // nIdTiposImp30 (Primary key)

        [Display(Name = "N valor tasa")]
        public decimal? NValorTasa { get; set; } // nValorTasa

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "D fecha edicion")]
        public System.DateTime DFechaEdicion { get; set; } // dFechaEdicion (Primary key)

        [Required]
        [Display(Name = "N ID usuario ed")]
        public int NIdUsuarioEd { get; set; } // nIdUsuarioEd (Primary key)
    }

}
// </auto-generated>
