// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_361_CARAC_ENTRADA_BODEGA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir361CaracEntradaBodega
    {
        [Required]
        [Display(Name = "N ID carac eb 361")]
        public int NIdCaracEb361 { get; set; } // nIdCaracEB361 (Primary key)

        [Required]
        [Display(Name = "N ID carac 130")]
        public int NIdCarac130 { get; set; } // nIdCarac130

        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "S valor")]
        public string SValor { get; set; } // sValor (length: 500)

        [Required]
        [Display(Name = "N ID entrada 156")]
        public int NIdEntrada156 { get; set; } // nIdEntrada156

        // Foreign keys

        /// <summary>
        /// Parent SIR_Sir130Caracteristica pointed by [SIR_361_CARAC_ENTRADA_BODEGA].([NIdCarac130]) (FK_SIR_361_CARAC_ENTRADA_BODEGA_SIR_130_CARACTERISTICAS)
        /// </summary>
        public virtual SIR_Sir130Caracteristica SIR_Sir130Caracteristica { get; set; } // FK_SIR_361_CARAC_ENTRADA_BODEGA_SIR_130_CARACTERISTICAS

        /// <summary>
        /// Parent SIR_Sir156EntradasBodega pointed by [SIR_361_CARAC_ENTRADA_BODEGA].([NIdEntrada156]) (FK_SIR_361_CARAC_ENTRADA_BODEGA_SIR_156_ENTRADAS_BODEGAS)
        /// </summary>
        public virtual SIR_Sir156EntradasBodega SIR_Sir156EntradasBodega { get; set; } // FK_SIR_361_CARAC_ENTRADA_BODEGA_SIR_156_ENTRADAS_BODEGAS
    }

}
// </auto-generated>
