// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_679_CLIENTE_MONITOR_EJECUTIVO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir679ClienteMonitorEjecutivo
    {
        [Required]
        [Display(Name = "N ID cliente monitor ejecutivo 679")]
        public int NIdClienteMonitorEjecutivo679 { get; set; } // nIdClienteMonitorEjecutivo679 (Primary key)

        [Display(Name = "N ID cliente")]
        public int? NIdCliente { get; set; } // nIdCliente

        [Display(Name = "N ID clie 07")]
        public int? NIdClie07 { get; set; } // nIdClie07

        [Required]
        [Display(Name = "N tipo vista")]
        public byte NTipoVista { get; set; } // nTipoVista

        [Required]
        [Display(Name = "B permiso monitor ejecutivo")]
        public bool BPermisoMonitorEjecutivo { get; set; } // bPermisoMonitorEjecutivo

        [Display(Name = "B permiso cotizador")]
        public bool? BPermisoCotizador { get; set; } // bPermisoCotizador

        // Foreign keys

        /// <summary>
        /// Parent CatCliente pointed by [SIR_679_CLIENTE_MONITOR_EJECUTIVO].([NIdCliente]) (FK_SIR_679_CLIENTE_MONITOR_EJECUTIVO_cat_clientes)
        /// </summary>
        public virtual CatCliente CatCliente { get; set; } // FK_SIR_679_CLIENTE_MONITOR_EJECUTIVO_cat_clientes
    }

}
// </auto-generated>
