// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_630_INSPECCION_FISICA_SAGARPA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir630InspeccionFisicaSagarpaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir630InspeccionFisicaSagarpa>
    {
        public SIR_Sir630InspeccionFisicaSagarpaConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir630InspeccionFisicaSagarpaConfiguration(string schema)
        {
            ToTable("SIR_630_INSPECCION_FISICA_SAGARPA", schema);
            HasKey(x => x.NIdRevisionDocumental626);

            Property(x => x.NIdRevisionDocumental626).HasColumnName(@"nIdRevisionDocumental626").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SCertificadoAutorizado).HasColumnName(@"sCertificadoAutorizado").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.DInspeccion).HasColumnName(@"dInspeccion").HasColumnType("datetime").IsOptional();
            Property(x => x.SNombreInspector).HasColumnName(@"sNombreInspector").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.SApellidoPaternoInspector).HasColumnName(@"sApellidoPaternoInspector").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.SApellidoMaternoInspector).HasColumnName(@"sApellidoMaternoInspector").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.NCantidadCarrosFerrocarril).HasColumnName(@"nCantidadCarrosFerrocarril").HasColumnType("int").IsOptional();
            Property(x => x.NCantidadDeGuiasAmparadas).HasColumnName(@"nCantidadDeGuiasAmparadas").HasColumnType("int").IsOptional();
            Property(x => x.SNumeroDeOperacion).HasColumnName(@"sNumeroDeOperacion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(14);
            Property(x => x.NTipoInspeccionFisicaFerroviaria).HasColumnName(@"nTipoInspeccionFisicaFerroviaria").HasColumnType("int").IsOptional();
            Property(x => x.SFolio).HasColumnName(@"sFolio").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsOptional();
            Property(x => x.DEdicion).HasColumnName(@"dEdicion").HasColumnType("datetime").IsOptional();
            Property(x => x.NIdFiguraLegal).HasColumnName(@"nIdFiguraLegal").HasColumnType("int").IsOptional();
            Property(x => x.NTipoFigura).HasColumnName(@"nTipoFigura").HasColumnType("tinyint").IsOptional();

            // Foreign keys
            HasOptional(a => a.CatEmp).WithMany(b => b.SIR_Sir630InspeccionFisicaSagarpa).HasForeignKey(c => c.NIdFiguraLegal).WillCascadeOnDelete(false); // FK_SIR_630_INSPECCION_FISICA_SAGARPA_cat_emp
            HasRequired(a => a.SIR_Sir626RevisionDocumental).WithOptional(b => b.SIR_Sir630InspeccionFisicaSagarpa).WillCascadeOnDelete(false); // FK_SIR_630_INSPECCION_FISICA_SAGARPA_SIR_626_REVISION_DOCUMENTAL
        }
    }

}
// </auto-generated>
