// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_120_SOLICITUD_CHEQUES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir120SolicitudCheque
    {
        [Required]
        [Display(Name = "N ID sol cheque 120")]
        public int NIdSolCheque120 { get; set; } // nIdSolCheque120 (Primary key)

        [Required]
        [Display(Name = "N folio")]
        public int NFolio { get; set; } // nFolio

        [Required]
        [Display(Name = "D fecha alta")]
        public System.DateTime DFechaAlta { get; set; } // dFechaAlta

        [Required]
        [Display(Name = "N tipo")]
        public byte NTipo { get; set; } // nTipo

        [Display(Name = "N ID empleado")]
        public int? NIdEmpleado { get; set; } // nIdEmpleado

        [Display(Name = "N ID proveedor")]
        public int? NIdProveedor { get; set; } // nIdProveedor

        [Display(Name = "N ID moneda prov")]
        public int? NIdMonedaProv { get; set; } // nIdMonedaProv

        [Display(Name = "N ID ejecutivo")]
        public int? NIdEjecutivo { get; set; } // nIdEjecutivo

        [Display(Name = "N ID prov giro")]
        public int? NIdProvGiro { get; set; } // nIdProvGiro

        [Display(Name = "N ID autoriza")]
        public int? NIdAutoriza { get; set; } // nIdAutoriza

        [Display(Name = "D fecha autoriza")]
        public System.DateTime? DFechaAutoriza { get; set; } // dFechaAutoriza

        [Display(Name = "N ID autoriza extra")]
        public int? NIdAutorizaExtra { get; set; } // nIdAutorizaExtra

        [Required]
        [Display(Name = "N status")]
        public byte NStatus { get; set; } // nStatus

        [Display(Name = "D fecha solicitud")]
        public System.DateTime? DFechaSolicitud { get; set; } // dFechaSolicitud

        [Display(Name = "D fecha rechazo")]
        public System.DateTime? DFechaRechazo { get; set; } // dFechaRechazo

        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "S motivo rechazo")]
        public string SMotivoRechazo { get; set; } // sMotivoRechazo (length: 500)

        [Display(Name = "N ID solicita")]
        public int? NIdSolicita { get; set; } // nIdSolicita

        [Display(Name = "N ID rechaza")]
        public int? NIdRechaza { get; set; } // nIdRechaza

        [Display(Name = "N ID cancela")]
        public int? NIdCancela { get; set; } // nIdCancela

        [Display(Name = "D fecha cancela")]
        public System.DateTime? DFechaCancela { get; set; } // dFechaCancela

        [Required]
        [Display(Name = "B permite carta")]
        public bool BPermiteCarta { get; set; } // bPermiteCarta

        [Display(Name = "N ID suc pat adu 71")]
        public int? NIdSucPatAdu71 { get; set; } // nIdSucPatAdu71

        [Required]
        [Display(Name = "B por comprobar")]
        public bool BPorComprobar { get; set; } // bPorComprobar

        [Required]
        [Display(Name = "B es deposito")]
        public bool BEsDeposito { get; set; } // bEsDeposito

        [Display(Name = "N ID deudor")]
        public int? NIdDeudor { get; set; } // nIdDeudor

        [Display(Name = "N ID empleado adm")]
        public int? NIdEmpleadoAdm { get; set; } // nIdEmpleadoAdm

        [Display(Name = "N ID proveedor adm")]
        public int? NIdProveedorAdm { get; set; } // nIdProveedorAdm

        [Display(Name = "N ID moneda prov adm")]
        public int? NIdMonedaProvAdm { get; set; } // nIdMonedaProvAdm

        [Display(Name = "N ID ejecutivo adm")]
        public int? NIdEjecutivoAdm { get; set; } // nIdEjecutivoAdm

        [Display(Name = "N ID autoriza adm")]
        public int? NIdAutorizaAdm { get; set; } // nIdAutorizaAdm

        [Display(Name = "N ID prov giro adm")]
        public int? NIdProvGiroAdm { get; set; } // nIdProvGiroAdm

        [Display(Name = "N ID autoriza extra adm")]
        public int? NIdAutorizaExtraAdm { get; set; } // nIdAutorizaExtraAdm

        [Display(Name = "N ID solicita adm")]
        public int? NIdSolicitaAdm { get; set; } // nIdSolicitaAdm

        [Display(Name = "N ID rechaza adm")]
        public int? NIdRechazaAdm { get; set; } // nIdRechazaAdm

        [Display(Name = "N ID cancela adm")]
        public int? NIdCancelaAdm { get; set; } // nIdCancelaAdm

        [Display(Name = "N ID elabora adm")]
        public int? NIdElaboraAdm { get; set; } // nIdElaboraAdm

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "S formade pago")]
        public string SFormadePago { get; set; } // sFormadePago (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "S ID foraneo")]
        public string SIdForaneo { get; set; } // sIdForaneo (length: 100)

        [DataType(DataType.DateTime)]
        [Display(Name = "D fecha elaboracion")]
        public System.DateTime? DFechaElaboracion { get; set; } // dFechaElaboracion

        // Reverse navigation

        /// <summary>
        /// Child SIR_Sir121SolCheqObserv where [SIR_121_SOL_CHEQ_OBSERV].[nIdSolCheque120] point to this entity (FK_SIR_121_SOL_CHEQ_OBSERV_SIR_120_SOLICITUD_CHEQUES)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir121SolCheqObserv> SIR_Sir121SolCheqObserv { get; set; } // SIR_121_SOL_CHEQ_OBSERV.FK_SIR_121_SOL_CHEQ_OBSERV_SIR_120_SOLICITUD_CHEQUES
        /// <summary>
        /// Child SIR_Sir122SolCheqConcepto where [SIR_122_SOL_CHEQ_CONCEPTOS].[nIdSolCheque120] point to this entity (FK_SIR_122_SOL_CHEQ_CONCEPTOS_SIR_120_SOLICITUD_CHEQUES)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir122SolCheqConcepto> SIR_Sir122SolCheqConcepto { get; set; } // SIR_122_SOL_CHEQ_CONCEPTOS.FK_SIR_122_SOL_CHEQ_CONCEPTOS_SIR_120_SOLICITUD_CHEQUES
        /// <summary>
        /// Child SIR_Sir136TarifaMuellCalculo where [SIR_136_TARIFA_MUELL_CALCULO].[nIdSolicitud120] point to this entity (FK_SIR_136_TARIFA_MUELL_CALCULO_SIR_120_SOLICITUD_CHEQUES)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir136TarifaMuellCalculo> SIR_Sir136TarifaMuellCalculo { get; set; } // SIR_136_TARIFA_MUELL_CALCULO.FK_SIR_136_TARIFA_MUELL_CALCULO_SIR_120_SOLICITUD_CHEQUES

        // Foreign keys

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdAutorizaAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Autoriza)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdAutorizaAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Autoriza

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdAutorizaExtraAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_AutorizaExtra)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdAutorizaExtraAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_AutorizaExtra

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdCancelaAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Cancela)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdCancelaAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Cancela

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdEjecutivoAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Ejecutivo)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdEjecutivoAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Ejecutivo

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdElaboraAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Elabora)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdElaboraAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Elabora

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdEmpleadoAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Empleado)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdEmpleadoAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Empleado

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdRechazaAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Rechaza)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdRechazaAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Rechaza

        /// <summary>
        /// Parent Admin_Admina02Personal pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdSolicitaAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Solicita)
        /// </summary>
        public virtual Admin_Admina02Personal Admin_Admina02Personal_NIdSolicitaAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINA_02_PERSONAL_Solicita

        /// <summary>
        /// Parent Admin_Adminc03Moneda pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdMonedaProvAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINC_03_MONEDAS)
        /// </summary>
        public virtual Admin_Adminc03Moneda Admin_Adminc03Moneda { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINC_03_MONEDAS

        /// <summary>
        /// Parent Admin_Adminc42Proveedore pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdProveedorAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINC_42_PROVEEDORES_Prov)
        /// </summary>
        public virtual Admin_Adminc42Proveedore Admin_Adminc42Proveedore_NIdProveedorAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINC_42_PROVEEDORES_Prov

        /// <summary>
        /// Parent Admin_Adminc42Proveedore pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdProvGiroAdm]) (FK_SIR_120_SOLICITUD_CHEQUES_ADMINC_42_PROVEEDORES_ProvGiro)
        /// </summary>
        public virtual Admin_Adminc42Proveedore Admin_Adminc42Proveedore_NIdProvGiroAdm { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_ADMINC_42_PROVEEDORES_ProvGiro

        /// <summary>
        /// Parent BcoCuenta pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdDeudor]) (FK_SIR_120_SOLICITUD_CHEQUES_bco_cuentas)
        /// </summary>
        public virtual BcoCuenta BcoCuenta { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_bco_cuentas

        /// <summary>
        /// Parent CatEmp pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdAutoriza]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_emp1)
        /// </summary>
        public virtual CatEmp CatEmp_NIdAutoriza { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_emp1

        /// <summary>
        /// Parent CatEmp pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdAutorizaExtra]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_emp2)
        /// </summary>
        public virtual CatEmp CatEmp_NIdAutorizaExtra { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_emp2

        /// <summary>
        /// Parent CatEmp pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdCancela]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_emp6)
        /// </summary>
        public virtual CatEmp CatEmp_NIdCancela { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_emp6

        /// <summary>
        /// Parent CatEmp pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdEjecutivo]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_emp3)
        /// </summary>
        public virtual CatEmp CatEmp_NIdEjecutivo { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_emp3

        /// <summary>
        /// Parent CatEmp pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdEmpleado]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_emp)
        /// </summary>
        public virtual CatEmp CatEmp_NIdEmpleado { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_emp

        /// <summary>
        /// Parent CatEmp pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdRechaza]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_emp5)
        /// </summary>
        public virtual CatEmp CatEmp_NIdRechaza { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_emp5

        /// <summary>
        /// Parent CatEmp pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdSolicita]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_emp4)
        /// </summary>
        public virtual CatEmp CatEmp_NIdSolicita { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_emp4

        /// <summary>
        /// Parent CatProv pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdEjecutivo]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_prov1)
        /// </summary>
        public virtual CatProv CatProv_NIdEjecutivo { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_prov1

        /// <summary>
        /// Parent CatProv pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdProveedor]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_prov)
        /// </summary>
        public virtual CatProv CatProv_NIdProveedor { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_prov

        /// <summary>
        /// Parent CatProv pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdProvGiro]) (FK_SIR_120_SOLICITUD_CHEQUES_cat_prov2)
        /// </summary>
        public virtual CatProv CatProv_NIdProvGiro { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_cat_prov2

        /// <summary>
        /// Parent MonMoneda pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdMonedaProv]) (FK_SIR_120_SOLICITUD_CHEQUES_mon_monedas)
        /// </summary>
        public virtual MonMoneda MonMoneda { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_mon_monedas

        /// <summary>
        /// Parent SIR_Sir71SucursalPatenteAduana pointed by [SIR_120_SOLICITUD_CHEQUES].([NIdSucPatAdu71]) (FK_SIR_120_SOLICITUD_CHEQUES_SIR_71_SUCURSAL_PATENTE_ADUANA)
        /// </summary>
        public virtual SIR_Sir71SucursalPatenteAduana SIR_Sir71SucursalPatenteAduana { get; set; } // FK_SIR_120_SOLICITUD_CHEQUES_SIR_71_SUCURSAL_PATENTE_ADUANA

        public SIR_Sir120SolicitudCheque()
        {
            BPermiteCarta = false;
            BEsDeposito = false;
            SIR_Sir121SolCheqObserv = new System.Collections.Generic.List<SIR_Sir121SolCheqObserv>();
            SIR_Sir122SolCheqConcepto = new System.Collections.Generic.List<SIR_Sir122SolCheqConcepto>();
            SIR_Sir136TarifaMuellCalculo = new System.Collections.Generic.List<SIR_Sir136TarifaMuellCalculo>();
        }
    }

}
// </auto-generated>
