// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIR_82_MUELLAJES_CLIENTES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIR_Sir82MuellajesClienteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIR_Sir82MuellajesCliente>
    {
        public SIR_Sir82MuellajesClienteConfiguration()
            : this("SIR")
        {
        }

        public SIR_Sir82MuellajesClienteConfiguration(string schema)
        {
            ToTable("SIR_82_MUELLAJES_CLIENTES", schema);
            HasKey(x => x.NIdMuellClie82);

            Property(x => x.NIdMuellClie82).HasColumnName(@"nIdMuellClie82").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NIdRecinto).HasColumnName(@"nIdRecinto").HasColumnType("int").IsRequired();
            Property(x => x.DFecha).HasColumnName(@"dFecha").HasColumnType("smalldatetime").IsRequired();
            Property(x => x.NIdCliente).HasColumnName(@"nIdCliente").HasColumnType("int").IsRequired();
            Property(x => x.NTarifaImpo).HasColumnName(@"nTarifaImpo").HasColumnType("decimal").IsOptional().HasPrecision(12,2);
            Property(x => x.NTarifaExpo).HasColumnName(@"nTarifaExpo").HasColumnType("decimal").IsOptional().HasPrecision(12,2);
            Property(x => x.DFechaEdicion).HasColumnName(@"dFechaEdicion").HasColumnType("datetime").IsRequired();
            Property(x => x.NIdUsuarioEd).HasColumnName(@"nIdUsuarioEd").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.CatCliente).WithMany(b => b.SIR_Sir82MuellajesCliente).HasForeignKey(c => c.NIdCliente).WillCascadeOnDelete(false); // FK_SIR_82_MUELLAJES_CLIENTES_cat_clientes
            HasRequired(a => a.CatProv).WithMany(b => b.SIR_Sir82MuellajesCliente).HasForeignKey(c => c.NIdRecinto).WillCascadeOnDelete(false); // FK_SIR_82_MUELLAJES_CLIENTES_cat_prov
            HasRequired(a => a.CatUsr).WithMany(b => b.SIR_Sir82MuellajesCliente).HasForeignKey(c => c.NIdUsuarioEd).WillCascadeOnDelete(false); // FK_SIR_82_MUELLAJES_CLIENTES_cat_usr_ed
        }
    }

}
// </auto-generated>
