// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIRA_21_FUNCIONES_USUARIOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIRAdmin_Sira21FuncionesUsuarioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIRAdmin_Sira21FuncionesUsuario>
    {
        public SIRAdmin_Sira21FuncionesUsuarioConfiguration()
            : this("SIRAdmin")
        {
        }

        public SIRAdmin_Sira21FuncionesUsuarioConfiguration(string schema)
        {
            ToTable("SIRA_21_FUNCIONES_USUARIOS", schema);
            HasKey(x => x.NIdFuncion20);

            Property(x => x.NIdFuncion20).HasColumnName(@"nIdFuncion20").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NIdUsuario).HasColumnName(@"nIdUsuario").HasColumnType("int").IsOptional();
            Property(x => x.NIdUsu01).HasColumnName(@"nIdUsu01").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Admin_Admina01Usuario).WithMany(b => b.SIRAdmin_Sira21FuncionesUsuario).HasForeignKey(c => c.NIdUsu01).WillCascadeOnDelete(false); // FK_SIRA_21_FUNCIONES_USUARIOS_ADMINA_01_USUARIOS
            HasOptional(a => a.CatUsr).WithMany(b => b.SIRAdmin_Sira21FuncionesUsuario).HasForeignKey(c => c.NIdUsuario).WillCascadeOnDelete(false); // FK_SIRA_21_FUNCIONES_USUARIOS_cat_usr
            HasRequired(a => a.SIRAdmin_Sira20Funcione).WithOptional(b => b.SIRAdmin_Sira21FuncionesUsuario).WillCascadeOnDelete(false); // FK_SIRA_21_FUNCIONES_USUARIOS_SIRA_20_FUNCIONES
        }
    }

}
// </auto-generated>
