// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIRA_14_CONTROLES_PROPIEDADES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIRAdmin_Sira14ControlesPropiedade
    {
        [Required]
        [Display(Name = "N ID prop 14")]
        public int NIdProp14 { get; set; } // nIdProp14 (Primary key)

        [Required]
        [Display(Name = "N ID control 13")]
        public int NIdControl13 { get; set; } // nIdControl13

        [Display(Name = "N item")]
        public byte? NItem { get; set; } // nItem

        [Required(AllowEmptyStrings = true)]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "S texto")]
        public string STexto { get; set; } // sTexto (length: 60)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "S descripcion")]
        public string SDescripcion { get; set; } // sDescripcion (length: 200)

        [Display(Name = "N ID tipo trafico 25")]
        public int? NIdTipoTrafico25 { get; set; } // nIdTipoTrafico25

        [Required]
        [Display(Name = "N idioma")]
        public byte NIdioma { get; set; } // nIdioma

        // Foreign keys

        /// <summary>
        /// Parent SIR_Sir25TiposTrafico pointed by [SIRA_14_CONTROLES_PROPIEDADES].([NIdTipoTrafico25]) (FK_SIRA_14_CONTROLES_PROPIEDADES_SIR_25_TIPOS_TRAFICO)
        /// </summary>
        public virtual SIR_Sir25TiposTrafico SIR_Sir25TiposTrafico { get; set; } // FK_SIRA_14_CONTROLES_PROPIEDADES_SIR_25_TIPOS_TRAFICO

        /// <summary>
        /// Parent SIRAdmin_Sira13ControlesSistema pointed by [SIRA_14_CONTROLES_PROPIEDADES].([NIdControl13]) (FK_SIRA_14_CONTROLES_PROPIEDADES_SIRA_13_CONTROLES_SISTEMA)
        /// </summary>
        public virtual SIRAdmin_Sira13ControlesSistema SIRAdmin_Sira13ControlesSistema { get; set; } // FK_SIRA_14_CONTROLES_PROPIEDADES_SIRA_13_CONTROLES_SISTEMA
    }

}
// </auto-generated>
