// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // SIRA_29_ESTRUCT_ARCH_RESPUESTA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SIRAdmin_Sira29EstructArchRespuestaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SIRAdmin_Sira29EstructArchRespuesta>
    {
        public SIRAdmin_Sira29EstructArchRespuestaConfiguration()
            : this("SIRAdmin")
        {
        }

        public SIRAdmin_Sira29EstructArchRespuestaConfiguration(string schema)
        {
            ToTable("SIRA_29_ESTRUCT_ARCH_RESPUESTA", schema);
            HasKey(x => x.NIdEstArcRes29);

            Property(x => x.NIdEstArcRes29).HasColumnName(@"nIdEstArcRes29").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SPrefijo).HasColumnName(@"sPrefijo").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(3);
            Property(x => x.SExtension).HasColumnName(@"sExtension").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(3);
            Property(x => x.NIdTipoArch28).HasColumnName(@"nIdTipoArch28").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.SIRAdmin_Sira28TiposDeArchivo).WithMany(b => b.SIRAdmin_Sira29EstructArchRespuesta).HasForeignKey(c => c.NIdTipoArch28).WillCascadeOnDelete(false); // FK_SIRA_29_ESTRUCT_ARCH_RESPUESTA_SIRA_28_TIPOS_DE_ARCHIVO
            HasMany(t => t.SIR_Sir247ServicioPrevalidacion).WithMany(t => t.SIRAdmin_Sira29EstructArchRespuesta).Map(m =>
            {
                m.ToTable("SIRA_30_ARCH_RESP_SERVICIO", "SIRAdmin");
                m.MapLeftKey("nIdEstArcRes29");
                m.MapRightKey("nIdServPre247");
            });
        }
    }

}
// </auto-generated>
