// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // sis_grid
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SisGrid
    {
        [Required]
        [Display(Name = "Id grid")]
        public int IdGrid { get; set; } // id_grid (Primary key)

        [MaxLength(150)]
        [StringLength(150)]
        [Display(Name = "Origen")]
        public string Origen { get; set; } // origen (length: 150)

        [Display(Name = "Formato")]
        public string Formato { get; set; } // formato
    }

}
// </auto-generated>
