// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // sis_layout_rel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SisLayoutRel
    {
        [Required]
        [Display(Name = "Id r")]
        public int IdR { get; set; } // id_r (Primary key)

        [Display(Name = "Id l")]
        public int? IdL { get; set; } // id_l

        [Display(Name = "Id ent")]
        public int? IdEnt { get; set; } // id_ent

        [Display(Name = "Id tbl")]
        public int? IdTbl { get; set; } // id_tbl

        [Display(Name = "Status")]
        public int? Status { get; set; } // status
    }

}
// </auto-generated>
