// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // sis_mtto_bd
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SisMttoBd
    {
        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Clave")]
        public string Clave { get; set; } // clave (Primary key) (length: 100)

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Des")]
        public string Des { get; set; } // des

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Desc larg")]
        public string DescLarg { get; set; } // desc_larg

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Query")]
        public string Query { get; set; } // query

        public SisMttoBd()
        {
            Clave = "";
            Des = "";
            DescLarg = "";
            Query = "";
        }
    }

}
// </auto-generated>
