// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // sis_ped_fac
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SisPedFacConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SisPedFac>
    {
        public SisPedFacConfiguration()
            : this("dbo")
        {
        }

        public SisPedFacConfiguration(string schema)
        {
            ToTable("sis_ped_fac", schema);
            HasKey(x => x.IdPedFac);

            Property(x => x.IdPedFac).HasColumnName(@"id_ped_fac").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdPed).HasColumnName(@"id_ped").HasColumnType("int").IsRequired();
            Property(x => x.NoFac).HasColumnName(@"no_fac").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(40);
            Property(x => x.PaisOri).HasColumnName(@"pais_ori").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(3);
            Property(x => x.MdaFac).HasColumnName(@"mda_fac").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(3);
            Property(x => x.ValMdaExt).HasColumnName(@"val_mda_ext").HasColumnType("float").IsRequired();
            Property(x => x.ValMdaUsd).HasColumnName(@"val_mda_usd").HasColumnType("float").IsRequired();
            Property(x => x.Incoterm).HasColumnName(@"incoterm").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(3);
            Property(x => x.Fecha).HasColumnName(@"fecha").HasColumnType("datetime").IsRequired();
            Property(x => x.IdUsr).HasColumnName(@"id_usr").HasColumnType("int").IsRequired();
            Property(x => x.FecReg).HasColumnName(@"fec_reg").HasColumnType("datetime").IsRequired();
            Property(x => x.Entidadfacturacion).HasColumnName(@"entidadfacturacion").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Cvefiscalprov).HasColumnName(@"cvefiscalprov").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(40);
            Property(x => x.Nomprov).HasColumnName(@"nomprov").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.Calleprov).HasColumnName(@"calleprov").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.Numintprov).HasColumnName(@"numintprov").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(40);
            Property(x => x.Numextprov).HasColumnName(@"numextprov").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(40);
            Property(x => x.Cpprov).HasColumnName(@"cpprov").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(40);
            Property(x => x.Mpioprov).HasColumnName(@"mpioprov").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(200);
            Property(x => x.IdProv1G).HasColumnName(@"id_prov1g").HasColumnType("int").IsRequired();
            Property(x => x.IdPedimento).HasColumnName(@"id_pedimento").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
