// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // sis_rel_ant_ped_oc
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SisRelAntPedOc
    {
        [Required]
        [Display(Name = "Id sis rel ant ped oc")]
        public int IdSisRelAntPedOc { get; set; } // id_sis_rel_ant_ped_oc (Primary key)

        [Required]
        [Display(Name = "Id ant")]
        public int IdAnt { get; set; } // id_ant

        [Required]
        [Display(Name = "Num ant")]
        public int NumAnt { get; set; } // num_ant

        [Required]
        [Display(Name = "Id tip doc")]
        public int IdTipDoc { get; set; } // id_tip_doc

        [Required]
        [Display(Name = "Id oc ped")]
        public int IdOcPed { get; set; } // id_oc_ped

        [Required]
        [Display(Name = "Num doc")]
        public int NumDoc { get; set; } // num_doc

        [Required]
        [Display(Name = "Mto apl")]
        public double MtoApl { get; set; } // mto_apl

        [Required]
        [Display(Name = "Mto apl bse")]
        public double MtoAplBse { get; set; } // mto_apl_bse

        [Required]
        [Display(Name = "Id mda ant")]
        public int IdMdaAnt { get; set; } // id_mda_ant

        [Required]
        [Display(Name = "Id mda doc")]
        public int IdMdaDoc { get; set; } // id_mda_doc

        [Required]
        [Display(Name = "Tc ant")]
        public double TcAnt { get; set; } // tc_ant

        [Required]
        [Display(Name = "Tc doc")]
        public double TcDoc { get; set; } // tc_doc

        [Required]
        [Display(Name = "Oper")]
        public int Oper { get; set; } // oper

        public SisRelAntPedOc()
        {
            IdAnt = 0;
            NumAnt = 0;
            IdTipDoc = 0;
            IdOcPed = 0;
            NumDoc = 0;
            MtoApl = 0;
            MtoAplBse = 0;
            IdMdaAnt = 0;
            IdMdaDoc = 0;
            TcAnt = 0;
            TcDoc = 0;
            Oper = 0;
        }
    }

}
// </auto-generated>
