// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // FCM_02_BITACORA_PUSH
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SOFTDEM_Fcm02BitacoraPush
    {
        [Required]
        [Display(Name = "N ID bitacora push 02")]
        public int NIdBitacoraPush02 { get; set; } // nIdBitacoraPush02 (Primary key)

        [Display(Name = "N ID token push 01")]
        public int? NIdTokenPush01 { get; set; } // nIdTokenPush01

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "S mensaje")]
        public string SMensaje { get; set; } // sMensaje

        [Display(Name = "S jsonr equest")]
        public string SJsonRequest { get; set; } // sJSONRequest

        [Display(Name = "S jsonr esponse")]
        public string SJsonResponse { get; set; } // sJSONResponse

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "D fecha")]
        public System.DateTime DFecha { get; set; } // dFecha

        [Required]
        [Display(Name = "N response status code")]
        public int NResponseStatusCode { get; set; } // nResponseStatusCode

        // Reverse navigation

        /// <summary>
        /// Child SIR_Sir797NotificacionSirApp (Many-to-Many) mapped by table [SIR_798_BITACORA_NOTIFICACIONES_SIR_APP]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SIR_Sir797NotificacionSirApp> SIR_Sir797NotificacionSirApp { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent SOFTDEM_Fcm01TokenPush pointed by [FCM_02_BITACORA_PUSH].([NIdTokenPush01]) (FK_FCM_02_BITACORA_PUSH_FCM_01_TOKEN_PUSH)
        /// </summary>
        public virtual SOFTDEM_Fcm01TokenPush SOFTDEM_Fcm01TokenPush { get; set; } // FK_FCM_02_BITACORA_PUSH_FCM_01_TOKEN_PUSH

        public SOFTDEM_Fcm02BitacoraPush()
        {
            SIR_Sir797NotificacionSirApp = new System.Collections.Generic.List<SIR_Sir797NotificacionSirApp>();
        }
    }

}
// </auto-generated>
