// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // tabla_referencias
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TablaReferenciaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TablaReferencia>
    {
        public TablaReferenciaConfiguration()
            : this("dbo")
        {
        }

        public TablaReferenciaConfiguration(string schema)
        {
            ToTable("tabla_referencias", schema);
            HasKey(x => x.Importe);

            Property(x => x.Referencia).HasColumnName(@"referencia").HasColumnType("nchar").IsOptional().IsFixedLength().HasMaxLength(15);
            Property(x => x.Importe).HasColumnName(@"importe").HasColumnType("decimal").IsRequired().HasPrecision(18,2).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

}
// </auto-generated>
