// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // tbl_f9
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TblF9
    {
        [Required]
        [Display(Name = "Id f 9")]
        public int IdF9 { get; set; } // id_f9 (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; } // descripcion (length: 100)

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Qry")]
        public string Qry { get; set; } // qry

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Cmp filtrado")]
        public string CmpFiltrado { get; set; } // cmp_filtrado (length: 50)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Cmp llave")]
        public string CmpLlave { get; set; } // cmp_llave (length: 50)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Cmp text")]
        public string CmpText { get; set; } // cmp_text (length: 50)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Cmp orden")]
        public string CmpOrden { get; set; } // cmp_orden (length: 50)

        [Required]
        [Display(Name = "Status")]
        public int Status { get; set; } // status

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec reg")]
        public System.DateTime FecReg { get; set; } // fec_reg

        public TblF9()
        {
            Descripcion = "";
            Qry = "";
            CmpFiltrado = "";
            CmpLlave = "";
            CmpText = "";
            CmpOrden = "";
            Status = 0;
            FecReg = System.DateTime.Now;
        }
    }

}
// </auto-generated>
