// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // tra_viajes_car
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TraViajesCar
    {
        [Required]
        [Display(Name = "Id viaje car")]
        public int IdViajeCar { get; set; } // id_viaje_car (Primary key)

        [Required]
        [Display(Name = "Id viaje")]
        public int IdViaje { get; set; } // id_viaje

        [Required]
        [Display(Name = "No entrega")]
        public int NoEntrega { get; set; } // no_entrega

        [Required]
        [Display(Name = "No part")]
        public int NoPart { get; set; } // no_part

        [Required]
        [Display(Name = "Tip ope")]
        public byte TipOpe { get; set; } // tip_ope

        [Required]
        [Display(Name = "Id carga")]
        public int IdCarga { get; set; } // id_carga

        [Required]
        [Display(Name = "Id tip mercancia")]
        public int IdTipMercancia { get; set; } // id_tip_mercancia

        [Required(AllowEmptyStrings = true)]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Mercancia")]
        public string Mercancia { get; set; } // mercancia (length: 128)

        [Required]
        [Display(Name = "Id tip clas")]
        public int IdTipClas { get; set; } // id_tip_clas

        [Required]
        [Display(Name = "Id tip contenedor")]
        public int IdTipContenedor { get; set; } // id_tip_contenedor

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Contenedor")]
        public string Contenedor { get; set; } // contenedor (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Sello")]
        public string Sello { get; set; } // sello (length: 100)

        [Required]
        [Display(Name = "Id tip empaque")]
        public int IdTipEmpaque { get; set; } // id_tip_empaque

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Poliza")]
        public string Poliza { get; set; } // poliza (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Aa")]
        public string Aa { get; set; } // aa (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Patente")]
        public string Patente { get; set; } // patente (length: 10)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Aduana")]
        public string Aduana { get; set; } // aduana (length: 10)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Seccion")]
        public string Seccion { get; set; } // seccion (length: 10)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Pedimento")]
        public string Pedimento { get; set; } // pedimento (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Booking")]
        public string Booking { get; set; } // booking (length: 100)

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fec aa")]
        public System.DateTime FecAa { get; set; } // fec_aa

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Buque")]
        public string Buque { get; set; } // buque (length: 100)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Referencia")]
        public string Referencia { get; set; } // referencia (length: 100)

        [Required]
        [Display(Name = "Volumen")]
        public double Volumen { get; set; } // volumen

        [Required]
        [Display(Name = "Peso")]
        public double Peso { get; set; } // peso

        [Required]
        [Display(Name = "Valor")]
        public double Valor { get; set; } // valor

        [Required]
        [Display(Name = "Cant porte")]
        public double CantPorte { get; set; } // cant_porte

        [Required]
        [Display(Name = "Id pro")]
        public int IdPro { get; set; } // id_pro

        [Required(AllowEmptyStrings = true)]
        [MaxLength(160)]
        [StringLength(160)]
        [Display(Name = "Des pro")]
        public string DesPro { get; set; } // des_pro (length: 160)

        [Required]
        [Display(Name = "Cant")]
        public int Cant { get; set; } // cant

        [Required]
        [Display(Name = "Precio")]
        public double Precio { get; set; } // precio

        [Required]
        [Display(Name = "Total")]
        public double Total { get; set; } // total

        [Required]
        [Display(Name = "Precio bse")]
        public double PrecioBse { get; set; } // precio_bse

        [Required]
        [Display(Name = "Total bse")]
        public double TotalBse { get; set; } // total_bse

        [Required]
        [Display(Name = "Id nota")]
        public int IdNota { get; set; } // id_nota

        [Required]
        [Display(Name = "Id tip doc")]
        public int IdTipDoc { get; set; } // id_tip_doc

        [Required]
        [Display(Name = "Id doc")]
        public int IdDoc { get; set; } // id_doc

        [Required]
        [Display(Name = "Id doc det")]
        public int IdDocDet { get; set; } // id_doc_det

        public TraViajesCar()
        {
            IdViaje = 0;
            NoEntrega = 0;
            NoPart = 0;
            TipOpe = 0;
            IdCarga = 0;
            IdTipMercancia = 0;
            Mercancia = "";
            IdTipClas = 0;
            IdTipContenedor = 0;
            Contenedor = "";
            Sello = "";
            IdTipEmpaque = 0;
            Poliza = "";
            Aa = "";
            Patente = "";
            Aduana = "";
            Seccion = "";
            Pedimento = "";
            Booking = "";
            Buque = "";
            Referencia = "";
            Volumen = 0;
            Peso = 0;
            Valor = 0;
            CantPorte = 0;
            IdPro = 0;
            DesPro = "";
            Cant = 0;
            Precio = 0;
            Total = 0;
            PrecioBse = 0;
            TotalBse = 0;
            IdNota = 0;
            IdTipDoc = 0;
            IdDoc = 0;
            IdDocDet = 0;
        }
    }

}
// </auto-generated>
