// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // USER_TEMP_SCH
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class UserTempSchConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserTempSch>
    {
        public UserTempSchConfiguration()
            : this("dbo")
        {
        }

        public UserTempSchConfiguration(string schema)
        {
            ToTable("USER_TEMP_SCH", schema);
            HasKey(x => new { x.Userid, x.Cometime, x.Leavetime });

            Property(x => x.Userid).HasColumnName(@"USERID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Cometime).HasColumnName(@"COMETIME").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Leavetime).HasColumnName(@"LEAVETIME").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Overtime).HasColumnName(@"OVERTIME").HasColumnType("int").IsRequired();
            Property(x => x.Type).HasColumnName(@"TYPE").HasColumnType("smallint").IsOptional();
            Property(x => x.Flag).HasColumnName(@"FLAG").HasColumnType("smallint").IsOptional();
            Property(x => x.Schclassid).HasColumnName(@"SCHCLASSID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
