// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // vta_fac_complementos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class VtaFacComplementoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VtaFacComplemento>
    {
        public VtaFacComplementoConfiguration()
            : this("dbo")
        {
        }

        public VtaFacComplementoConfiguration(string schema)
        {
            ToTable("vta_fac_complementos", schema);
            HasKey(x => x.IdFac);

            Property(x => x.IdFac).HasColumnName(@"id_fac").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdSisTipMotivo).HasColumnName(@"id_sis_tip_motivo").HasColumnType("int").IsRequired();
            Property(x => x.IdSisTipOper).HasColumnName(@"id_sis_tip_oper").HasColumnType("int").IsRequired();
            Property(x => x.IdSisClavePed).HasColumnName(@"id_sis_clave_ped").HasColumnType("int").IsRequired();
            Property(x => x.CertOrig).HasColumnName(@"cert_orig").HasColumnType("int").IsRequired();
            Property(x => x.NumeroExpoConfiab).HasColumnName(@"NumeroExpoConfiab").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Incoterm).HasColumnName(@"Incoterm").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Subdiv).HasColumnName(@"subdiv").HasColumnType("int").IsRequired();
            Property(x => x.IdNotaObserv).HasColumnName(@"id_nota_observ").HasColumnType("int").IsRequired();
            Property(x => x.TcUsd).HasColumnName(@"TC_USD").HasColumnType("float").IsRequired();
            Property(x => x.TotUsd).HasColumnName(@"tot_USD").HasColumnType("float").IsRequired();
            Property(x => x.IdProp).HasColumnName(@"id_prop").HasColumnType("int").IsRequired();
            Property(x => x.IdRecep).HasColumnName(@"id_recep").HasColumnType("int").IsRequired();
            Property(x => x.IdDest).HasColumnName(@"id_dest").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
