// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // vucem1g_digitalizacion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Vucem1GDigitalizacionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Vucem1GDigitalizacion>
    {
        public Vucem1GDigitalizacionConfiguration()
            : this("dbo")
        {
        }

        public Vucem1GDigitalizacionConfiguration(string schema)
        {
            ToTable("vucem1g_digitalizacion", schema);
            HasKey(x => x.Idvucemdig);

            Property(x => x.Idvucemdig).HasColumnName(@"idvucemdig").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Folio).HasColumnName(@"folio").HasColumnType("int").IsOptional();
            Property(x => x.Rfcconsulta).HasColumnName(@"rfcconsulta").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.IdCli).HasColumnName(@"id_cli").HasColumnType("int").IsOptional();
            Property(x => x.ClaveDocVucem).HasColumnName(@"clave_doc_vucem").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.DescripcionDocVucem).HasColumnName(@"descripcion_doc_vucem").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Archivo).HasColumnName(@"archivo").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.NombreDocVucem).HasColumnName(@"nombre_doc_vucem").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.IdArch).HasColumnName(@"id_arch").HasColumnType("int").IsOptional();
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("int").IsOptional();
            Property(x => x.EMail).HasColumnName(@"e_mail").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.NumeroOperacion).HasColumnName(@"numero_operacion").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.EDocument).HasColumnName(@"e-document").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
        }
    }

}
// </auto-generated>
