// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // The table 'vucem1g_enc' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // vucem1g_enc
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Vucem1GEnc
    {
        [Display(Name = "Idvucem 1 g")]
        public int? Idvucem1G { get; set; } // idvucem1g

        [Display(Name = "Id tip opera")]
        public int? IdTipOpera { get; set; } // id_tip_opera

        [Display(Name = "Id tip doc")]
        public int? IdTipDoc { get; set; } // id_tip_doc

        [Display(Name = "Id tip figura")]
        public int? IdTipFigura { get; set; } // id_tip_figura

        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; } // descripcion

        [Display(Name = "Numoperacion")]
        public string Numoperacion { get; set; } // numoperacion

        [Display(Name = "Edocument")]
        public string Edocument { get; set; } // edocument

        [DataType(DataType.DateTime)]
        [Display(Name = "Fechaoperacion")]
        public System.DateTime? Fechaoperacion { get; set; } // fechaoperacion

        [DataType(DataType.DateTime)]
        [Display(Name = "Fechaacuse")]
        public System.DateTime? Fechaacuse { get; set; } // fechaacuse

        [DataType(DataType.DateTime)]
        [Display(Name = "Fechaedocument")]
        public System.DateTime? Fechaedocument { get; set; } // fechaedocument

        [Display(Name = "Total")]
        public double? Total { get; set; } // total

        [Display(Name = "Status")]
        public int? Status { get; set; } // status

        [DataType(DataType.DateTime)]
        [Display(Name = "Fechaexpedicion")]
        public System.DateTime? Fechaexpedicion { get; set; } // fechaexpedicion

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecharegistro")]
        public System.DateTime? Fecharegistro { get; set; } // fecharegistro

        [Display(Name = "Folio")]
        public int? Folio { get; set; } // folio
    }

}
// </auto-generated>
