// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace Hinojosa.Common.DataAccessLayer.Entidades
{

    // vucem_pat1g
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class VucemPat1GConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VucemPat1G>
    {
        public VucemPat1GConfiguration()
            : this("dbo")
        {
        }

        public VucemPat1GConfiguration(string schema)
        {
            ToTable("vucem_pat1g", schema);
            HasKey(x => x.IdPatCatSat);

            Property(x => x.IdPat).HasColumnName(@"id_pat").HasColumnType("int").IsOptional();
            Property(x => x.Patente).HasColumnName(@"patente").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Nombre).HasColumnName(@"nombre").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("int").IsOptional();
            Property(x => x.IdProv).HasColumnName(@"id_prov").HasColumnType("int").IsOptional();
            Property(x => x.IdPatCatSat).HasColumnName(@"id_pat_cat_sat").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

}
// </auto-generated>
